// SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package api

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ResourceGroupManagementServiceClient is the client API for ResourceGroupManagementService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ResourceGroupManagementServiceClient interface {
	// Create a new empty and inactive resource group.
	//
	// This is the first step in the resource group lifecycle. The created resource group is initially
	// empty (no resources) and inactive (no policies applied to hardware). Resources must be added
	// and the group activated before power policies take effect.
	ResourceGroupCreate(ctx context.Context, in *ResourceGroupCreateRequest, opts ...grpc.CallOption) (*ResourceGroupCreateResponse, error)
	// Deactivate and delete a given resource group
	//
	// This permanently removes the resource group and restores all associated hardware resources
	// to their topology-specified power policies. If the resource group is active, it is automatically
	// deactivated before deletion. This is typically called when a workload completes.
	ResourceGroupDelete(ctx context.Context, in *ResourceGroupDeleteRequest, opts ...grpc.CallOption) (*ResourceGroupDeleteResponse, error)
	// List all available resource groups
	//
	// Returns comprehensive information about all resource groups in the system, including their
	// activation status, assigned resources, and power policies. This is used for monitoring,
	// administration, and troubleshooting resource group state.
	ResourceGroupList(ctx context.Context, in *ResourceGroupListAllRequest, opts ...grpc.CallOption) (*ResourceGroupListAllResponse, error)
	// Add resources to a given resource group.
	//
	// This assigns compute resources (nodes) to the resource group. Resources can be assigned
	// group-level or entity-specific power policies. If the resource group is active, policies
	// are applied immediately and power is reallocated; if inactive, the assignment is stored
	// for activation.
	ResourceGroupAddResources(ctx context.Context, in *ResourceGroupAddResourcesRequest, opts ...grpc.CallOption) (*ResourceGroupAddResourcesResponse, error)
	// Remove resources from a given resource group.
	//
	// This removes compute resources from the resource group. If active, policies are reverted
	// to topology defaults and power is reallocated; if inactive, resources are simply removed.
	ResourceGroupRemoveResources(ctx context.Context, in *ResourceGroupRemoveResourcesRequest, opts ...grpc.CallOption) (*ResourceGroupRemoveResourcesResponse, error)
	// Activate a given resource group. The resource group must be inactive.
	//
	// This applies the resource group's power policies to the assigned hardware resources and
	// marks the group as active. The activation process validates power allocation constraints
	// and applies policies to the hardware. Once active, the resource group manages power
	// policies for its assigned resources until deactivation.
	ActivateResourceGroup(ctx context.Context, in *ActivateResourceGroupRequest, opts ...grpc.CallOption) (*ActivateResourceGroupResponse, error)
	// Update a resource group policy. The new policy affects all entities in the resource group
	// that does not have entity-level policies set. If the resource group is active, the policy is
	// validated and applied immediately.
	//
	// This changes the default power policy for the entire resource group. Entities with
	// entity-specific policies are not affected. If the resource group is active, the new policy
	// is immediately validated and applied to hardware. This enables dynamic power optimization
	// during workload execution.
	ResourceGroupUpdate(ctx context.Context, in *ResourceGroupUpdateRequest, opts ...grpc.CallOption) (*ResourceGroupUpdateResponse, error)
	// Update policies for some of the resources in the resource group. If the resource group is
	// active, the changes are applied immediately. This API may perform partial updates.
	//
	// This updates entity-specific power policies for selected resources in the group. If the
	// resource group is active, changes are immediately applied to hardware. The API supports
	// partial updates - some policy changes may succeed while others fail, allowing for
	// selective power optimization.
	ResourceGroupUpdateResources(ctx context.Context, in *ResourceGroupUpdateResourcesRequest, opts ...grpc.CallOption) (*ResourceGroupUpdateResourcesResponse, error)
	// UpdateGPUPolicies allows updating GPU policies without specifying the resource group.
	// Because of this, a single call may end up updating multiple resource groups. If the resource
	// groups are active, the changes are applied immediately.
	//
	// This provides direct GPU power management without requiring knowledge of resource group
	// assignments. It's designed for telemetry-driven power optimization where external monitoring
	// systems can adjust GPU power limits based on real-time performance data. A single call may
	// affect multiple resource groups if GPUs span multiple groups.
	UpdateGPUPolicies(ctx context.Context, in *UpdateGPUPoliciesRequest, opts ...grpc.CallOption) (*UpdateGPUPoliciesResponse, error)
	// Queries the server about the status of an asynchronous operation started by one of the service APIs
	//
	// Resource group operations (especially activation) can be performed asynchronously for better
	// scalability. This API allows clients to check the progress and results of these asynchronous
	// operations. The operation results are available until explicitly queried and forgotten.
	AsyncOperationStatus(ctx context.Context, in *ResourceGroupAsyncOperationStatusRequest, opts ...grpc.CallOption) (*ResourceGroupAsyncOperationStatus, error)
}

type resourceGroupManagementServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewResourceGroupManagementServiceClient(cc grpc.ClientConnInterface) ResourceGroupManagementServiceClient {
	return &resourceGroupManagementServiceClient{cc}
}

func (c *resourceGroupManagementServiceClient) ResourceGroupCreate(ctx context.Context, in *ResourceGroupCreateRequest, opts ...grpc.CallOption) (*ResourceGroupCreateResponse, error) {
	out := new(ResourceGroupCreateResponse)
	err := c.cc.Invoke(ctx, "/nvidia.dcpower.v1.ResourceGroupManagementService/ResourceGroupCreate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *resourceGroupManagementServiceClient) ResourceGroupDelete(ctx context.Context, in *ResourceGroupDeleteRequest, opts ...grpc.CallOption) (*ResourceGroupDeleteResponse, error) {
	out := new(ResourceGroupDeleteResponse)
	err := c.cc.Invoke(ctx, "/nvidia.dcpower.v1.ResourceGroupManagementService/ResourceGroupDelete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *resourceGroupManagementServiceClient) ResourceGroupList(ctx context.Context, in *ResourceGroupListAllRequest, opts ...grpc.CallOption) (*ResourceGroupListAllResponse, error) {
	out := new(ResourceGroupListAllResponse)
	err := c.cc.Invoke(ctx, "/nvidia.dcpower.v1.ResourceGroupManagementService/ResourceGroupList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *resourceGroupManagementServiceClient) ResourceGroupAddResources(ctx context.Context, in *ResourceGroupAddResourcesRequest, opts ...grpc.CallOption) (*ResourceGroupAddResourcesResponse, error) {
	out := new(ResourceGroupAddResourcesResponse)
	err := c.cc.Invoke(ctx, "/nvidia.dcpower.v1.ResourceGroupManagementService/ResourceGroupAddResources", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *resourceGroupManagementServiceClient) ResourceGroupRemoveResources(ctx context.Context, in *ResourceGroupRemoveResourcesRequest, opts ...grpc.CallOption) (*ResourceGroupRemoveResourcesResponse, error) {
	out := new(ResourceGroupRemoveResourcesResponse)
	err := c.cc.Invoke(ctx, "/nvidia.dcpower.v1.ResourceGroupManagementService/ResourceGroupRemoveResources", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *resourceGroupManagementServiceClient) ActivateResourceGroup(ctx context.Context, in *ActivateResourceGroupRequest, opts ...grpc.CallOption) (*ActivateResourceGroupResponse, error) {
	out := new(ActivateResourceGroupResponse)
	err := c.cc.Invoke(ctx, "/nvidia.dcpower.v1.ResourceGroupManagementService/ActivateResourceGroup", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *resourceGroupManagementServiceClient) ResourceGroupUpdate(ctx context.Context, in *ResourceGroupUpdateRequest, opts ...grpc.CallOption) (*ResourceGroupUpdateResponse, error) {
	out := new(ResourceGroupUpdateResponse)
	err := c.cc.Invoke(ctx, "/nvidia.dcpower.v1.ResourceGroupManagementService/ResourceGroupUpdate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *resourceGroupManagementServiceClient) ResourceGroupUpdateResources(ctx context.Context, in *ResourceGroupUpdateResourcesRequest, opts ...grpc.CallOption) (*ResourceGroupUpdateResourcesResponse, error) {
	out := new(ResourceGroupUpdateResourcesResponse)
	err := c.cc.Invoke(ctx, "/nvidia.dcpower.v1.ResourceGroupManagementService/ResourceGroupUpdateResources", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *resourceGroupManagementServiceClient) UpdateGPUPolicies(ctx context.Context, in *UpdateGPUPoliciesRequest, opts ...grpc.CallOption) (*UpdateGPUPoliciesResponse, error) {
	out := new(UpdateGPUPoliciesResponse)
	err := c.cc.Invoke(ctx, "/nvidia.dcpower.v1.ResourceGroupManagementService/UpdateGPUPolicies", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *resourceGroupManagementServiceClient) AsyncOperationStatus(ctx context.Context, in *ResourceGroupAsyncOperationStatusRequest, opts ...grpc.CallOption) (*ResourceGroupAsyncOperationStatus, error) {
	out := new(ResourceGroupAsyncOperationStatus)
	err := c.cc.Invoke(ctx, "/nvidia.dcpower.v1.ResourceGroupManagementService/AsyncOperationStatus", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ResourceGroupManagementServiceServer is the server API for ResourceGroupManagementService service.
// All implementations must embed UnimplementedResourceGroupManagementServiceServer
// for forward compatibility
type ResourceGroupManagementServiceServer interface {
	// Create a new empty and inactive resource group.
	//
	// This is the first step in the resource group lifecycle. The created resource group is initially
	// empty (no resources) and inactive (no policies applied to hardware). Resources must be added
	// and the group activated before power policies take effect.
	ResourceGroupCreate(context.Context, *ResourceGroupCreateRequest) (*ResourceGroupCreateResponse, error)
	// Deactivate and delete a given resource group
	//
	// This permanently removes the resource group and restores all associated hardware resources
	// to their topology-specified power policies. If the resource group is active, it is automatically
	// deactivated before deletion. This is typically called when a workload completes.
	ResourceGroupDelete(context.Context, *ResourceGroupDeleteRequest) (*ResourceGroupDeleteResponse, error)
	// List all available resource groups
	//
	// Returns comprehensive information about all resource groups in the system, including their
	// activation status, assigned resources, and power policies. This is used for monitoring,
	// administration, and troubleshooting resource group state.
	ResourceGroupList(context.Context, *ResourceGroupListAllRequest) (*ResourceGroupListAllResponse, error)
	// Add resources to a given resource group.
	//
	// This assigns compute resources (nodes) to the resource group. Resources can be assigned
	// group-level or entity-specific power policies. If the resource group is active, policies
	// are applied immediately and power is reallocated; if inactive, the assignment is stored
	// for activation.
	ResourceGroupAddResources(context.Context, *ResourceGroupAddResourcesRequest) (*ResourceGroupAddResourcesResponse, error)
	// Remove resources from a given resource group.
	//
	// This removes compute resources from the resource group. If active, policies are reverted
	// to topology defaults and power is reallocated; if inactive, resources are simply removed.
	ResourceGroupRemoveResources(context.Context, *ResourceGroupRemoveResourcesRequest) (*ResourceGroupRemoveResourcesResponse, error)
	// Activate a given resource group. The resource group must be inactive.
	//
	// This applies the resource group's power policies to the assigned hardware resources and
	// marks the group as active. The activation process validates power allocation constraints
	// and applies policies to the hardware. Once active, the resource group manages power
	// policies for its assigned resources until deactivation.
	ActivateResourceGroup(context.Context, *ActivateResourceGroupRequest) (*ActivateResourceGroupResponse, error)
	// Update a resource group policy. The new policy affects all entities in the resource group
	// that does not have entity-level policies set. If the resource group is active, the policy is
	// validated and applied immediately.
	//
	// This changes the default power policy for the entire resource group. Entities with
	// entity-specific policies are not affected. If the resource group is active, the new policy
	// is immediately validated and applied to hardware. This enables dynamic power optimization
	// during workload execution.
	ResourceGroupUpdate(context.Context, *ResourceGroupUpdateRequest) (*ResourceGroupUpdateResponse, error)
	// Update policies for some of the resources in the resource group. If the resource group is
	// active, the changes are applied immediately. This API may perform partial updates.
	//
	// This updates entity-specific power policies for selected resources in the group. If the
	// resource group is active, changes are immediately applied to hardware. The API supports
	// partial updates - some policy changes may succeed while others fail, allowing for
	// selective power optimization.
	ResourceGroupUpdateResources(context.Context, *ResourceGroupUpdateResourcesRequest) (*ResourceGroupUpdateResourcesResponse, error)
	// UpdateGPUPolicies allows updating GPU policies without specifying the resource group.
	// Because of this, a single call may end up updating multiple resource groups. If the resource
	// groups are active, the changes are applied immediately.
	//
	// This provides direct GPU power management without requiring knowledge of resource group
	// assignments. It's designed for telemetry-driven power optimization where external monitoring
	// systems can adjust GPU power limits based on real-time performance data. A single call may
	// affect multiple resource groups if GPUs span multiple groups.
	UpdateGPUPolicies(context.Context, *UpdateGPUPoliciesRequest) (*UpdateGPUPoliciesResponse, error)
	// Queries the server about the status of an asynchronous operation started by one of the service APIs
	//
	// Resource group operations (especially activation) can be performed asynchronously for better
	// scalability. This API allows clients to check the progress and results of these asynchronous
	// operations. The operation results are available until explicitly queried and forgotten.
	AsyncOperationStatus(context.Context, *ResourceGroupAsyncOperationStatusRequest) (*ResourceGroupAsyncOperationStatus, error)
	mustEmbedUnimplementedResourceGroupManagementServiceServer()
}

// UnimplementedResourceGroupManagementServiceServer must be embedded to have forward compatible implementations.
type UnimplementedResourceGroupManagementServiceServer struct {
}

func (UnimplementedResourceGroupManagementServiceServer) ResourceGroupCreate(context.Context, *ResourceGroupCreateRequest) (*ResourceGroupCreateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ResourceGroupCreate not implemented")
}
func (UnimplementedResourceGroupManagementServiceServer) ResourceGroupDelete(context.Context, *ResourceGroupDeleteRequest) (*ResourceGroupDeleteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ResourceGroupDelete not implemented")
}
func (UnimplementedResourceGroupManagementServiceServer) ResourceGroupList(context.Context, *ResourceGroupListAllRequest) (*ResourceGroupListAllResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ResourceGroupList not implemented")
}
func (UnimplementedResourceGroupManagementServiceServer) ResourceGroupAddResources(context.Context, *ResourceGroupAddResourcesRequest) (*ResourceGroupAddResourcesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ResourceGroupAddResources not implemented")
}
func (UnimplementedResourceGroupManagementServiceServer) ResourceGroupRemoveResources(context.Context, *ResourceGroupRemoveResourcesRequest) (*ResourceGroupRemoveResourcesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ResourceGroupRemoveResources not implemented")
}
func (UnimplementedResourceGroupManagementServiceServer) ActivateResourceGroup(context.Context, *ActivateResourceGroupRequest) (*ActivateResourceGroupResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ActivateResourceGroup not implemented")
}
func (UnimplementedResourceGroupManagementServiceServer) ResourceGroupUpdate(context.Context, *ResourceGroupUpdateRequest) (*ResourceGroupUpdateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ResourceGroupUpdate not implemented")
}
func (UnimplementedResourceGroupManagementServiceServer) ResourceGroupUpdateResources(context.Context, *ResourceGroupUpdateResourcesRequest) (*ResourceGroupUpdateResourcesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ResourceGroupUpdateResources not implemented")
}
func (UnimplementedResourceGroupManagementServiceServer) UpdateGPUPolicies(context.Context, *UpdateGPUPoliciesRequest) (*UpdateGPUPoliciesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateGPUPolicies not implemented")
}
func (UnimplementedResourceGroupManagementServiceServer) AsyncOperationStatus(context.Context, *ResourceGroupAsyncOperationStatusRequest) (*ResourceGroupAsyncOperationStatus, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AsyncOperationStatus not implemented")
}
func (UnimplementedResourceGroupManagementServiceServer) mustEmbedUnimplementedResourceGroupManagementServiceServer() {
}

// UnsafeResourceGroupManagementServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ResourceGroupManagementServiceServer will
// result in compilation errors.
type UnsafeResourceGroupManagementServiceServer interface {
	mustEmbedUnimplementedResourceGroupManagementServiceServer()
}

func RegisterResourceGroupManagementServiceServer(s grpc.ServiceRegistrar, srv ResourceGroupManagementServiceServer) {
	s.RegisterService(&ResourceGroupManagementService_ServiceDesc, srv)
}

func _ResourceGroupManagementService_ResourceGroupCreate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResourceGroupCreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ResourceGroupManagementServiceServer).ResourceGroupCreate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/nvidia.dcpower.v1.ResourceGroupManagementService/ResourceGroupCreate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ResourceGroupManagementServiceServer).ResourceGroupCreate(ctx, req.(*ResourceGroupCreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ResourceGroupManagementService_ResourceGroupDelete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResourceGroupDeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ResourceGroupManagementServiceServer).ResourceGroupDelete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/nvidia.dcpower.v1.ResourceGroupManagementService/ResourceGroupDelete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ResourceGroupManagementServiceServer).ResourceGroupDelete(ctx, req.(*ResourceGroupDeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ResourceGroupManagementService_ResourceGroupList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResourceGroupListAllRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ResourceGroupManagementServiceServer).ResourceGroupList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/nvidia.dcpower.v1.ResourceGroupManagementService/ResourceGroupList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ResourceGroupManagementServiceServer).ResourceGroupList(ctx, req.(*ResourceGroupListAllRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ResourceGroupManagementService_ResourceGroupAddResources_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResourceGroupAddResourcesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ResourceGroupManagementServiceServer).ResourceGroupAddResources(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/nvidia.dcpower.v1.ResourceGroupManagementService/ResourceGroupAddResources",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ResourceGroupManagementServiceServer).ResourceGroupAddResources(ctx, req.(*ResourceGroupAddResourcesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ResourceGroupManagementService_ResourceGroupRemoveResources_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResourceGroupRemoveResourcesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ResourceGroupManagementServiceServer).ResourceGroupRemoveResources(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/nvidia.dcpower.v1.ResourceGroupManagementService/ResourceGroupRemoveResources",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ResourceGroupManagementServiceServer).ResourceGroupRemoveResources(ctx, req.(*ResourceGroupRemoveResourcesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ResourceGroupManagementService_ActivateResourceGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ActivateResourceGroupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ResourceGroupManagementServiceServer).ActivateResourceGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/nvidia.dcpower.v1.ResourceGroupManagementService/ActivateResourceGroup",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ResourceGroupManagementServiceServer).ActivateResourceGroup(ctx, req.(*ActivateResourceGroupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ResourceGroupManagementService_ResourceGroupUpdate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResourceGroupUpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ResourceGroupManagementServiceServer).ResourceGroupUpdate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/nvidia.dcpower.v1.ResourceGroupManagementService/ResourceGroupUpdate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ResourceGroupManagementServiceServer).ResourceGroupUpdate(ctx, req.(*ResourceGroupUpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ResourceGroupManagementService_ResourceGroupUpdateResources_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResourceGroupUpdateResourcesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ResourceGroupManagementServiceServer).ResourceGroupUpdateResources(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/nvidia.dcpower.v1.ResourceGroupManagementService/ResourceGroupUpdateResources",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ResourceGroupManagementServiceServer).ResourceGroupUpdateResources(ctx, req.(*ResourceGroupUpdateResourcesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ResourceGroupManagementService_UpdateGPUPolicies_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateGPUPoliciesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ResourceGroupManagementServiceServer).UpdateGPUPolicies(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/nvidia.dcpower.v1.ResourceGroupManagementService/UpdateGPUPolicies",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ResourceGroupManagementServiceServer).UpdateGPUPolicies(ctx, req.(*UpdateGPUPoliciesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ResourceGroupManagementService_AsyncOperationStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResourceGroupAsyncOperationStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ResourceGroupManagementServiceServer).AsyncOperationStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/nvidia.dcpower.v1.ResourceGroupManagementService/AsyncOperationStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ResourceGroupManagementServiceServer).AsyncOperationStatus(ctx, req.(*ResourceGroupAsyncOperationStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ResourceGroupManagementService_ServiceDesc is the grpc.ServiceDesc for ResourceGroupManagementService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ResourceGroupManagementService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "nvidia.dcpower.v1.ResourceGroupManagementService",
	HandlerType: (*ResourceGroupManagementServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ResourceGroupCreate",
			Handler:    _ResourceGroupManagementService_ResourceGroupCreate_Handler,
		},
		{
			MethodName: "ResourceGroupDelete",
			Handler:    _ResourceGroupManagementService_ResourceGroupDelete_Handler,
		},
		{
			MethodName: "ResourceGroupList",
			Handler:    _ResourceGroupManagementService_ResourceGroupList_Handler,
		},
		{
			MethodName: "ResourceGroupAddResources",
			Handler:    _ResourceGroupManagementService_ResourceGroupAddResources_Handler,
		},
		{
			MethodName: "ResourceGroupRemoveResources",
			Handler:    _ResourceGroupManagementService_ResourceGroupRemoveResources_Handler,
		},
		{
			MethodName: "ActivateResourceGroup",
			Handler:    _ResourceGroupManagementService_ActivateResourceGroup_Handler,
		},
		{
			MethodName: "ResourceGroupUpdate",
			Handler:    _ResourceGroupManagementService_ResourceGroupUpdate_Handler,
		},
		{
			MethodName: "ResourceGroupUpdateResources",
			Handler:    _ResourceGroupManagementService_ResourceGroupUpdateResources_Handler,
		},
		{
			MethodName: "UpdateGPUPolicies",
			Handler:    _ResourceGroupManagementService_UpdateGPUPolicies_Handler,
		},
		{
			MethodName: "AsyncOperationStatus",
			Handler:    _ResourceGroupManagementService_AsyncOperationStatus_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "v1/resourcegroup.proto",
}
