#
# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
generatorOptions:
  disableNameSuffixHash: true

namespace: nico-system

resources:
  - namespace.yaml
  - external-services.yaml
  - ../nico-base
  - ../nico-unbound-base

components:
  - ../components/imagepullsecret
  - ../components/boot-artifacts-containers

configMapGenerator:
  - name: nico-dns
    behavior: create
    literals:
      - "NICO_API=https://nico-api.nico-system.svc.cluster.local:1079"
  - name: nico-system-nico-database-config
    literals:
      - DB_HOST=nico-pg-cluster.postgres.svc.cluster.local
      - DB_PORT=5432
      - DB_NAME=nico_system_nico
      - SECRET_REF=nico-system.nico.nico-pg-cluster.credentials.postgresql.acid.zalan.do
  - name: vault-cluster-info
    literals:
      - VAULT_SERVICE=https://vault.vault.svc.cluster.local:8200
      - NICO_VAULT_MOUNT=secrets
      - NICO_VAULT_PKI_MOUNT=nicoca

patches:
  - patch: |-
      apiVersion: cert-manager.io/v1
      kind: Certificate
      metadata:
        name: nico-dns-certificate
      spec:
        dnsNames:
          - nico-dns.nico-system.svc.cluster.local
        uris:
          - spiffe://nico.local/nico-system/sa/nico-dns
    target:
      group: cert-manager.io
      version: v1
      kind: Certificate
      name: nico-dns-certificate
  - patch: |-
      kind: Certificate
      metadata:
        name: nico-pxe-certificate
      spec:
        dnsNames:
          - nico-pxe.nico-system.svc.cluster.local
        uris:
          - spiffe://nico.local/nico-system/sa/nico-pxe
    target:
      group: cert-manager.io
      version: v1
      kind: Certificate
      name: nico-pxe-certificate
  - patch: |-
      kind: Certificate
      metadata:
        name: nico-dhcp-certificate
      spec:
        dnsNames:
          - nico-dhcp.nico-system.svc.cluster.local
        uris:
          - spiffe://nico.local/nico-system/sa/nico-dhcp
    target:
      group: cert-manager.io
      version: v1
      kind: Certificate
      name: nico-dhcp-certificate
  - patch: |-
      kind: Certificate
      metadata:
        name: nico-api-certificate
      spec:
        dnsNames:
          - nico-api.nico-system.svc.cluster.local
          - nico-api.nico
        uris:
          - spiffe://nico.local/nico-system/sa/nico-api
    target:
      group: cert-manager.io
      version: v1
      kind: Certificate
      name: nico-api-certificate
  - patch: |-
      kind: Certificate
      metadata:
        name: nico-hardware-health-certificate
      spec:
        dnsNames:
          - nico-hardware-health.nico-system.svc.cluster.local
        uris:
          - spiffe://nico.local/nico-system/sa/nico-hardware-health
    target:
      group: cert-manager.io
      version: v1
      kind: Certificate
      name: nico-hardware-health-certificate
  - patch: |-
      kind: Certificate
      metadata:
        name: nico-ssh-console-rs-certificate
      spec:
        dnsNames:
          - nico-ssh-console-rs.nico-system.svc.cluster.local
        uris:
          - spiffe://nico.local/nico-system/sa/nico-ssh-console-rs
    target:
      group: cert-manager.io
      version: v1
      kind: Certificate
      name: nico-ssh-console-rs-certificate
  - patch: |-
      apiVersion: acid.zalan.do/v1
      kind: postgresql
      metadata:
        name: nico-pg-cluster
    target:
      group: acid.zalan.do
      version: v1
      kind: postgresql
      name: nico-pg-cluster
