# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

apiVersion: v2
name: nico-rest
description: Umbrella chart for the NICo REST API platform
type: application
version: 0.1.13
appVersion: "1.6.0"
keywords:
  - nico
  - bare-metal
  - rest
  - umbrella

dependencies:
  - name: nico-rest-common
    version: "0.1.0"
    condition: nico-rest-common.enabled
  - name: nico-rest-cert-manager
    version: "0.1.0"
    condition: nico-rest-cert-manager.enabled
  - name: nico-rest-api
    version: "0.1.1"
    condition: nico-rest-api.enabled
  - name: nico-rest-workflow
    version: "0.1.0"
    condition: nico-rest-workflow.enabled
  - name: nico-rest-site-manager
    version: "0.1.1"
    condition: nico-rest-site-manager.enabled
  - name: nico-rest-db
    version: "0.1.0"
    condition: nico-rest-db.enabled
