/*
 * SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
 * SPDX-License-Identifier: Apache-2.0
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

//! Doc-gate: every counter and histogram declared through the instrumentation
//! framework -- inline on a `#[derive(Event)]`, or once on a
//! `#[derive(MetricFamily)]` shared by several Events -- must have a row in the
//! checked-in metrics catalogue, `docs/observability/core_metrics.md`. A family
//! is the row for the metric it declares, and the Events recording it add none,
//! so a shared metric is documented once from one `describe`.
//!
//! The catalogue is regenerated by the `test_integration` metrics test, which
//! scrapes `/metrics`. That leaves a gap the CI repo-clean check cannot see: a
//! metric no test exercises is never scraped, so it can land with no catalogue
//! row and nothing complains. This check closes it from the source side --
//! it reads the `#[event(...)]` declarations directly, so a metric is caught
//! whether or not any test drives it at runtime.
//!
//! The scan parses each source file with `syn` and walks its item tree, so the
//! metric name is read as a proper Rust string literal (raw strings included),
//! `#[cfg(test)]` fixtures are excluded by their attribute or an enclosing
//! module's, and `#[event(...)]` in a doc-comment example is never seen (a doc
//! comment is not an item). It fails closed: a counter/histogram whose name
//! cannot be read, or an event-bearing file that cannot be parsed, is an error,
//! never a silent skip.
//!
//! `metric_name_unchecked` events are exempt: their exposed `/metrics` name is a
//! sanitized/suffixed transform of the declared name (dotted OpenTelemetry
//! names, the doubled `_total_total`), not the verbatim string, so a source
//! match is not meaningful. Cataloguing those precisely wants the events
//! registry from #3221; until then they stay documented by scrape-and-retain.

use std::path::{Path, PathBuf};

use eyre::{Context, bail};
use proc_macro2::{TokenStream, TokenTree};
use syn::{Attribute, Item, ItemStruct, Meta};
use walkdir::WalkDir;

static REPO_ROOT: &str = concat!(env!("CARGO_MANIFEST_DIR"), "/../.."); // crates/xtask/../..
const CATALOGUE: &str = "docs/observability/core_metrics.md";

/// A counter or histogram declared by a `#[derive(Event)]` `#[event(...)]`
/// site, keyed by its verbatim exposed name.
struct DeclaredMetric {
    name: String,
    kind: &'static str,
    describe: Option<String>,
    source: PathBuf,
}

pub(super) fn check(fix: bool) -> eyre::Result<()> {
    let repo_root = PathBuf::from(REPO_ROOT).canonicalize()?;
    let catalogue_path = repo_root.join(CATALOGUE);
    let catalogue =
        std::fs::read_to_string(&catalogue_path).with_context(|| format!("reading {CATALOGUE}"))?;

    let mut declared = Vec::new();
    for dir in ["crates", "rest-api"] {
        collect(&repo_root.join(dir), &repo_root, &mut declared)?;
    }

    let missing: Vec<&DeclaredMetric> = declared
        .iter()
        .filter(|m| !catalogue.contains(&format!("<td>{}</td>", m.name)))
        .collect();

    if missing.is_empty() {
        println!(
            "OK: all {} framework metrics are documented in {CATALOGUE}.",
            declared.len(),
        );
        return Ok(());
    }

    if fix {
        let updated = rebuild_catalogue(&catalogue, &missing)?;
        std::fs::write(&catalogue_path, updated).with_context(|| format!("writing {CATALOGUE}"))?;
        println!("Added {} missing row(s) to {CATALOGUE}:", missing.len());
        for m in &missing {
            println!("  + {} ({})", m.name, m.kind);
        }
        println!("Review and commit {CATALOGUE}.");
        return Ok(());
    }

    eprintln!(
        "{} framework metric(s) are declared with #[derive(Event)] or #[derive(MetricFamily)] \
         but missing from {CATALOGUE}:\n",
        missing.len(),
    );
    for m in &missing {
        eprintln!("  {} ({}) -- {}", m.name, m.kind, m.source.display());
        eprintln!("      {}", suggested_row(m));
    }
    eprintln!(
        "\nEvery metric declared through the instrumentation framework needs a row \
         in {CATALOGUE}, so the metric is documented even when no test scrapes it. Run \
         `cargo xtask check-metric-docs --fix` to add the row(s) above automatically, name-sorted and \
         with the Description column taken from the declaration's `describe`, then commit \
         {CATALOGUE}. \
         (metric_name_unchecked declarations are exempt -- their exposed name is a sanitized transform; see #3221.)"
    );
    std::process::exit(1);
}

/// Returns `catalogue` with each missing metric's row inserted into the table's
/// single byte-sorted block of `<tr>` rows.
///
/// The rows are re-sorted with the same byte order and row format the
/// `test_integration` generator uses (see [`suggested_row`] and [`html_escape`]),
/// so a later scrape-and-regenerate finds them already in place rather than
/// reshuffling -- and running `--fix` twice is a no-op.
fn rebuild_catalogue(catalogue: &str, missing: &[&DeclaredMetric]) -> eyre::Result<String> {
    let lines: Vec<&str> = catalogue.lines().collect();
    // The table is a header row (`<td>Name</td>...`) followed by a contiguous,
    // byte-sorted run of `<tr>` data rows. Anchor on the header, then take the
    // run that follows it.
    let header = lines
        .iter()
        .position(|l| l.starts_with("<tr>") && l.contains("<td>Name</td>"))
        .ok_or_else(|| eyre::eyre!("{CATALOGUE}: no table header row to anchor on"))?;
    let start = header + 1;
    let end = start
        + lines[start..]
            .iter()
            .take_while(|l| l.starts_with("<tr>"))
            .count();

    let mut rows: Vec<String> = lines[start..end].iter().map(|&s| s.to_string()).collect();
    rows.extend(missing.iter().map(|m| suggested_row(m)));
    rows.sort(); // `str` orders by bytes, matching the catalogue's sort.

    let mut out = String::with_capacity(catalogue.len() + missing.len() * 96);
    for line in &lines[..start] {
        out.push_str(line);
        out.push('\n');
    }
    for row in &rows {
        out.push_str(row);
        out.push('\n');
    }
    for line in &lines[end..] {
        out.push_str(line);
        out.push('\n');
    }
    Ok(out)
}

fn collect(dir: &Path, repo_root: &Path, out: &mut Vec<DeclaredMetric>) -> eyre::Result<()> {
    for entry in WalkDir::new(dir) {
        // Fail closed: a scan root that is missing or unreadable surfaces as the
        // error WalkDir yields, and must abort the gate rather than let it scan
        // zero files and still report "OK" -- the silent skip the module avoids.
        let entry = entry
            .with_context(|| format!("metric-docs gate: walking scan root {}", dir.display()))?;
        if !entry.file_type().is_file() {
            continue;
        }
        let path = entry.path();
        if path.extension().and_then(|e| e.to_str()) != Some("rs") {
            continue;
        }
        let rel = path.strip_prefix(repo_root).unwrap_or(path);
        if skip_path(rel) {
            continue;
        }
        let src =
            std::fs::read_to_string(path).with_context(|| format!("reading {}", path.display()))?;
        // Only files that declare a metric are worth parsing; but once a file
        // does, a parse failure is loud -- never a silent skip of a metric. A
        // metric family need not sit next to an Event (a family shared across
        // crates lives in neither), so `#[metric(` is a trigger of its own.
        if !src.contains("#[event(") && !src.contains("#[metric(") {
            continue;
        }
        let file = syn::parse_file(&src).with_context(|| {
            format!(
                "{} declares #[event(...)] or #[metric(...)] but the metric-docs gate could not \
                 parse it",
                rel.display()
            )
        })?;
        collect_items(&file.items, false, rel, out)?;
    }
    Ok(())
}

/// Walks the module item tree, carrying whether an enclosing module is
/// `#[cfg(test)]`. Production events are module-level structs, so fn bodies and
/// impl blocks (where test fixtures live) are deliberately not descended into.
fn collect_items(
    items: &[Item],
    in_test: bool,
    source: &Path,
    out: &mut Vec<DeclaredMetric>,
) -> eyre::Result<()> {
    for item in items {
        match item {
            Item::Mod(module) => {
                let module_in_test = in_test || has_cfg_test(&module.attrs);
                if let Some((_, sub_items)) = &module.content {
                    collect_items(sub_items, module_in_test, source, out)?;
                }
            }
            Item::Struct(item_struct) => {
                if in_test || has_cfg_test(&item_struct.attrs) {
                    continue;
                }
                if derives_metric_family(&item_struct.attrs) {
                    if let Some(metric) = family_metric(item_struct, source)? {
                        out.push(metric);
                    }
                } else if derives_event(&item_struct.attrs)
                    && let Some(metric) = event_metric(&item_struct.attrs, source)?
                {
                    out.push(metric);
                }
            }
            // An enum Event declares one metric for the whole enum, exactly as
            // a struct Event does. Without this arm the gate would not see it
            // at all -- and would still report OK, which is the wrong way for a
            // contract check to fail.
            Item::Enum(item_enum) => {
                if in_test || has_cfg_test(&item_enum.attrs) {
                    continue;
                }
                if derives_event(&item_enum.attrs)
                    && let Some(metric) = event_metric(&item_enum.attrs, source)?
                {
                    out.push(metric);
                }
            }
            _ => {}
        }
    }
    Ok(())
}

/// Reads the `#[event(...)]` of a `#[derive(Event)]` struct. `Ok(None)` when it
/// declares no counter/histogram (metric = none) or is `metric_name_unchecked`;
/// errors (fails closed) when a counter/histogram's name cannot be read.
fn event_metric(attrs: &[Attribute], source: &Path) -> eyre::Result<Option<DeclaredMetric>> {
    let mut name = None;
    let mut metric = None;
    let mut describe = None;
    let mut metric_name_unchecked = false;
    // The derive accumulates every `#[event(...)]` on the struct, so reading
    // only the first would let a split declaration hide its metric name from
    // the gate and slip through undocumented.
    for attr in attrs.iter().filter(|a| a.path().is_ident("event")) {
        attr.parse_nested_meta(|meta| {
            if meta.path.is_ident("metric_name") {
                name = Some(meta.value()?.parse::<syn::LitStr>()?.value());
            } else if meta.path.is_ident("event_name") {
                // The event's identity, not the exposed metric name -- ignore it.
                let _: syn::LitStr = meta.value()?.parse()?;
            } else if meta.path.is_ident("metric") {
                metric = Some(meta.value()?.parse::<syn::Ident>()?.to_string());
            } else if meta.path.is_ident("metric_family") {
                // The family owns the metric and its catalogue row, so an Event
                // that names one contributes none. Consume the path and leave
                // `metric` unset, which skips this Event below.
                let _: syn::Path = meta.value()?.parse()?;
            } else if meta.path.is_ident("describe") {
                describe = Some(meta.value()?.parse::<syn::LitStr>()?.value());
            } else if meta.path.is_ident("metric_name_unchecked") {
                metric_name_unchecked = true;
            } else if meta.path.is_ident("describe_unchecked") {
                // A flag with no value, and no bearing on documentation.
            } else if meta.path.is_ident("message") {
                // Either a string literal or the `dynamic` ident (message = dynamic);
                // the gate ignores the value but must consume whichever form.
                let value = meta.value()?;
                if value.peek(syn::LitStr) {
                    let _: syn::LitStr = value.parse()?;
                } else {
                    let _: syn::Ident = value.parse()?;
                }
            } else if meta.path.is_ident("component") || meta.path.is_ident("unit") {
                // String-valued keys the gate ignores; consumed to keep parsing.
                let _: syn::LitStr = meta.value()?.parse()?;
            } else if meta.path.is_ident("log") {
                let _: syn::Ident = meta.value()?.parse()?;
            } else if meta.path.is_ident("labels") {
                // An enum Event's label schema. The gate checks the metric's
                // name and description, not its dimensions, so step over it.
                let content;
                syn::parenthesized!(content in meta.input);
                let _: proc_macro2::TokenStream = content.parse()?;
            } else {
                // An event key the derive defines but this gate has not been taught:
                // fail closed so the two stay in sync.
                return Err(meta.error("metric-docs gate: unrecognized `event` key"));
            }
            Ok(())
        })
        .with_context(|| format!("parsing #[event(...)] in {}", source.display()))?;
    }

    let kind = match metric.as_deref() {
        Some("counter") => "counter",
        Some("histogram") => "histogram",
        Some("gauge") => "gauge",
        // metric = none, or no metric side: nothing to catalogue.
        _ => return Ok(None),
    };
    if metric_name_unchecked {
        return Ok(None);
    }
    let Some(name) = name else {
        bail!(
            "{}: an #[event(...)] with metric = {kind} has no readable name; the metric-docs \
             gate will not skip it silently",
            source.display(),
        );
    };
    Ok(Some(DeclaredMetric {
        name,
        kind,
        describe,
        source: source.to_path_buf(),
    }))
}

/// The instrumentation crate's own `#[event]` sites are doc examples and test
/// fixtures; xtask (this crate) only mentions `#[event(` in scanner strings;
/// `tests`/`benches` trees and `tests.rs` modules are never production metrics.
fn skip_path(rel: &Path) -> bool {
    let path = rel.to_string_lossy();
    if path.starts_with("crates/instrument/")
        || path.starts_with("crates/instrument-macros/")
        || path.starts_with("crates/xtask/")
    {
        return true;
    }
    if matches!(
        rel.file_stem().and_then(|s| s.to_str()),
        Some("tests" | "test")
    ) {
        return true;
    }
    rel.components().any(|c| {
        matches!(
            c.as_os_str().to_str(),
            Some("tests") | Some("benches") | Some("target")
        )
    })
}

/// Whether `#[derive(...)]` names `Event` (bare or path-qualified, e.g.
/// `carbide_instrument::Event`).
fn derives_event(attrs: &[Attribute]) -> bool {
    attrs.iter().any(|attr| {
        attr.path().is_ident("derive")
            && matches!(&attr.meta, Meta::List(list) if tokens_have_ident(list.tokens.clone(), "Event"))
    })
}

fn derives_metric_family(attrs: &[Attribute]) -> bool {
    attrs.iter().any(|attr| {
        attr.path().is_ident("derive")
            && matches!(&attr.meta, Meta::List(list) if tokens_have_ident(list.tokens.clone(), "MetricFamily"))
    })
}

/// Reads the `#[metric(...)]` of a `#[derive(MetricFamily)]` struct. A family
/// declares one metric shared by every Event that records it, so the family is
/// the catalogue row and those Events contribute none. `Ok(None)` only for a
/// `metric_name_unchecked` family, matching the Event-side exemption.
fn family_metric(item: &ItemStruct, source: &Path) -> eyre::Result<Option<DeclaredMetric>> {
    let mut name = None;
    let mut kind = None;
    let mut describe = None;
    let mut metric_name_unchecked = false;
    // The derive accumulates every `#[metric(...)]` on the struct, so reading
    // only the first would let a split declaration hide its name from the gate
    // and slip through undocumented.
    for attr in item.attrs.iter().filter(|a| a.path().is_ident("metric")) {
        attr.parse_nested_meta(|meta| {
            if meta.path.is_ident("name") {
                name = Some(meta.value()?.parse::<syn::LitStr>()?.value());
            } else if meta.path.is_ident("kind") {
                kind = Some(meta.value()?.parse::<syn::Ident>()?.to_string());
            } else if meta.path.is_ident("describe") {
                describe = Some(meta.value()?.parse::<syn::LitStr>()?.value());
            } else if meta.path.is_ident("metric_name_unchecked") {
                metric_name_unchecked = true;
            } else if meta.path.is_ident("describe_unchecked") {
                // A flag with no value, and no bearing on documentation.
            } else if meta.path.is_ident("component") || meta.path.is_ident("unit") {
                // String-valued keys the gate ignores; consumed to keep parsing.
                let _: syn::LitStr = meta.value()?.parse()?;
            } else {
                // A metric key the derive defines but this gate has not been taught:
                // fail closed so the two stay in sync.
                return Err(meta.error("metric-docs gate: unrecognized `metric` key"));
            }
            Ok(())
        })
        .with_context(|| format!("parsing #[metric(...)] in {}", source.display()))?;
    }

    let kind = match kind.as_deref() {
        Some("counter") => "counter",
        Some("histogram") => "histogram",
        Some("gauge") => "gauge",
        // The derive requires a kind; a family without one does not compile.
        _ => return Ok(None),
    };
    if metric_name_unchecked {
        return Ok(None);
    }
    let Some(name) = name else {
        bail!(
            "{}: a #[metric(...)] family with kind = {kind} has no readable name; the \
             metric-docs gate will not skip it silently",
            source.display(),
        );
    };
    Ok(Some(DeclaredMetric {
        name,
        kind,
        describe,
        source: source.to_path_buf(),
    }))
}

/// Whether an attribute list carries `#[cfg(test)]` (also inside `all(...)` /
/// `any(...)`), ignoring a `not(test)` subtree.
fn has_cfg_test(attrs: &[Attribute]) -> bool {
    attrs.iter().any(|attr| {
        attr.path().is_ident("cfg")
            && matches!(&attr.meta, Meta::List(list) if predicate_mentions_test(list.tokens.clone()))
    })
}

/// A `test` predicate is active in a `cfg(...)` token stream: recurse into
/// `all(...)`/`any(...)` groups, but skip a `not(...)` subtree (its `test`
/// would negate to non-test).
fn predicate_mentions_test(tokens: TokenStream) -> bool {
    let mut iter = tokens.into_iter().peekable();
    while let Some(tt) = iter.next() {
        match tt {
            TokenTree::Ident(ident) if ident == "not" => {
                // Drop the argument group of `not(...)`.
                if matches!(iter.peek(), Some(TokenTree::Group(_))) {
                    iter.next();
                }
            }
            TokenTree::Ident(ident) if ident == "test" => return true,
            TokenTree::Group(group) if predicate_mentions_test(group.stream()) => return true,
            _ => {}
        }
    }
    false
}

/// Whether a token stream contains the identifier `wanted` at any nesting.
fn tokens_have_ident(tokens: TokenStream, wanted: &str) -> bool {
    tokens.into_iter().any(|tt| match tt {
        TokenTree::Ident(ident) => ident == wanted,
        TokenTree::Group(group) => tokens_have_ident(group.stream(), wanted),
        _ => false,
    })
}

/// The `<tr>` row a developer should add to the catalogue for a missing metric.
fn suggested_row(m: &DeclaredMetric) -> String {
    format!(
        "<tr><td>{}</td><td>{}</td><td>{}</td></tr>",
        m.name,
        m.kind,
        html_escape(m.describe.as_deref().unwrap_or("")),
    )
}

/// HTML entity escaping matching the catalogue generator (`askama_escape::Html`).
fn html_escape(s: &str) -> String {
    let mut out = String::with_capacity(s.len());
    for c in s.chars() {
        match c {
            '&' => out.push_str("&amp;"),
            '<' => out.push_str("&lt;"),
            '>' => out.push_str("&gt;"),
            '"' => out.push_str("&quot;"),
            '\'' => out.push_str("&#39;"),
            _ => out.push(c),
        }
    }
    out
}

#[cfg(test)]
mod tests {
    use std::path::{Path, PathBuf};

    use super::{DeclaredMetric, collect, collect_items, rebuild_catalogue};

    /// Collect the counter/histogram metrics the gate would require from a
    /// snippet of source (the same item walk the real scan uses).
    fn declared(src: &str) -> Vec<DeclaredMetric> {
        let file = syn::parse_file(src).expect("snippet parses");
        let mut out = Vec::new();
        collect_items(&file.items, false, Path::new("snippet.rs"), &mut out)
            .expect("no fail-closed error");
        out
    }

    /// A raw-string metric name (which the derive accepts) is read, not
    /// silently skipped -- the codex P2 hole.
    #[test]
    fn raw_string_name_is_collected() {
        let metrics = declared(
            r##"
            #[derive(Event)]
            #[event(metric_name = r"carbide_raw_total", component = "c", log = off, metric = counter,
                    describe = "Number of raw things")]
            struct RawNamed;

            #[derive(Event)]
            #[event(metric_name = r#"carbide_hashed_total"#, component = "c", log = off, metric = counter,
                    describe = "Number of hashed things")]
            struct HashNamed;
            "##,
        );
        let names: Vec<&str> = metrics.iter().map(|m| m.name.as_str()).collect();
        assert!(
            names.contains(&"carbide_raw_total"),
            "raw string name r\"...\" must be read, got {names:?}"
        );
        assert!(
            names.contains(&"carbide_hashed_total"),
            "raw string name r#\"...\"# must be read, got {names:?}"
        );
    }

    /// A cooked string name still round-trips (escapes handled by LitStr).
    #[test]
    fn cooked_string_name_is_collected() {
        let metrics = declared(
            r#"
            #[derive(Event)]
            #[event(metric_name = "carbide_cooked_total", component = "c", log = off, metric = counter,
                    describe = "Number of cooked things")]
            struct Cooked;
            "#,
        );
        assert_eq!(metrics.len(), 1);
        assert_eq!(metrics[0].name, "carbide_cooked_total");
    }

    /// A metric-backed event may declare `message = dynamic` (per-variant log
    /// wording); the gate consumes the ident form and still collects the row.
    #[test]
    fn dynamic_message_counter_is_collected() {
        let metrics = declared(
            r#"
            #[derive(Event)]
            #[event(metric_name = "carbide_dynmsg_total", component = "c", log = dynamic,
                    metric = counter, message = dynamic, describe = "Number of dynmsg things")]
            struct DynMsg;
            "#,
        );
        assert_eq!(metrics.len(), 1);
        assert_eq!(metrics[0].name, "carbide_dynmsg_total");
    }

    /// A family need not sit next to an Event -- one shared across crates lives
    /// in neither -- so the file-level scan filter must accept a file that
    /// declares only a family. This drives the real `collect`, which is where
    /// that filter lives (`declared` above parses a snippet directly).
    #[test]
    fn collect_scans_a_file_declaring_only_a_metric_family() {
        let dir = std::env::temp_dir().join("metric-docs-family-only-scan");
        let _ = std::fs::remove_dir_all(&dir);
        std::fs::create_dir_all(&dir).expect("temp scan root");
        std::fs::write(
            dir.join("family_only.rs"),
            r#"
            #[derive(MetricFamily)]
            #[metric(name = "carbide_shared_total", kind = counter, component = "c",
                     describe = "Number of shared things")]
            pub struct Shared {
                pub stage: Stage,
            }
            "#,
        )
        .expect("write family-only source");

        let mut out = Vec::new();
        collect(&dir, &dir, &mut out).expect("scan succeeds");
        let _ = std::fs::remove_dir_all(&dir);

        let names: Vec<&str> = out.iter().map(|m| m.name.as_str()).collect();
        assert_eq!(
            names,
            vec!["carbide_shared_total"],
            "a family-only file must reach the catalogue gate, got {names:?}"
        );
    }

    /// A metric family is the catalogue row for the metric it declares, and the
    /// Events that record it contribute none -- so a metric shared by several
    /// Events is documented once, from one describe.
    #[test]
    fn a_metric_family_is_the_catalogue_row_for_its_events() {
        let metrics = declared(
            r#"
            #[derive(MetricFamily)]
            #[metric(name = "carbide_family_total", kind = counter, component = "c",
                     describe = "Number of family things")]
            struct Family {
                stage: Stage,
            }

            #[derive(Event)]
            #[event(event_name = "first_failed", metric_family = Family, log = warn, message = "first")]
            struct First {
                #[label]
                stage: Stage,
            }

            #[derive(Event)]
            #[event(event_name = "second_failed", metric_family = Family, log = error, message = "second")]
            struct Second {
                #[label]
                stage: Stage,
            }
            "#,
        );
        let names: Vec<&str> = metrics.iter().map(|m| m.name.as_str()).collect();
        assert_eq!(
            names,
            vec!["carbide_family_total"],
            "the family owns the row and its Events add none, got {names:?}"
        );
        assert_eq!(
            metrics[0].describe.as_deref(),
            Some("Number of family things")
        );
    }

    /// A `metric_name_unchecked` family is exempt exactly as the Event-side
    /// escape hatch is, and a histogram family still lands a row.
    #[test]
    fn family_kinds_and_the_grandfathered_hatch() {
        let metrics = declared(
            r#"
            #[derive(MetricFamily)]
            #[metric(name = "carbide_family_duration_seconds", kind = histogram, component = "c",
                     describe = "Duration of family things")]
            struct Timed {}

            #[derive(MetricFamily)]
            #[metric(name = "legacy_family_total", kind = counter, metric_name_unchecked,
                     component = "c", describe = "Total number", describe_unchecked)]
            struct Legacy {}
            "#,
        );
        let names: Vec<&str> = metrics.iter().map(|m| m.name.as_str()).collect();
        assert_eq!(names, vec!["carbide_family_duration_seconds"]);
        assert_eq!(metrics[0].kind, "histogram");
    }

    /// Events under `#[cfg(test)]` -- on the struct or an enclosing module --
    /// are excluded, so unit-test fixtures do not demand catalogue rows.
    #[test]
    fn cfg_test_events_are_excluded() {
        let metrics = declared(
            r#"
            #[derive(Event)]
            #[event(metric_name = "carbide_prod_total", component = "c", log = off, metric = counter,
                    describe = "Number of prod things")]
            struct Prod;

            #[cfg(test)]
            mod tests {
                #[derive(Event)]
                #[event(metric_name = "carbide_modfixture_total", component = "c", log = off,
                        metric = counter, describe = "Number of fixtures")]
                struct ModFixture;
            }

            #[cfg(test)]
            #[derive(Event)]
            #[event(metric_name = "carbide_structfixture_total", component = "c", log = off,
                    metric = counter, describe = "Number of fixtures")]
            struct StructFixture;
            "#,
        );
        let names: Vec<&str> = metrics.iter().map(|m| m.name.as_str()).collect();
        assert_eq!(
            names,
            vec!["carbide_prod_total"],
            "only the non-test event should be collected, got {names:?}"
        );
    }

    /// `metric = none` and `metric_name_unchecked` events are not catalogue rows.
    #[test]
    fn non_metric_and_grandfathered_are_skipped() {
        let metrics = declared(
            r#"
            #[derive(Event)]
            #[event(metric_name = "carbide_logonly", component = "c", metric = none, message = "hi")]
            struct LogOnly;

            #[derive(Event)]
            #[event(metric_name = "carbide_legacy_total_total", metric_name_unchecked, component = "c",
                    log = off, metric = counter, describe = "Total number", describe_unchecked)]
            struct Legacy;
            "#,
        );
        let names: Vec<&str> = metrics.iter().map(|m| m.name.as_str()).collect();
        assert!(names.is_empty(), "got {names:?}");
    }

    /// `--fix` inserts each missing row in byte-sorted position, preserves the
    /// surrounding file, and is a no-op once the rows are present.
    #[test]
    fn fix_inserts_rows_in_sorted_position_and_is_idempotent() {
        let catalogue = concat!(
            "<table>\n",
            "<tr><td>Name</td><td>Type</td><td>Description</td></tr>\n",
            "<tr><td>carbide_apple_total</td><td>counter</td><td>Apples.</td></tr>\n",
            "<tr><td>carbide_cherry_total</td><td>counter</td><td>Cherries.</td></tr>\n",
            "</table>\n",
        );
        let banana = DeclaredMetric {
            name: "carbide_banana_total".into(),
            kind: "counter",
            describe: Some("Bananas.".into()),
            source: PathBuf::from("snippet.rs"),
        };
        let expected = concat!(
            "<table>\n",
            "<tr><td>Name</td><td>Type</td><td>Description</td></tr>\n",
            "<tr><td>carbide_apple_total</td><td>counter</td><td>Apples.</td></tr>\n",
            "<tr><td>carbide_banana_total</td><td>counter</td><td>Bananas.</td></tr>\n",
            "<tr><td>carbide_cherry_total</td><td>counter</td><td>Cherries.</td></tr>\n",
            "</table>\n",
        );
        let added = rebuild_catalogue(catalogue, &[&banana]).unwrap();
        assert_eq!(added, expected, "banana row lands between apple and cherry");
        // Re-running with nothing missing leaves the catalogue byte-for-byte.
        assert_eq!(
            rebuild_catalogue(&added, &[]).unwrap(),
            expected,
            "idempotent"
        );
    }
}
