#!/usr/bin/env -S bash -p
# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
set -x

HOSTNAME=$(hostname)

if [[ "$HOSTNAME" == "localhost" ]]; then
    echo "hostname cannot be 'localhost'"
    exit 1
fi

source /etc/otelcol-contrib/otelcol-wrapper-imports

# This should protect us on start-up in the event that bad extension config was left behind.
# We'll at least get the minimum expected metrics.
if /usr/bin/otelcol-contrib validate --config=/etc/otelcol-contrib/config.yaml ${ADDITIONAL_CONFIGS}; then
    exec /usr/bin/otelcol-contrib --config=/etc/otelcol-contrib/config.yaml ${ADDITIONAL_CONFIGS}
else
    echo "WARN: DPU service extension config found but does not pass validation so continuing without it."
    exec /usr/bin/otelcol-contrib --config=/etc/otelcol-contrib/config.yaml
fi
