{{- $supplementalCmName := default "" (get (default (dict) .Values.supplementalNetworkConfig) "name") -}}
{{- if or .Values.fmds.sign_proxy_url $supplementalCmName }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "nico-dpu-agent.fullname" . }}-config
  labels:
    {{- include "nico-dpu-agent.labels" . | nindent 4 }}
data:
  config.toml: |
    {{- with .Values.fmds.sign_proxy_url }}
    [machine-identity]
    sign-proxy-url = {{ . | quote }}
    {{- end }}
    {{- if $supplementalCmName }}
    [network]
    supplemental-config-path = "/etc/forge/supplemental-network-config/supplemental.json"
    {{- end }}
{{- end }}
