# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

apiVersion: v2
name: nico-rest-common
description: Helm chart for NICo REST common secrets and certificates
type: application
version: 0.1.0
appVersion: "latest"
keywords:
  - nico
  - rest
  - common
