#!/bin/sh
# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -e

. /usr/share/debconf/confmodule

if [ "$1" = "configure" ]; then
    # TODO:  is this needed for scout?
	# Ensure the core file directory exists
	# Must match /proc/sys/kernel/core_pattern
	# mkdir -p /var/support/core

	systemctl daemon-reload
	systemctl enable forge-scout.service

	# Do not depend on starting services now, as this package is installed early in setup
	# and should not hang or cause out of order steps in discovery workflows. The discovery
	# workflow will reboot shortly after this package is installed, so it is best to rely
	# on the reboot process to start the services enabled above.

	#if [ -n "$2" ]; then
 		# The package is being upgraded and not installed for the first time...
	#fi
fi
