# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

# carbide-rest-site-manager Service
apiVersion: v1
kind: Service
metadata:
  name: carbide-rest-site-manager
  labels:
    app: carbide-rest-site-manager
spec:
  type: ClusterIP
  ports:
    - port: 8100
      targetPort: 8100
      name: https
  selector:
    app: carbide-rest-site-manager

