#
# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nico-ntp
  namespace: default
spec:
  serviceName: nico-ntp
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: nico-ntp
  template:
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app.kubernetes.io/name
                      operator: In
                      values:
                        - nico-ntp
                topologyKey: "kubernetes.io/hostname"
      containers:
        - name: chrony
          image: 'dockurr/chrony:latest'
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 123
              protocol: UDP
          env:
            - name: NTP_SERVERS
              value: "time1.google.com,time2.google.com,time3.google.com,time4.google.com,nico-ntp-1.nico-ntp.nico-system.svc.cluster.local,nico-ntp-2.nico-ntp.nico-system.svc.cluster.local,nico-ntp-3.nico-ntp.nico-system.svc.cluster.local"
            - name: NTP_DIRECTIVES
              value: "ratelimit"
