#
# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

generatorOptions:
  disableNameSuffixHash: true

buildMetadata: [originAnnotations]

resources:
  - nico-system

images:
  - name: yourdockerregistry.com/path/to/nico-core
    newName: NICO_REGISTRY_PATH/nico-core
    newTag: NICO_TAG
  - name: yourdockerregistry.com/path/to/boot-artifacts-aarch64
    newName: NICO_REGISTRY_PATH/boot-artifacts-aarch64
    newTag: BOOT_ARTIFACTS_AARCH64_TAG
  - name: yourdockerregistry.com/path/to/boot-artifacts-x86_64
    newName: NICO_REGISTRY_PATH/boot-artifacts-x86_64
    newTag: BOOT_ARTIFACTS_X86_TAG
  - name: yourdockerregistry.com/path/to/nvmetal-scout-burn-in
    newName: NICO_REGISTRY_PATH/machine_validation
    newTag: MACHINE_VALIDATION_TAG

#
# IP addresses are from the metallb IP pool from this environment
#
patches:
  - patch: |-
      - op: add
        path: "/metadata/annotations/metallb.universe.tf~1loadBalancerIPs"
        value: NICO_DHCP_EXTERNAL_IP
    target:
      version: v1
      kind: Service
      name: nico-dhcp-external
  - patch: |-
      - op: add
        path: "/metadata/annotations/metallb.universe.tf~1loadBalancerIPs"
        value: NICO_DNS_INSTANCE_0_IP
    target:
      version: v1
      kind: Service
      labelSelector: app.kubernetes.io/part-of=nico-dns-instance-0
  - patch: |-
      - op: add
        path: "/metadata/annotations/metallb.universe.tf~1loadBalancerIPs"
        value: NICO_DNS_INSTANCE_1_IP
    target:
      version: v1
      kind: Service
      labelSelector: app.kubernetes.io/part-of=nico-dns-instance-1
  - patch: |-
      - op: add
        path: "/metadata/annotations/metallb.universe.tf~1loadBalancerIPs"
        value: NICO_PXE_IP
    target:
      version: v1
      kind: Service
      labelSelector: app.kubernetes.io/part-of=nico-pxe
  - patch: |-
      - op: add
        path: "/metadata/annotations/metallb.universe.tf~1loadBalancerIPs"
        value: NICO_API_EXTERNAL_IP
    target:
      version: v1
      kind: Service
      name: nico-api-external
  - patch: |-
      - op: add
        path: "/metadata/annotations/metallb.universe.tf~1loadBalancerIPs"
        value: NICO_SSH_CONSOLE_EXTERNAL_IP
    target:
      version: v1
      kind: Service
      name: nico-ssh-console-rs-external
  - patch: |-
      apiVersion: v1
      kind: Service
      metadata:
        name: nico-unbound
      spec:
        type: LoadBalancer
        loadBalancerIP: NICO_UNBOUND_EXTERNAL_IP
    target:
      version: v1
      kind: Service
      name: nico-unbound
  - patch: |-
      - op: add
        path: "/spec/dnsNames/0"
        value: "api-ENVIORNMENT_NAME.SITE_DOMAIN_NAME"
    target:
      group: cert-manager.io
      version: v1
      kind: Certificate
      name: nico-api-certificate
  - patch: |-
      - op: add
        path: "/metadata/annotations/metallb.universe.tf~1loadBalancerIPs"
        value: NICO_NTP_SERVERS_IP_0
    target:
      kind: Service
      labelSelector: app.kubernetes.io/part-of=nico-ntp-instance-0
      version: v1
  - patch: |-
      - op: add
        path: "/metadata/annotations/metallb.universe.tf~1loadBalancerIPs"
        value: NICO_NTP_SERVERS_IP_1
    target:
      kind: Service
      labelSelector: app.kubernetes.io/part-of=nico-ntp-instance-1
      version: v1
  - patch: |-
      - op: add
        path: "/metadata/annotations/metallb.universe.tf~1loadBalancerIPs"
        value: NICO_NTP_SERVERS_IP_2
    target:
      kind: Service
      labelSelector: app.kubernetes.io/part-of=nico-ntp-instance-2
      version: v1

configMapGenerator:
  - name: nico-dhcp-config
    files:
      - files/kea_config.json
  - name: nico-api-site-config-files
    behavior: merge
    files:
      - files/nico-api/nico-api-site-config.toml
      - files/nico-api/admin_root_cert_pem
  - name: nico-dns-config
    literals:
      - "NICO_API=https://nico-api.nico-system.svc.cluster.local:1079"
  - name: nico-pxe-env-config
    literals:
      - "NICO_STATIC_PXE_URL=http://nico-static-pxe.nico"
  - name: unbound-local-config
    behavior: merge
    files:
      # Set up DNS records
      - local_data.conf=files/unbound/local_data.conf
      # Set up forwarders
      - forwarders.conf=files/unbound/forwarders.conf
  - name: nico-web-api-hostname
    literals:
      - "hostname=api-ENVIORNMENT_NAME.SITE_DOMAIN_NAME"
