apiVersion: apps/v1
kind: Deployment
metadata:
  name: carbide-bmc-proxy
  namespace: {{ include "carbide-bmc-proxy.namespace" . }}
  labels:
    {{- include "carbide-bmc-proxy.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.annotations | nindent 4 }}
spec:
  replicas: {{ .Values.replicas }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      {{- include "carbide-bmc-proxy.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "carbide-bmc-proxy.labels" . | nindent 8 }}
      annotations:
        kubectl.kubernetes.io/default-container: carbide-bmc-proxy
    spec:
      automountServiceAccountToken: {{ .Values.automountServiceAccountToken }}
      serviceAccountName: {{ .Values.serviceAccountName }}
      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: carbide-bmc-proxy
          image: "{{ include "carbide-bmc-proxy.image" . }}"
          imagePullPolicy: {{ .Values.global.image.pullPolicy }}
          command:
            {{- toYaml .Values.command | nindent 12 }}
          env:
            - name: VAULT_ROLE_ID
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.envFrom.vaultApproleTokens.secretName }}
                  key: VAULT_ROLE_ID
                  optional: true
            - name: VAULT_SECRET_ID
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.envFrom.vaultApproleTokens.secretName }}
                  key: VAULT_SECRET_ID
                  optional: true
            - name: VAULT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.envFrom.vaultToken.secretName }}
                  key: token
            - name: VAULT_ADDR
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.envFrom.vaultClusterInfo.configMapName }}
                  key: VAULT_SERVICE
            - name: VAULT_KV_MOUNT_LOCATION
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.envFrom.vaultClusterInfo.configMapName }}
                  key: FORGE_VAULT_MOUNT
            - name: VAULT_PKI_MOUNT_LOCATION
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.envFrom.vaultClusterInfo.configMapName }}
                  key: FORGE_VAULT_PKI_MOUNT
            - name: VAULT_PKI_ROLE_NAME
              value: {{ .Values.env.VAULT_PKI_ROLE_NAME | quote }}
            - name: DATASTORE_USER
              valueFrom:
                secretKeyRef:
                  key: username
                  name: {{ .Values.envFrom.databaseCredentials.secretName }}
            - name: DATASTORE_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: {{ .Values.envFrom.databaseCredentials.secretName }}
            - name: DATASTORE_HOST
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.envFrom.databaseConfig.configMapName }}
                  key: DB_HOST
            - name: DATASTORE_PORT
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.envFrom.databaseConfig.configMapName }}
                  key: DB_PORT
            - name: DATASTORE_NAME
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.envFrom.databaseConfig.configMapName }}
                  key: DB_NAME
            - name: CARBIDE_BMC_PROXY_DATABASE_URL
              value: "postgres://$(DATASTORE_USER):$(DATASTORE_PASSWORD)@$(DATASTORE_HOST):$(DATASTORE_PORT)/$(DATASTORE_NAME)"
            - name: RUST_BACKTRACE
              value: {{ .Values.env.RUST_BACKTRACE | quote }}
            - name: RUST_LIB_BACKTRACE
              value: {{ .Values.env.RUST_LIB_BACKTRACE | quote }}
            {{- with .Values.extraEnv }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          ports:
            - name: proxy
              containerPort: {{ .Values.service.proxy.port }}
            - name: metrics
              containerPort: {{ .Values.service.metrics.port }}
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          volumeMounts:
            - name: carbide-bmc-proxy-config-files
              mountPath: /etc/forge/carbide-bmc-proxy
            - name: spiffe
              mountPath: "/var/run/secrets/spiffe.io"
              readOnly: true
            - name: forge-roots
              mountPath: "/var/run/secrets/forge-roots"
              readOnly: true
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: carbide-bmc-proxy-config-files
          configMap:
            name: carbide-bmc-proxy-config-files
        - name: spiffe
          secret:
            secretName: carbide-bmc-proxy-certificate
        - name: forge-roots
          secret:
            secretName: forge-roots
