apiVersion: v1
kind: ServiceAccount
metadata:
  name: carbide-bmc-proxy
  namespace: {{ include "carbide-bmc-proxy.namespace" . }}
  labels:
    {{- include "carbide-bmc-proxy.labels" . | nindent 4 }}
