#
# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nico-dhcp
  namespace: default
  annotations:
    configmap.reloader.stakater.com/reload: "nico-dhcp-config"
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app.kubernetes.io/name: nico-dhcp
  template:
    spec:
      containers:
        - name: nico-dhcp
          image: yourdockerregistry.com/path/to/nico-core:latest
          command: ['sh', '-c', 'mkdir -vp /var/run/kea /var/lib/kea && /sbin/kea-dhcp4 -c /tmp/kea_config.json']
          env:
            - name: FORGE_ROOT_CAFILE_PATH
              value: /var/run/secrets/spiffe.io/ca.crt
            - name: FORGE_CLIENT_CERT_PATH
              value: /var/run/secrets/spiffe.io/tls.crt
            - name: FORGE_CLIENT_KEY_PATH
              value: /var/run/secrets/spiffe.io/tls.key
            - name: RUST_BACKTRACE
              value: "full"
            - name: RUST_LIB_BACKTRACE # See https://doc.rust-lang.org/std/backtrace/index.html#environment-variables
              value: "0"
          imagePullPolicy: IfNotPresent
          securityContext:
            capabilities:
              add:
                - SYS_PTRACE
          ports:
            - name: udp
              containerPort: 67
            - name: metrics
              containerPort: 1089
          volumeMounts:
            - name: spiffe
              mountPath: /var/run/secrets/spiffe.io
              readOnly: true
            - name: config
              mountPath: /tmp
      volumes:
        - name: spiffe
          secret:
            secretName: nico-dhcp-certificate
        - name: config
          configMap:
            defaultMode: 420
            name: nico-dhcp-config
