apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "nico-pxe.name" . }}-env-config
  namespace: {{ include "nico-pxe.namespace" . }}
  labels:
    {{- include "nico-pxe.labels" . | nindent 4 }}
data:
  NICO_API_HOST: {{ printf "%s.%s.svc.cluster.local" .Values.apiServiceName (include "nico-pxe.namespace" .) | quote }}
  NICO_API_PORT: {{ .Values.config.nicoApiPort | default "1079" | quote }}
  {{- range $key, $value := .Values.config.extraEnvData }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
