apiVersion: v1
kind: Service
metadata:
  name: {{ include "nico-pxe.name" . }}
  namespace: {{ include "nico-pxe.namespace" . }}
  labels:
    {{- include "nico-pxe.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "nico-pxe.selectorLabels" . | nindent 4 }}
  ports:
    - port: {{ .Values.service.port }}
      name: http
      protocol: TCP
