ALTER TABLE IF EXISTS instances 
    ADD COLUMN labels JSONB NOT NULL DEFAULT ('{}'),
    ADD COLUMN name VARCHAR(64) NOT NULL DEFAULT (''),
    ADD COLUMN description VARCHAR(64) NOT NULL DEFAULT (''),
    ADD COLUMN metadata_version VARCHAR(64) NOT NULL DEFAULT ('V1-T1666644937952268');