# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

name: Notify Slack on Pull Request

on:
  pull_request_target:
    types: [opened]

jobs:
  notify-slack:
    runs-on: ubuntu-latest
    steps:
      - name: Send Slack Notification
        uses: slackapi/slack-github-action@v2.1.1 # Use a pre-existing action
        env:
          MESSAGE: ":github: *nico-rest* - ${{ github.event.pull_request.title }}\nOpened by: *${{ github.event.pull_request.user.login }}*\nURL: ${{ github.event.pull_request.html_url }}"
        with:
          webhook: ${{ secrets.SLACK_WEBHOOK_URL }}
          webhook-type: incoming-webhook
          payload: |
            text: ${{ toJSON(env.MESSAGE) }}
