{{- if .Values.externalService.enabled }}
{{- $replicas := int .Values.replicas }}
{{- range $i := until $replicas }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "nico-dns.name" . }}-external-udp-{{ $i }}
  namespace: {{ include "nico-dns.namespace" $ }}
  labels:
    app.kubernetes.io/part-of: {{ include "nico-dns.name" . }}-instance-{{ $i }}
  annotations:
    metallb.universe.tf/allow-shared-ip: "{{ include "nico-dns.name" . }}-instance-{{ $i }}"
    {{- $annotations := "" }}
    {{- if and $.Values.externalService.perPodAnnotations (gt (len $.Values.externalService.perPodAnnotations) $i) }}
    {{- $annotations = index $.Values.externalService.perPodAnnotations $i }}
    {{- end }}
    {{- with $annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  type: {{ $.Values.externalService.type | default "LoadBalancer" }}
  selector:
    app.kubernetes.io/name: {{ include "nico-dns.name" . }}
    statefulset.kubernetes.io/pod-name: {{ include "nico-dns.name" . }}-{{ $i }}
  ports:
    - port: 53
      targetPort: 53
      name: udp
      protocol: UDP
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "nico-dns.name" . }}-external-tcp-{{ $i }}
  namespace: {{ include "nico-dns.namespace" $ }}
  labels:
    app.kubernetes.io/part-of: {{ include "nico-dns.name" . }}-instance-{{ $i }}
  annotations:
    metallb.universe.tf/allow-shared-ip: "{{ include "nico-dns.name" . }}-instance-{{ $i }}"
    {{- $annotations := "" }}
    {{- if and $.Values.externalService.perPodAnnotations (gt (len $.Values.externalService.perPodAnnotations) $i) }}
    {{- $annotations = index $.Values.externalService.perPodAnnotations $i }}
    {{- end }}
    {{- with $annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  type: {{ $.Values.externalService.type | default "LoadBalancer" }}
  selector:
    app.kubernetes.io/name: {{ include "nico-dns.name" . }}
    statefulset.kubernetes.io/pod-name: {{ include "nico-dns.name" . }}-{{ $i }}
  ports:
    - port: 53
      targetPort: 53
      name: tcp
      protocol: TCP
{{- end }}
{{- end }}
