#
# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nico-dns
  namespace: default
  annotations:
    configmap.reloader.stakater.com/reload: "nico-dns, nico-dns-config"
spec:
  serviceName: nico-dns
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: nico-dns
  template:
    metadata:
    spec:
      containers:
        - name: nico-dns
          image: yourdockerregistry.com/path/to/nico-core:latest
          command: ["/bin/sh", "-c", "/opt/carbide/carbide-dns run --carbide-url=\"${NICO_API}\" --listen=\"[::]:53\""]  # yamllint disable-line
          env:
            - name: NICO_API
              valueFrom:
                configMapKeyRef:
                  name: nico-dns
                  key: NICO_API
            - name: FORGE_ROOT_CA_PATH
              value: "/run/secrets/spiffe.io/ca.crt"
            - name: RUST_BACKTRACE
              value: "full"
            - name: RUST_LIB_BACKTRACE # See https://doc.rust-lang.org/std/backtrace/index.html#environment-variables
              value: "0"
          imagePullPolicy: IfNotPresent
          securityContext:
            capabilities:
              add:
                - SYS_PTRACE
          ports:
            - name: udp
              containerPort: 53
            - name: tcp
              containerPort: 53
          volumeMounts:
            - name: spiffe
              mountPath: /var/run/secrets/spiffe.io
              readOnly: true
      volumes:
        - name: spiffe
          secret:
            secretName: nico-dns-certificate
