# syntax=docker/dockerfile:1.4

#
# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
FROM registry.minikube/runtime-container:latest as carbide

WORKDIR ./carbide
RUN mkdir -p /opt/carbide/scout-firmware-scripts

COPY .skaffold/target/carbide-api/debug/carbide-api /opt/carbide/
COPY .skaffold/target/nico-admin-cli/debug/nico-admin-cli /opt/carbide/
RUN ln -s /opt/carbide/nico-admin-cli /opt/carbide/carbide-admin-cli && \
    ln -s /opt/carbide/nico-admin-cli /opt/carbide/forge-admin-cli
COPY crates/api/casbin-policy.csv /opt/carbide/
COPY pxe/scout-firmware-scripts/ /opt/carbide/scout-firmware-scripts/
ENV CASBIN_POLICY_FILE=/opt/carbide/casbin-policy.csv
