#
# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nico-unbound
  annotations:
    configmap.reloader.stakater.com/reload: "unbound-local-config, unbound-envvars"
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: unbound
      app.kubernetes.io/instance: nico-unbound
  template:
    metadata:
      annotations:
        prometheus.io/port: "9167"
        prometheus.io/scrape: "1"
      labels:
        app.kubernetes.io/instance: nico-unbound
        app.kubernetes.io/name: unbound
    spec:
      imagePullSecrets:
        - name: imagepullsecret
      containers:
        - name: unbound
          image: yourdockerregistry.com/path/to/unbound:3b089e6
          imagePullPolicy: IfNotPresent
          ports:
            - name: dns-udp
              containerPort: 53
              protocol: UDP
            - name: dns-tcp
              containerPort: 53
              protocol: TCP
          livenessProbe:
            tcpSocket:
              port: 53
          readinessProbe:
            tcpSocket:
              port: 53
          volumeMounts:
            - name: local-config
              mountPath: /etc/unbound/local.conf.d
            - name: control-keys
              mountPath: /etc/unbound/keys
          envFrom:
            - configMapRef:
                name: unbound-envvars
        - name: unbound-metrics
          image: yourdockerregistry.com/path/to/unbound_exporter:7561033
          imagePullPolicy: IfNotPresent
          env:
            - name: KEYS_DIR
              value: /etc/unbound/keys
          volumeMounts:
            - name: control-keys
              mountPath: /etc/unbound/keys
              readOnly: true
          ports:
            - name: metrics
              containerPort: 9167
              protocol: TCP
      volumes:
        - name: local-config
          configMap:
            name: unbound-local-config
        - name: control-keys
          emptyDir: {}
