#
# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml

configMapGenerator:
  - name: unbound-envvars
    envs:
      - unbound.env
  - name: unbound-local-config
    files:
      - access_control.conf=local.conf.d/access_control.conf
      - extended_statistics.conf=local.conf.d/extended_statistics.conf
      - verbosity.conf=local.conf.d/verbosity.conf
      - nico_local_unknowndomain.conf=local.conf.d/nico_local_unknowndomain.conf
      - forwarders.conf=local.conf.d/patchme.conf

labels:
  - pairs:
      app.kubernetes.io/name: unbound
      app.kubernetes.io/component: recursive-dns
    includeSelectors: true
    includeTemplates: true

commonAnnotations:
  managed-by: argocd.argoproj.io

generatorOptions:
  disableNameSuffixHash: true
