apiVersion: v1
kind: Service
metadata:
  name: {{ include "nico-api.name" . }}-profiler
  namespace: {{ include "nico-api.namespace" . }}
  labels:
    {{- include "nico-api.labels" . | nindent 4 }}
    app: {{ include "nico-api.name" . }}
    app.kubernetes.io/metrics: {{ include "nico-api.name" . }}
spec:
  selector:
    {{- include "nico-api.selectorLabels" . | nindent 4 }}
  ports:
    - port: {{ .Values.service.profiler.port }}
      name: http
      protocol: TCP
      targetPort: {{ .Values.service.profiler.port }}
