apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "nico-api.name" . }}
  namespace: {{ include "nico-api.namespace" . }}
  labels:
    {{- include "nico-api.labels" . | nindent 4 }}
automountServiceAccountToken: {{ .Values.automountServiceAccountToken }}
