apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "nico-machine-a-tron.name" . }}
  namespace: {{ include "nico-machine-a-tron.namespace" . }}
  labels:
    {{- include "nico-machine-a-tron.labels" . | nindent 4 }}
