#!/bin/bash -p
# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

HOSTNAME=$(hostname)

if [[ "$HOSTNAME" == "localhost" ]]; then
    echo "hostname cannot be 'localhost'"
    exit 1
fi

CERT_PATH=/etc/otelcol-contrib/certs/otel-cert.pem
KEY_PATH=/etc/otelcol-contrib/certs/private/otel-key.pem
MAX_INTERVAL=30
MAX_INTERVAL_REPEATED_COUNT=5

interval=1
interval_repeated_count=0
max_interval_reached=false

while [[ ! -f "$CERT_PATH" || ! -f "$KEY_PATH" ]]; do
    echo "Certs not found. Try again in ${interval}s."

    sleep $interval

    if [[ $max_interval_reached == "true" ]]; then
        : # leave max interval unchanged
    elif [[ $interval -ge $MAX_INTERVAL ]]; then
        echo "Maximum interval reached. Continue to try every ${MAX_INTERVAL}s."
        max_interval_reached=true
    elif [[ $interval_repeated_count -ge $MAX_INTERVAL_REPEATED_COUNT ]]; then
        interval=$(( (interval * 3 + 1) / 2 )) # backoff factor 1.5 rounded up
        interval=$(( interval < MAX_INTERVAL ? interval : MAX_INTERVAL ))
        interval_repeated_count=0
    else
        interval_repeated_count=$(( $interval_repeated_count + 1 ))
    fi
done

echo "Found $CERT_PATH and $KEY_PATH"
exec /usr/bin/otelcol-contrib --config=/etc/otelcol-contrib/config.yaml
