apiVersion: v1
kind: Service
metadata:
  name: {{ include "nico-dhcp.name" . }}-metrics
  namespace: {{ include "nico-dhcp.namespace" . }}
  labels:
    {{- include "nico-dhcp.labels" . | nindent 4 }}
    app: {{ include "nico-dhcp.name" . }}
    app.kubernetes.io/metrics: {{ include "nico-dhcp.name" . }}
spec:
  selector:
    {{- include "nico-dhcp.selectorLabels" . | nindent 4 }}
  ports:
    - port: {{ .Values.metrics.port }}
      name: http
      protocol: TCP
      targetPort: {{ .Values.metrics.port }}
