#
# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: nico-pxe-certificate
  namespace: default
spec:
  duration: 720h0m0s
  renewBefore: 360h0m0s
  dnsNames:
    - nico-pxe.default.svc.cluster.local
  uris:
    - spiffe://nico.local/default/sa/nico-pxe
  privateKey:
    algorithm: ECDSA
    size: 384
  issuerRef:
    kind: ClusterIssuer
    name: vault-nico-issuer
    group: cert-manager.io
  secretName: nico-pxe-certificate
