#
# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nico-ssh-console-rs
  namespace: default
  annotations:
    configmap.reloader.stakater.com/reload: "ssh-console-rs-config-files"
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: nico-ssh-console-rs
  template:
    metadata:
    spec:
      serviceAccountName: nico-ssh-console-rs
      # TODO: drop this when ssh-console-rs goes into the nico-system overlay.
      # Normally the nico-system overlay patches this in via components/imagepullsecret, but
      # ssh-console-rs isn't in the nico-system overlay yet, so we explicitly put this here.
      imagePullSecrets:
        - name: imagepullsecret
      containers:
        - name: ssh-console-rs
          image: yourdockerregistry.com/path/to/nico-core:latest
          command: ["/opt/carbide/ssh-console"]
          args: ["run", "-c", "/etc/forge/ssh-console/config.toml"]
          imagePullPolicy: IfNotPresent
          # russh uses memlock(2) for preventing sensitive data from getting
          # swapped. Allow it to mlock more than the default 64kb limit.
          securityContext:
            capabilities:
              add:
                - IPC_LOCK
          ports:
            - name: ssh
              containerPort: 22
              protocol: TCP
          readinessProbe:
            failureThreshold: 3
            tcpSocket:
              port: 22
            initialDelaySeconds: 1
            periodSeconds: 30
            successThreshold: 1
          resources: {}
          volumeMounts:
            - name: ssh-console-rs-config-files
              mountPath: /etc/forge/ssh-console
            - name: spiffe
              mountPath: "/var/run/secrets/spiffe.io"
              readOnly: true
            - name: ssh-host-key
              mountPath: /etc/ssh/ssh_host_ed25519_key
              subPath: ssh_host_ed25519_key
              readOnly: true
            - name: ssh-host-key-pub
              mountPath: /etc/ssh/ssh_host_ed25519_key.pub
              subPath: ssh_host_ed25519_key_pub
              readOnly: true
            - name: console-logs
              mountPath: /var/log/consoles
        - name: loki-log-collector
          image: ghcr.io/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector-contrib:0.81.0
          imagePullPolicy: IfNotPresent
          args: ["--config=/etc/otelcol-contrib/config.yaml"]
          volumeMounts:
            - name: otelcol-config
              mountPath: /etc/otelcol-contrib
              readOnly: true
            - name: console-logs
              mountPath: /var/log/consoles
            - name: otelcol-file-log-checkpoints
              mountPath: /var/lib/otelcol/filelog-checkpoints
      volumes:
        - name: ssh-console-rs-config-files
          configMap:
            name: ssh-console-rs-config-files
        - name: spiffe
          secret:
            secretName: nico-ssh-console-rs-certificate
        - name: ssh-host-key
          secret:
            secretName: ssh-host-key
            defaultMode: 0400
        - name: ssh-host-key-pub
          secret:
            secretName: ssh-host-key
            defaultMode: 0444
        - name: console-logs
          emptyDir: {}
        - name: otelcol-file-log-checkpoints
          emptyDir: {}
        - name: otelcol-config
          configMap:
            name: ssh-console-rs-otelcol-config
