// SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

/*
NVIDIA Infra Controller REST API

NVIDIA Infra Controller REST API allows users to create and manage resources, e.g., VPCs, Subnets, and Instances, across all connected NVIDIA Infra Controller datacenters, also referred to as Sites.

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package standard

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the ExploredBootOption type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ExploredBootOption{}

// ExploredBootOption One Redfish boot option.
type ExploredBootOption struct {
	DisplayName       string         `json:"displayName"`
	Id                string         `json:"id"`
	BootOptionEnabled NullableBool   `json:"bootOptionEnabled,omitempty"`
	UefiDevicePath    NullableString `json:"uefiDevicePath,omitempty"`
}

type _ExploredBootOption ExploredBootOption

// NewExploredBootOption instantiates a new ExploredBootOption object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewExploredBootOption(displayName string, id string) *ExploredBootOption {
	this := ExploredBootOption{}
	this.DisplayName = displayName
	this.Id = id
	return &this
}

// NewExploredBootOptionWithDefaults instantiates a new ExploredBootOption object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewExploredBootOptionWithDefaults() *ExploredBootOption {
	this := ExploredBootOption{}
	return &this
}

// GetDisplayName returns the DisplayName field value
func (o *ExploredBootOption) GetDisplayName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.DisplayName
}

// GetDisplayNameOk returns a tuple with the DisplayName field value
// and a boolean to check if the value has been set.
func (o *ExploredBootOption) GetDisplayNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DisplayName, true
}

// SetDisplayName sets field value
func (o *ExploredBootOption) SetDisplayName(v string) {
	o.DisplayName = v
}

// GetId returns the Id field value
func (o *ExploredBootOption) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *ExploredBootOption) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *ExploredBootOption) SetId(v string) {
	o.Id = v
}

// GetBootOptionEnabled returns the BootOptionEnabled field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ExploredBootOption) GetBootOptionEnabled() bool {
	if o == nil || IsNil(o.BootOptionEnabled.Get()) {
		var ret bool
		return ret
	}
	return *o.BootOptionEnabled.Get()
}

// GetBootOptionEnabledOk returns a tuple with the BootOptionEnabled field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ExploredBootOption) GetBootOptionEnabledOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return o.BootOptionEnabled.Get(), o.BootOptionEnabled.IsSet()
}

// HasBootOptionEnabled returns a boolean if a field has been set.
func (o *ExploredBootOption) HasBootOptionEnabled() bool {
	if o != nil && o.BootOptionEnabled.IsSet() {
		return true
	}

	return false
}

// SetBootOptionEnabled gets a reference to the given NullableBool and assigns it to the BootOptionEnabled field.
func (o *ExploredBootOption) SetBootOptionEnabled(v bool) {
	o.BootOptionEnabled.Set(&v)
}

// SetBootOptionEnabledNil sets the value for BootOptionEnabled to be an explicit nil
func (o *ExploredBootOption) SetBootOptionEnabledNil() {
	o.BootOptionEnabled.Set(nil)
}

// UnsetBootOptionEnabled ensures that no value is present for BootOptionEnabled, not even an explicit nil
func (o *ExploredBootOption) UnsetBootOptionEnabled() {
	o.BootOptionEnabled.Unset()
}

// GetUefiDevicePath returns the UefiDevicePath field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ExploredBootOption) GetUefiDevicePath() string {
	if o == nil || IsNil(o.UefiDevicePath.Get()) {
		var ret string
		return ret
	}
	return *o.UefiDevicePath.Get()
}

// GetUefiDevicePathOk returns a tuple with the UefiDevicePath field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ExploredBootOption) GetUefiDevicePathOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.UefiDevicePath.Get(), o.UefiDevicePath.IsSet()
}

// HasUefiDevicePath returns a boolean if a field has been set.
func (o *ExploredBootOption) HasUefiDevicePath() bool {
	if o != nil && o.UefiDevicePath.IsSet() {
		return true
	}

	return false
}

// SetUefiDevicePath gets a reference to the given NullableString and assigns it to the UefiDevicePath field.
func (o *ExploredBootOption) SetUefiDevicePath(v string) {
	o.UefiDevicePath.Set(&v)
}

// SetUefiDevicePathNil sets the value for UefiDevicePath to be an explicit nil
func (o *ExploredBootOption) SetUefiDevicePathNil() {
	o.UefiDevicePath.Set(nil)
}

// UnsetUefiDevicePath ensures that no value is present for UefiDevicePath, not even an explicit nil
func (o *ExploredBootOption) UnsetUefiDevicePath() {
	o.UefiDevicePath.Unset()
}

func (o ExploredBootOption) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ExploredBootOption) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["displayName"] = o.DisplayName
	toSerialize["id"] = o.Id
	if o.BootOptionEnabled.IsSet() {
		toSerialize["bootOptionEnabled"] = o.BootOptionEnabled.Get()
	}
	if o.UefiDevicePath.IsSet() {
		toSerialize["uefiDevicePath"] = o.UefiDevicePath.Get()
	}
	return toSerialize, nil
}

func (o *ExploredBootOption) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"displayName",
		"id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if value, exists := allProperties[requiredProperty]; !exists || value == nil {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varExploredBootOption := _ExploredBootOption{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	err = decoder.Decode(&varExploredBootOption)

	if err != nil {
		return err
	}

	*o = ExploredBootOption(varExploredBootOption)

	return err
}

type NullableExploredBootOption struct {
	value *ExploredBootOption
	isSet bool
}

func (v NullableExploredBootOption) Get() *ExploredBootOption {
	return v.value
}

func (v *NullableExploredBootOption) Set(val *ExploredBootOption) {
	v.value = val
	v.isSet = true
}

func (v NullableExploredBootOption) IsSet() bool {
	return v.isSet
}

func (v *NullableExploredBootOption) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableExploredBootOption(val *ExploredBootOption) *NullableExploredBootOption {
	return &NullableExploredBootOption{value: val, isSet: true}
}

func (v NullableExploredBootOption) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableExploredBootOption) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
