// SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

/*
NVIDIA Infra Controller REST API

NVIDIA Infra Controller REST API allows users to create and manage resources e.g. VPC, Subnets, Instances across all connected NVIDIA Infra Controller datacenters, also referred to as Sites.

API version: 1.6.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package standard

import (
	"encoding/json"
	"fmt"
)

// AllocationStatus Status values for Allocation objects
type AllocationStatus string

// List of AllocationStatus
const (
	ALLOCATIONSTATUS_PENDING    AllocationStatus = "Pending"
	ALLOCATIONSTATUS_REGISTERED AllocationStatus = "Registered"
	ALLOCATIONSTATUS_DELETING   AllocationStatus = "Deleting"
	ALLOCATIONSTATUS_ERROR      AllocationStatus = "Error"
)

// All allowed values of AllocationStatus enum
var AllowedAllocationStatusEnumValues = []AllocationStatus{
	"Pending",
	"Registered",
	"Deleting",
	"Error",
}

func (v *AllocationStatus) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := AllocationStatus(value)
	for _, existing := range AllowedAllocationStatusEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid AllocationStatus", value)
}

// NewAllocationStatusFromValue returns a pointer to a valid AllocationStatus
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewAllocationStatusFromValue(v string) (*AllocationStatus, error) {
	ev := AllocationStatus(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for AllocationStatus: valid values are %v", v, AllowedAllocationStatusEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v AllocationStatus) IsValid() bool {
	for _, existing := range AllowedAllocationStatusEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to AllocationStatus value
func (v AllocationStatus) Ptr() *AllocationStatus {
	return &v
}

type NullableAllocationStatus struct {
	value *AllocationStatus
	isSet bool
}

func (v NullableAllocationStatus) Get() *AllocationStatus {
	return v.value
}

func (v *NullableAllocationStatus) Set(val *AllocationStatus) {
	v.value = val
	v.isSet = true
}

func (v NullableAllocationStatus) IsSet() bool {
	return v.isSet
}

func (v *NullableAllocationStatus) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAllocationStatus(val *AllocationStatus) *NullableAllocationStatus {
	return &NullableAllocationStatus{value: val, isSet: true}
}

func (v NullableAllocationStatus) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAllocationStatus) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
