// SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

/*
NVIDIA Infra Controller REST API

NVIDIA Infra Controller REST API allows users to create and manage resources, e.g., VPCs, Subnets, and Instances, across all connected NVIDIA Infra Controller datacenters, also referred to as Sites.

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package standard

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the UpdateRuleRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateRuleRequest{}

// UpdateRuleRequest Request body for patching an Operation Rule. All mutable fields are optional; unset fields are left unchanged. At least one of `name`, `description`, `ruleDefinition` must be provided.
type UpdateRuleRequest struct {
	// ID of the Site that owns the rule.
	SiteId string `json:"siteId"`
	// New rule name. Must be non-empty when provided.
	Name *string `json:"name,omitempty"`
	// New free-form description.
	Description    *string         `json:"description,omitempty"`
	RuleDefinition *RuleDefinition `json:"ruleDefinition,omitempty"`
}

type _UpdateRuleRequest UpdateRuleRequest

// NewUpdateRuleRequest instantiates a new UpdateRuleRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateRuleRequest(siteId string) *UpdateRuleRequest {
	this := UpdateRuleRequest{}
	this.SiteId = siteId
	return &this
}

// NewUpdateRuleRequestWithDefaults instantiates a new UpdateRuleRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateRuleRequestWithDefaults() *UpdateRuleRequest {
	this := UpdateRuleRequest{}
	return &this
}

// GetSiteId returns the SiteId field value
func (o *UpdateRuleRequest) GetSiteId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SiteId
}

// GetSiteIdOk returns a tuple with the SiteId field value
// and a boolean to check if the value has been set.
func (o *UpdateRuleRequest) GetSiteIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SiteId, true
}

// SetSiteId sets field value
func (o *UpdateRuleRequest) SetSiteId(v string) {
	o.SiteId = v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *UpdateRuleRequest) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateRuleRequest) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *UpdateRuleRequest) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *UpdateRuleRequest) SetName(v string) {
	o.Name = &v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *UpdateRuleRequest) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateRuleRequest) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *UpdateRuleRequest) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *UpdateRuleRequest) SetDescription(v string) {
	o.Description = &v
}

// GetRuleDefinition returns the RuleDefinition field value if set, zero value otherwise.
func (o *UpdateRuleRequest) GetRuleDefinition() RuleDefinition {
	if o == nil || IsNil(o.RuleDefinition) {
		var ret RuleDefinition
		return ret
	}
	return *o.RuleDefinition
}

// GetRuleDefinitionOk returns a tuple with the RuleDefinition field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateRuleRequest) GetRuleDefinitionOk() (*RuleDefinition, bool) {
	if o == nil || IsNil(o.RuleDefinition) {
		return nil, false
	}
	return o.RuleDefinition, true
}

// HasRuleDefinition returns a boolean if a field has been set.
func (o *UpdateRuleRequest) HasRuleDefinition() bool {
	if o != nil && !IsNil(o.RuleDefinition) {
		return true
	}

	return false
}

// SetRuleDefinition gets a reference to the given RuleDefinition and assigns it to the RuleDefinition field.
func (o *UpdateRuleRequest) SetRuleDefinition(v RuleDefinition) {
	o.RuleDefinition = &v
}

func (o UpdateRuleRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateRuleRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["siteId"] = o.SiteId
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !IsNil(o.RuleDefinition) {
		toSerialize["ruleDefinition"] = o.RuleDefinition
	}
	return toSerialize, nil
}

func (o *UpdateRuleRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"siteId",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if value, exists := allProperties[requiredProperty]; !exists || value == nil {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUpdateRuleRequest := _UpdateRuleRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varUpdateRuleRequest)

	if err != nil {
		return err
	}

	*o = UpdateRuleRequest(varUpdateRuleRequest)

	return err
}

type NullableUpdateRuleRequest struct {
	value *UpdateRuleRequest
	isSet bool
}

func (v NullableUpdateRuleRequest) Get() *UpdateRuleRequest {
	return v.value
}

func (v *NullableUpdateRuleRequest) Set(val *UpdateRuleRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateRuleRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateRuleRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateRuleRequest(val *UpdateRuleRequest) *NullableUpdateRuleRequest {
	return &NullableUpdateRuleRequest{value: val, isSet: true}
}

func (v NullableUpdateRuleRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateRuleRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
