// SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

/*
NVIDIA Infra Controller REST API

NVIDIA Infra Controller REST API allows users to create and manage resources, e.g., VPCs, Subnets, and Instances, across all connected NVIDIA Infra Controller datacenters, also referred to as Sites.

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package standard

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the ExploredChassis type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ExploredChassis{}

// ExploredChassis Redfish Chassis reported during exploration.
type ExploredChassis struct {
	Id              string                   `json:"id"`
	NetworkAdapters []ExploredNetworkAdapter `json:"networkAdapters,omitempty"`
	Manufacturer    NullableString           `json:"manufacturer,omitempty"`
	Model           NullableString           `json:"model,omitempty"`
	PartNumber      NullableString           `json:"partNumber,omitempty"`
	SerialNumber    NullableString           `json:"serialNumber,omitempty"`
}

type _ExploredChassis ExploredChassis

// NewExploredChassis instantiates a new ExploredChassis object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewExploredChassis(id string) *ExploredChassis {
	this := ExploredChassis{}
	this.Id = id
	return &this
}

// NewExploredChassisWithDefaults instantiates a new ExploredChassis object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewExploredChassisWithDefaults() *ExploredChassis {
	this := ExploredChassis{}
	return &this
}

// GetId returns the Id field value
func (o *ExploredChassis) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *ExploredChassis) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *ExploredChassis) SetId(v string) {
	o.Id = v
}

// GetNetworkAdapters returns the NetworkAdapters field value if set, zero value otherwise.
func (o *ExploredChassis) GetNetworkAdapters() []ExploredNetworkAdapter {
	if o == nil || IsNil(o.NetworkAdapters) {
		var ret []ExploredNetworkAdapter
		return ret
	}
	return o.NetworkAdapters
}

// GetNetworkAdaptersOk returns a tuple with the NetworkAdapters field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ExploredChassis) GetNetworkAdaptersOk() ([]ExploredNetworkAdapter, bool) {
	if o == nil || IsNil(o.NetworkAdapters) {
		return nil, false
	}
	return o.NetworkAdapters, true
}

// HasNetworkAdapters returns a boolean if a field has been set.
func (o *ExploredChassis) HasNetworkAdapters() bool {
	if o != nil && !IsNil(o.NetworkAdapters) {
		return true
	}

	return false
}

// SetNetworkAdapters gets a reference to the given []ExploredNetworkAdapter and assigns it to the NetworkAdapters field.
func (o *ExploredChassis) SetNetworkAdapters(v []ExploredNetworkAdapter) {
	o.NetworkAdapters = v
}

// GetManufacturer returns the Manufacturer field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ExploredChassis) GetManufacturer() string {
	if o == nil || IsNil(o.Manufacturer.Get()) {
		var ret string
		return ret
	}
	return *o.Manufacturer.Get()
}

// GetManufacturerOk returns a tuple with the Manufacturer field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ExploredChassis) GetManufacturerOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Manufacturer.Get(), o.Manufacturer.IsSet()
}

// HasManufacturer returns a boolean if a field has been set.
func (o *ExploredChassis) HasManufacturer() bool {
	if o != nil && o.Manufacturer.IsSet() {
		return true
	}

	return false
}

// SetManufacturer gets a reference to the given NullableString and assigns it to the Manufacturer field.
func (o *ExploredChassis) SetManufacturer(v string) {
	o.Manufacturer.Set(&v)
}

// SetManufacturerNil sets the value for Manufacturer to be an explicit nil
func (o *ExploredChassis) SetManufacturerNil() {
	o.Manufacturer.Set(nil)
}

// UnsetManufacturer ensures that no value is present for Manufacturer, not even an explicit nil
func (o *ExploredChassis) UnsetManufacturer() {
	o.Manufacturer.Unset()
}

// GetModel returns the Model field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ExploredChassis) GetModel() string {
	if o == nil || IsNil(o.Model.Get()) {
		var ret string
		return ret
	}
	return *o.Model.Get()
}

// GetModelOk returns a tuple with the Model field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ExploredChassis) GetModelOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Model.Get(), o.Model.IsSet()
}

// HasModel returns a boolean if a field has been set.
func (o *ExploredChassis) HasModel() bool {
	if o != nil && o.Model.IsSet() {
		return true
	}

	return false
}

// SetModel gets a reference to the given NullableString and assigns it to the Model field.
func (o *ExploredChassis) SetModel(v string) {
	o.Model.Set(&v)
}

// SetModelNil sets the value for Model to be an explicit nil
func (o *ExploredChassis) SetModelNil() {
	o.Model.Set(nil)
}

// UnsetModel ensures that no value is present for Model, not even an explicit nil
func (o *ExploredChassis) UnsetModel() {
	o.Model.Unset()
}

// GetPartNumber returns the PartNumber field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ExploredChassis) GetPartNumber() string {
	if o == nil || IsNil(o.PartNumber.Get()) {
		var ret string
		return ret
	}
	return *o.PartNumber.Get()
}

// GetPartNumberOk returns a tuple with the PartNumber field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ExploredChassis) GetPartNumberOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.PartNumber.Get(), o.PartNumber.IsSet()
}

// HasPartNumber returns a boolean if a field has been set.
func (o *ExploredChassis) HasPartNumber() bool {
	if o != nil && o.PartNumber.IsSet() {
		return true
	}

	return false
}

// SetPartNumber gets a reference to the given NullableString and assigns it to the PartNumber field.
func (o *ExploredChassis) SetPartNumber(v string) {
	o.PartNumber.Set(&v)
}

// SetPartNumberNil sets the value for PartNumber to be an explicit nil
func (o *ExploredChassis) SetPartNumberNil() {
	o.PartNumber.Set(nil)
}

// UnsetPartNumber ensures that no value is present for PartNumber, not even an explicit nil
func (o *ExploredChassis) UnsetPartNumber() {
	o.PartNumber.Unset()
}

// GetSerialNumber returns the SerialNumber field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ExploredChassis) GetSerialNumber() string {
	if o == nil || IsNil(o.SerialNumber.Get()) {
		var ret string
		return ret
	}
	return *o.SerialNumber.Get()
}

// GetSerialNumberOk returns a tuple with the SerialNumber field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ExploredChassis) GetSerialNumberOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.SerialNumber.Get(), o.SerialNumber.IsSet()
}

// HasSerialNumber returns a boolean if a field has been set.
func (o *ExploredChassis) HasSerialNumber() bool {
	if o != nil && o.SerialNumber.IsSet() {
		return true
	}

	return false
}

// SetSerialNumber gets a reference to the given NullableString and assigns it to the SerialNumber field.
func (o *ExploredChassis) SetSerialNumber(v string) {
	o.SerialNumber.Set(&v)
}

// SetSerialNumberNil sets the value for SerialNumber to be an explicit nil
func (o *ExploredChassis) SetSerialNumberNil() {
	o.SerialNumber.Set(nil)
}

// UnsetSerialNumber ensures that no value is present for SerialNumber, not even an explicit nil
func (o *ExploredChassis) UnsetSerialNumber() {
	o.SerialNumber.Unset()
}

func (o ExploredChassis) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ExploredChassis) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	if !IsNil(o.NetworkAdapters) {
		toSerialize["networkAdapters"] = o.NetworkAdapters
	}
	if o.Manufacturer.IsSet() {
		toSerialize["manufacturer"] = o.Manufacturer.Get()
	}
	if o.Model.IsSet() {
		toSerialize["model"] = o.Model.Get()
	}
	if o.PartNumber.IsSet() {
		toSerialize["partNumber"] = o.PartNumber.Get()
	}
	if o.SerialNumber.IsSet() {
		toSerialize["serialNumber"] = o.SerialNumber.Get()
	}
	return toSerialize, nil
}

func (o *ExploredChassis) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if value, exists := allProperties[requiredProperty]; !exists || value == nil {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varExploredChassis := _ExploredChassis{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	err = decoder.Decode(&varExploredChassis)

	if err != nil {
		return err
	}

	*o = ExploredChassis(varExploredChassis)

	return err
}

type NullableExploredChassis struct {
	value *ExploredChassis
	isSet bool
}

func (v NullableExploredChassis) Get() *ExploredChassis {
	return v.value
}

func (v *NullableExploredChassis) Set(val *ExploredChassis) {
	v.value = val
	v.isSet = true
}

func (v NullableExploredChassis) IsSet() bool {
	return v.isSet
}

func (v *NullableExploredChassis) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableExploredChassis(val *ExploredChassis) *NullableExploredChassis {
	return &NullableExploredChassis{value: val, isSet: true}
}

func (v NullableExploredChassis) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableExploredChassis) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
