// SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

/*
NVIDIA Infra Controller REST API

NVIDIA Infra Controller REST API allows users to create and manage resources e.g. VPC, Subnets, Instances across all connected NVIDIA Infra Controller datacenters, also referred to as Sites.

API version: 1.6.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package standard

import (
	"encoding/json"
)

// checks if the SkuComponents type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SkuComponents{}

// SkuComponents Hardware components that make up a SKU
type SkuComponents struct {
	// CPU components
	Cpus []SkuCpu `json:"cpus,omitempty"`
	// GPU components
	Gpus []SkuGpu `json:"gpus,omitempty"`
	// Memory components
	Memory []SkuMemory `json:"memory,omitempty"`
	// Storage components
	Storage []SkuStorage `json:"storage,omitempty"`
	// Chassis component
	Chassis *SkuChassis `json:"chassis,omitempty"`
	// Ethernet device components
	EthernetDevices []SkuEthernetDevice `json:"ethernetDevices,omitempty"`
	// Infiniband device components
	InfinibandDevices []SkuInfinibandDevice `json:"infinibandDevices,omitempty"`
	// TPM components
	Tpm []SkuTpm `json:"tpm,omitempty"`
}

// NewSkuComponents instantiates a new SkuComponents object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSkuComponents() *SkuComponents {
	this := SkuComponents{}
	return &this
}

// NewSkuComponentsWithDefaults instantiates a new SkuComponents object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSkuComponentsWithDefaults() *SkuComponents {
	this := SkuComponents{}
	return &this
}

// GetCpus returns the Cpus field value if set, zero value otherwise.
func (o *SkuComponents) GetCpus() []SkuCpu {
	if o == nil || IsNil(o.Cpus) {
		var ret []SkuCpu
		return ret
	}
	return o.Cpus
}

// GetCpusOk returns a tuple with the Cpus field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SkuComponents) GetCpusOk() ([]SkuCpu, bool) {
	if o == nil || IsNil(o.Cpus) {
		return nil, false
	}
	return o.Cpus, true
}

// HasCpus returns a boolean if a field has been set.
func (o *SkuComponents) HasCpus() bool {
	if o != nil && !IsNil(o.Cpus) {
		return true
	}

	return false
}

// SetCpus gets a reference to the given []SkuCpu and assigns it to the Cpus field.
func (o *SkuComponents) SetCpus(v []SkuCpu) {
	o.Cpus = v
}

// GetGpus returns the Gpus field value if set, zero value otherwise.
func (o *SkuComponents) GetGpus() []SkuGpu {
	if o == nil || IsNil(o.Gpus) {
		var ret []SkuGpu
		return ret
	}
	return o.Gpus
}

// GetGpusOk returns a tuple with the Gpus field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SkuComponents) GetGpusOk() ([]SkuGpu, bool) {
	if o == nil || IsNil(o.Gpus) {
		return nil, false
	}
	return o.Gpus, true
}

// HasGpus returns a boolean if a field has been set.
func (o *SkuComponents) HasGpus() bool {
	if o != nil && !IsNil(o.Gpus) {
		return true
	}

	return false
}

// SetGpus gets a reference to the given []SkuGpu and assigns it to the Gpus field.
func (o *SkuComponents) SetGpus(v []SkuGpu) {
	o.Gpus = v
}

// GetMemory returns the Memory field value if set, zero value otherwise.
func (o *SkuComponents) GetMemory() []SkuMemory {
	if o == nil || IsNil(o.Memory) {
		var ret []SkuMemory
		return ret
	}
	return o.Memory
}

// GetMemoryOk returns a tuple with the Memory field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SkuComponents) GetMemoryOk() ([]SkuMemory, bool) {
	if o == nil || IsNil(o.Memory) {
		return nil, false
	}
	return o.Memory, true
}

// HasMemory returns a boolean if a field has been set.
func (o *SkuComponents) HasMemory() bool {
	if o != nil && !IsNil(o.Memory) {
		return true
	}

	return false
}

// SetMemory gets a reference to the given []SkuMemory and assigns it to the Memory field.
func (o *SkuComponents) SetMemory(v []SkuMemory) {
	o.Memory = v
}

// GetStorage returns the Storage field value if set, zero value otherwise.
func (o *SkuComponents) GetStorage() []SkuStorage {
	if o == nil || IsNil(o.Storage) {
		var ret []SkuStorage
		return ret
	}
	return o.Storage
}

// GetStorageOk returns a tuple with the Storage field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SkuComponents) GetStorageOk() ([]SkuStorage, bool) {
	if o == nil || IsNil(o.Storage) {
		return nil, false
	}
	return o.Storage, true
}

// HasStorage returns a boolean if a field has been set.
func (o *SkuComponents) HasStorage() bool {
	if o != nil && !IsNil(o.Storage) {
		return true
	}

	return false
}

// SetStorage gets a reference to the given []SkuStorage and assigns it to the Storage field.
func (o *SkuComponents) SetStorage(v []SkuStorage) {
	o.Storage = v
}

// GetChassis returns the Chassis field value if set, zero value otherwise.
func (o *SkuComponents) GetChassis() SkuChassis {
	if o == nil || IsNil(o.Chassis) {
		var ret SkuChassis
		return ret
	}
	return *o.Chassis
}

// GetChassisOk returns a tuple with the Chassis field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SkuComponents) GetChassisOk() (*SkuChassis, bool) {
	if o == nil || IsNil(o.Chassis) {
		return nil, false
	}
	return o.Chassis, true
}

// HasChassis returns a boolean if a field has been set.
func (o *SkuComponents) HasChassis() bool {
	if o != nil && !IsNil(o.Chassis) {
		return true
	}

	return false
}

// SetChassis gets a reference to the given SkuChassis and assigns it to the Chassis field.
func (o *SkuComponents) SetChassis(v SkuChassis) {
	o.Chassis = &v
}

// GetEthernetDevices returns the EthernetDevices field value if set, zero value otherwise.
func (o *SkuComponents) GetEthernetDevices() []SkuEthernetDevice {
	if o == nil || IsNil(o.EthernetDevices) {
		var ret []SkuEthernetDevice
		return ret
	}
	return o.EthernetDevices
}

// GetEthernetDevicesOk returns a tuple with the EthernetDevices field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SkuComponents) GetEthernetDevicesOk() ([]SkuEthernetDevice, bool) {
	if o == nil || IsNil(o.EthernetDevices) {
		return nil, false
	}
	return o.EthernetDevices, true
}

// HasEthernetDevices returns a boolean if a field has been set.
func (o *SkuComponents) HasEthernetDevices() bool {
	if o != nil && !IsNil(o.EthernetDevices) {
		return true
	}

	return false
}

// SetEthernetDevices gets a reference to the given []SkuEthernetDevice and assigns it to the EthernetDevices field.
func (o *SkuComponents) SetEthernetDevices(v []SkuEthernetDevice) {
	o.EthernetDevices = v
}

// GetInfinibandDevices returns the InfinibandDevices field value if set, zero value otherwise.
func (o *SkuComponents) GetInfinibandDevices() []SkuInfinibandDevice {
	if o == nil || IsNil(o.InfinibandDevices) {
		var ret []SkuInfinibandDevice
		return ret
	}
	return o.InfinibandDevices
}

// GetInfinibandDevicesOk returns a tuple with the InfinibandDevices field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SkuComponents) GetInfinibandDevicesOk() ([]SkuInfinibandDevice, bool) {
	if o == nil || IsNil(o.InfinibandDevices) {
		return nil, false
	}
	return o.InfinibandDevices, true
}

// HasInfinibandDevices returns a boolean if a field has been set.
func (o *SkuComponents) HasInfinibandDevices() bool {
	if o != nil && !IsNil(o.InfinibandDevices) {
		return true
	}

	return false
}

// SetInfinibandDevices gets a reference to the given []SkuInfinibandDevice and assigns it to the InfinibandDevices field.
func (o *SkuComponents) SetInfinibandDevices(v []SkuInfinibandDevice) {
	o.InfinibandDevices = v
}

// GetTpm returns the Tpm field value if set, zero value otherwise.
func (o *SkuComponents) GetTpm() []SkuTpm {
	if o == nil || IsNil(o.Tpm) {
		var ret []SkuTpm
		return ret
	}
	return o.Tpm
}

// GetTpmOk returns a tuple with the Tpm field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SkuComponents) GetTpmOk() ([]SkuTpm, bool) {
	if o == nil || IsNil(o.Tpm) {
		return nil, false
	}
	return o.Tpm, true
}

// HasTpm returns a boolean if a field has been set.
func (o *SkuComponents) HasTpm() bool {
	if o != nil && !IsNil(o.Tpm) {
		return true
	}

	return false
}

// SetTpm gets a reference to the given []SkuTpm and assigns it to the Tpm field.
func (o *SkuComponents) SetTpm(v []SkuTpm) {
	o.Tpm = v
}

func (o SkuComponents) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SkuComponents) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Cpus) {
		toSerialize["cpus"] = o.Cpus
	}
	if !IsNil(o.Gpus) {
		toSerialize["gpus"] = o.Gpus
	}
	if !IsNil(o.Memory) {
		toSerialize["memory"] = o.Memory
	}
	if !IsNil(o.Storage) {
		toSerialize["storage"] = o.Storage
	}
	if !IsNil(o.Chassis) {
		toSerialize["chassis"] = o.Chassis
	}
	if !IsNil(o.EthernetDevices) {
		toSerialize["ethernetDevices"] = o.EthernetDevices
	}
	if !IsNil(o.InfinibandDevices) {
		toSerialize["infinibandDevices"] = o.InfinibandDevices
	}
	if !IsNil(o.Tpm) {
		toSerialize["tpm"] = o.Tpm
	}
	return toSerialize, nil
}

type NullableSkuComponents struct {
	value *SkuComponents
	isSet bool
}

func (v NullableSkuComponents) Get() *SkuComponents {
	return v.value
}

func (v *NullableSkuComponents) Set(val *SkuComponents) {
	v.value = val
	v.isSet = true
}

func (v NullableSkuComponents) IsSet() bool {
	return v.isSet
}

func (v *NullableSkuComponents) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSkuComponents(val *SkuComponents) *NullableSkuComponents {
	return &NullableSkuComponents{value: val, isSet: true}
}

func (v NullableSkuComponents) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSkuComponents) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
