// SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

/*
NVIDIA Infra Controller REST API

NVIDIA Infra Controller REST API allows users to create and manage resources e.g. VPC, Subnets, Instances across all connected NVIDIA Infra Controller datacenters, also referred to as Sites.

API version: 1.6.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package standard

import (
	"encoding/json"
	"time"
)

// checks if the VpcPeering type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &VpcPeering{}

// VpcPeering VPC peering connection between two VPCs on the same site
type VpcPeering struct {
	// Unique identifier of the VPC peering
	Id *string `json:"id,omitempty"`
	// ID of the first VPC in the peering
	Vpc1Id *string `json:"vpc1Id,omitempty"`
	// ID of the second VPC in the peering
	Vpc2Id *string `json:"vpc2Id,omitempty"`
	// ID of the Site where the peering exists
	SiteId *string `json:"siteId,omitempty"`
	// Indicates if this is a multi-tenant peering (VPCs from different tenants)
	IsMultiTenant *bool `json:"isMultiTenant,omitempty"`
	// Status of the VPC peering
	Status *VpcPeeringStatus `json:"status,omitempty"`
	// Date and time when the VPC peering was created
	Created *time.Time `json:"created,omitempty"`
	// Date and time when the VPC peering was last updated
	Updated *time.Time `json:"updated,omitempty"`
}

// NewVpcPeering instantiates a new VpcPeering object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewVpcPeering() *VpcPeering {
	this := VpcPeering{}
	return &this
}

// NewVpcPeeringWithDefaults instantiates a new VpcPeering object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewVpcPeeringWithDefaults() *VpcPeering {
	this := VpcPeering{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *VpcPeering) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VpcPeering) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *VpcPeering) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *VpcPeering) SetId(v string) {
	o.Id = &v
}

// GetVpc1Id returns the Vpc1Id field value if set, zero value otherwise.
func (o *VpcPeering) GetVpc1Id() string {
	if o == nil || IsNil(o.Vpc1Id) {
		var ret string
		return ret
	}
	return *o.Vpc1Id
}

// GetVpc1IdOk returns a tuple with the Vpc1Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VpcPeering) GetVpc1IdOk() (*string, bool) {
	if o == nil || IsNil(o.Vpc1Id) {
		return nil, false
	}
	return o.Vpc1Id, true
}

// HasVpc1Id returns a boolean if a field has been set.
func (o *VpcPeering) HasVpc1Id() bool {
	if o != nil && !IsNil(o.Vpc1Id) {
		return true
	}

	return false
}

// SetVpc1Id gets a reference to the given string and assigns it to the Vpc1Id field.
func (o *VpcPeering) SetVpc1Id(v string) {
	o.Vpc1Id = &v
}

// GetVpc2Id returns the Vpc2Id field value if set, zero value otherwise.
func (o *VpcPeering) GetVpc2Id() string {
	if o == nil || IsNil(o.Vpc2Id) {
		var ret string
		return ret
	}
	return *o.Vpc2Id
}

// GetVpc2IdOk returns a tuple with the Vpc2Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VpcPeering) GetVpc2IdOk() (*string, bool) {
	if o == nil || IsNil(o.Vpc2Id) {
		return nil, false
	}
	return o.Vpc2Id, true
}

// HasVpc2Id returns a boolean if a field has been set.
func (o *VpcPeering) HasVpc2Id() bool {
	if o != nil && !IsNil(o.Vpc2Id) {
		return true
	}

	return false
}

// SetVpc2Id gets a reference to the given string and assigns it to the Vpc2Id field.
func (o *VpcPeering) SetVpc2Id(v string) {
	o.Vpc2Id = &v
}

// GetSiteId returns the SiteId field value if set, zero value otherwise.
func (o *VpcPeering) GetSiteId() string {
	if o == nil || IsNil(o.SiteId) {
		var ret string
		return ret
	}
	return *o.SiteId
}

// GetSiteIdOk returns a tuple with the SiteId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VpcPeering) GetSiteIdOk() (*string, bool) {
	if o == nil || IsNil(o.SiteId) {
		return nil, false
	}
	return o.SiteId, true
}

// HasSiteId returns a boolean if a field has been set.
func (o *VpcPeering) HasSiteId() bool {
	if o != nil && !IsNil(o.SiteId) {
		return true
	}

	return false
}

// SetSiteId gets a reference to the given string and assigns it to the SiteId field.
func (o *VpcPeering) SetSiteId(v string) {
	o.SiteId = &v
}

// GetIsMultiTenant returns the IsMultiTenant field value if set, zero value otherwise.
func (o *VpcPeering) GetIsMultiTenant() bool {
	if o == nil || IsNil(o.IsMultiTenant) {
		var ret bool
		return ret
	}
	return *o.IsMultiTenant
}

// GetIsMultiTenantOk returns a tuple with the IsMultiTenant field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VpcPeering) GetIsMultiTenantOk() (*bool, bool) {
	if o == nil || IsNil(o.IsMultiTenant) {
		return nil, false
	}
	return o.IsMultiTenant, true
}

// HasIsMultiTenant returns a boolean if a field has been set.
func (o *VpcPeering) HasIsMultiTenant() bool {
	if o != nil && !IsNil(o.IsMultiTenant) {
		return true
	}

	return false
}

// SetIsMultiTenant gets a reference to the given bool and assigns it to the IsMultiTenant field.
func (o *VpcPeering) SetIsMultiTenant(v bool) {
	o.IsMultiTenant = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *VpcPeering) GetStatus() VpcPeeringStatus {
	if o == nil || IsNil(o.Status) {
		var ret VpcPeeringStatus
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VpcPeering) GetStatusOk() (*VpcPeeringStatus, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *VpcPeering) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given VpcPeeringStatus and assigns it to the Status field.
func (o *VpcPeering) SetStatus(v VpcPeeringStatus) {
	o.Status = &v
}

// GetCreated returns the Created field value if set, zero value otherwise.
func (o *VpcPeering) GetCreated() time.Time {
	if o == nil || IsNil(o.Created) {
		var ret time.Time
		return ret
	}
	return *o.Created
}

// GetCreatedOk returns a tuple with the Created field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VpcPeering) GetCreatedOk() (*time.Time, bool) {
	if o == nil || IsNil(o.Created) {
		return nil, false
	}
	return o.Created, true
}

// HasCreated returns a boolean if a field has been set.
func (o *VpcPeering) HasCreated() bool {
	if o != nil && !IsNil(o.Created) {
		return true
	}

	return false
}

// SetCreated gets a reference to the given time.Time and assigns it to the Created field.
func (o *VpcPeering) SetCreated(v time.Time) {
	o.Created = &v
}

// GetUpdated returns the Updated field value if set, zero value otherwise.
func (o *VpcPeering) GetUpdated() time.Time {
	if o == nil || IsNil(o.Updated) {
		var ret time.Time
		return ret
	}
	return *o.Updated
}

// GetUpdatedOk returns a tuple with the Updated field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VpcPeering) GetUpdatedOk() (*time.Time, bool) {
	if o == nil || IsNil(o.Updated) {
		return nil, false
	}
	return o.Updated, true
}

// HasUpdated returns a boolean if a field has been set.
func (o *VpcPeering) HasUpdated() bool {
	if o != nil && !IsNil(o.Updated) {
		return true
	}

	return false
}

// SetUpdated gets a reference to the given time.Time and assigns it to the Updated field.
func (o *VpcPeering) SetUpdated(v time.Time) {
	o.Updated = &v
}

func (o VpcPeering) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o VpcPeering) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Vpc1Id) {
		toSerialize["vpc1Id"] = o.Vpc1Id
	}
	if !IsNil(o.Vpc2Id) {
		toSerialize["vpc2Id"] = o.Vpc2Id
	}
	if !IsNil(o.SiteId) {
		toSerialize["siteId"] = o.SiteId
	}
	if !IsNil(o.IsMultiTenant) {
		toSerialize["isMultiTenant"] = o.IsMultiTenant
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	if !IsNil(o.Created) {
		toSerialize["created"] = o.Created
	}
	if !IsNil(o.Updated) {
		toSerialize["updated"] = o.Updated
	}
	return toSerialize, nil
}

type NullableVpcPeering struct {
	value *VpcPeering
	isSet bool
}

func (v NullableVpcPeering) Get() *VpcPeering {
	return v.value
}

func (v *NullableVpcPeering) Set(val *VpcPeering) {
	v.value = val
	v.isSet = true
}

func (v NullableVpcPeering) IsSet() bool {
	return v.isSet
}

func (v *NullableVpcPeering) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableVpcPeering(val *VpcPeering) *NullableVpcPeering {
	return &NullableVpcPeering{value: val, isSet: true}
}

func (v NullableVpcPeering) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableVpcPeering) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
