// SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

/*
NVIDIA Infra Controller REST API

NVIDIA Infra Controller REST API allows users to create and manage resources e.g. VPC, Subnets, Instances across all connected NVIDIA Infra Controller datacenters, also referred to as Sites.

API version: 1.6.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package standard

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the VpcPeeringCreateRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &VpcPeeringCreateRequest{}

// VpcPeeringCreateRequest Request data to create a VPC peering between two VPCs, the ordering of VPCs is not important
type VpcPeeringCreateRequest struct {
	// ID of the first VPC in the peering
	Vpc1Id string `json:"vpc1Id"`
	// ID of the second VPC to peer with
	Vpc2Id string `json:"vpc2Id"`
	// ID of the Site where the peering exists
	SiteId string `json:"siteId"`
}

type _VpcPeeringCreateRequest VpcPeeringCreateRequest

// NewVpcPeeringCreateRequest instantiates a new VpcPeeringCreateRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewVpcPeeringCreateRequest(vpc1Id string, vpc2Id string, siteId string) *VpcPeeringCreateRequest {
	this := VpcPeeringCreateRequest{}
	this.Vpc1Id = vpc1Id
	this.Vpc2Id = vpc2Id
	this.SiteId = siteId
	return &this
}

// NewVpcPeeringCreateRequestWithDefaults instantiates a new VpcPeeringCreateRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewVpcPeeringCreateRequestWithDefaults() *VpcPeeringCreateRequest {
	this := VpcPeeringCreateRequest{}
	return &this
}

// GetVpc1Id returns the Vpc1Id field value
func (o *VpcPeeringCreateRequest) GetVpc1Id() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Vpc1Id
}

// GetVpc1IdOk returns a tuple with the Vpc1Id field value
// and a boolean to check if the value has been set.
func (o *VpcPeeringCreateRequest) GetVpc1IdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Vpc1Id, true
}

// SetVpc1Id sets field value
func (o *VpcPeeringCreateRequest) SetVpc1Id(v string) {
	o.Vpc1Id = v
}

// GetVpc2Id returns the Vpc2Id field value
func (o *VpcPeeringCreateRequest) GetVpc2Id() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Vpc2Id
}

// GetVpc2IdOk returns a tuple with the Vpc2Id field value
// and a boolean to check if the value has been set.
func (o *VpcPeeringCreateRequest) GetVpc2IdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Vpc2Id, true
}

// SetVpc2Id sets field value
func (o *VpcPeeringCreateRequest) SetVpc2Id(v string) {
	o.Vpc2Id = v
}

// GetSiteId returns the SiteId field value
func (o *VpcPeeringCreateRequest) GetSiteId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SiteId
}

// GetSiteIdOk returns a tuple with the SiteId field value
// and a boolean to check if the value has been set.
func (o *VpcPeeringCreateRequest) GetSiteIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SiteId, true
}

// SetSiteId sets field value
func (o *VpcPeeringCreateRequest) SetSiteId(v string) {
	o.SiteId = v
}

func (o VpcPeeringCreateRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o VpcPeeringCreateRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["vpc1Id"] = o.Vpc1Id
	toSerialize["vpc2Id"] = o.Vpc2Id
	toSerialize["siteId"] = o.SiteId
	return toSerialize, nil
}

func (o *VpcPeeringCreateRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"vpc1Id",
		"vpc2Id",
		"siteId",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varVpcPeeringCreateRequest := _VpcPeeringCreateRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varVpcPeeringCreateRequest)

	if err != nil {
		return err
	}

	*o = VpcPeeringCreateRequest(varVpcPeeringCreateRequest)

	return err
}

type NullableVpcPeeringCreateRequest struct {
	value *VpcPeeringCreateRequest
	isSet bool
}

func (v NullableVpcPeeringCreateRequest) Get() *VpcPeeringCreateRequest {
	return v.value
}

func (v *NullableVpcPeeringCreateRequest) Set(val *VpcPeeringCreateRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableVpcPeeringCreateRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableVpcPeeringCreateRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableVpcPeeringCreateRequest(val *VpcPeeringCreateRequest) *NullableVpcPeeringCreateRequest {
	return &NullableVpcPeeringCreateRequest{value: val, isSet: true}
}

func (v NullableVpcPeeringCreateRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableVpcPeeringCreateRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
