// SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

/*
NVIDIA Infra Controller REST API

NVIDIA Infra Controller REST API allows users to create and manage resources, e.g., VPCs, Subnets, and Instances, across all connected NVIDIA Infra Controller datacenters, also referred to as Sites.

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package standard

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the RetryPolicy type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RetryPolicy{}

// RetryPolicy Retry behavior for a step's child workflow.
type RetryPolicy struct {
	// Maximum number of attempts including the first.
	MaxAttempts int32 `json:"maxAttempts"`
	// Initial retry interval, as a Go duration string (e.g. `1s`).
	InitialInterval string `json:"initialInterval"`
	// Exponential backoff multiplier; must be `>= 1.0`.
	BackoffCoefficient float32 `json:"backoffCoefficient"`
	// Optional cap on retry interval, as a Go duration string.
	MaxInterval *string `json:"maxInterval,omitempty"`
}

type _RetryPolicy RetryPolicy

// NewRetryPolicy instantiates a new RetryPolicy object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRetryPolicy(maxAttempts int32, initialInterval string, backoffCoefficient float32) *RetryPolicy {
	this := RetryPolicy{}
	this.MaxAttempts = maxAttempts
	this.InitialInterval = initialInterval
	this.BackoffCoefficient = backoffCoefficient
	return &this
}

// NewRetryPolicyWithDefaults instantiates a new RetryPolicy object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRetryPolicyWithDefaults() *RetryPolicy {
	this := RetryPolicy{}
	return &this
}

// GetMaxAttempts returns the MaxAttempts field value
func (o *RetryPolicy) GetMaxAttempts() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.MaxAttempts
}

// GetMaxAttemptsOk returns a tuple with the MaxAttempts field value
// and a boolean to check if the value has been set.
func (o *RetryPolicy) GetMaxAttemptsOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MaxAttempts, true
}

// SetMaxAttempts sets field value
func (o *RetryPolicy) SetMaxAttempts(v int32) {
	o.MaxAttempts = v
}

// GetInitialInterval returns the InitialInterval field value
func (o *RetryPolicy) GetInitialInterval() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.InitialInterval
}

// GetInitialIntervalOk returns a tuple with the InitialInterval field value
// and a boolean to check if the value has been set.
func (o *RetryPolicy) GetInitialIntervalOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.InitialInterval, true
}

// SetInitialInterval sets field value
func (o *RetryPolicy) SetInitialInterval(v string) {
	o.InitialInterval = v
}

// GetBackoffCoefficient returns the BackoffCoefficient field value
func (o *RetryPolicy) GetBackoffCoefficient() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.BackoffCoefficient
}

// GetBackoffCoefficientOk returns a tuple with the BackoffCoefficient field value
// and a boolean to check if the value has been set.
func (o *RetryPolicy) GetBackoffCoefficientOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.BackoffCoefficient, true
}

// SetBackoffCoefficient sets field value
func (o *RetryPolicy) SetBackoffCoefficient(v float32) {
	o.BackoffCoefficient = v
}

// GetMaxInterval returns the MaxInterval field value if set, zero value otherwise.
func (o *RetryPolicy) GetMaxInterval() string {
	if o == nil || IsNil(o.MaxInterval) {
		var ret string
		return ret
	}
	return *o.MaxInterval
}

// GetMaxIntervalOk returns a tuple with the MaxInterval field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RetryPolicy) GetMaxIntervalOk() (*string, bool) {
	if o == nil || IsNil(o.MaxInterval) {
		return nil, false
	}
	return o.MaxInterval, true
}

// HasMaxInterval returns a boolean if a field has been set.
func (o *RetryPolicy) HasMaxInterval() bool {
	if o != nil && !IsNil(o.MaxInterval) {
		return true
	}

	return false
}

// SetMaxInterval gets a reference to the given string and assigns it to the MaxInterval field.
func (o *RetryPolicy) SetMaxInterval(v string) {
	o.MaxInterval = &v
}

func (o RetryPolicy) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RetryPolicy) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["maxAttempts"] = o.MaxAttempts
	toSerialize["initialInterval"] = o.InitialInterval
	toSerialize["backoffCoefficient"] = o.BackoffCoefficient
	if !IsNil(o.MaxInterval) {
		toSerialize["maxInterval"] = o.MaxInterval
	}
	return toSerialize, nil
}

func (o *RetryPolicy) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"maxAttempts",
		"initialInterval",
		"backoffCoefficient",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if value, exists := allProperties[requiredProperty]; !exists || value == nil {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varRetryPolicy := _RetryPolicy{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varRetryPolicy)

	if err != nil {
		return err
	}

	*o = RetryPolicy(varRetryPolicy)

	return err
}

type NullableRetryPolicy struct {
	value *RetryPolicy
	isSet bool
}

func (v NullableRetryPolicy) Get() *RetryPolicy {
	return v.value
}

func (v *NullableRetryPolicy) Set(val *RetryPolicy) {
	v.value = val
	v.isSet = true
}

func (v NullableRetryPolicy) IsSet() bool {
	return v.isSet
}

func (v *NullableRetryPolicy) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRetryPolicy(val *RetryPolicy) *NullableRetryPolicy {
	return &NullableRetryPolicy{value: val, isSet: true}
}

func (v NullableRetryPolicy) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRetryPolicy) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
