// SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

/*
NVIDIA Infra Controller REST API

NVIDIA Infra Controller REST API allows users to create and manage resources e.g. VPC, Subnets, Instances across all connected NVIDIA Infra Controller datacenters, also referred to as Sites.

API version: 1.6.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package standard

import (
	"encoding/json"
	"fmt"
)

// DpuExtensionServiceDeploymentStatus Status values for DPU Extension Service Deployment objects
type DpuExtensionServiceDeploymentStatus string

// List of DpuExtensionServiceDeploymentStatus
const (
	DPUEXTENSIONSERVICEDEPLOYMENTSTATUS_PENDING     DpuExtensionServiceDeploymentStatus = "Pending"
	DPUEXTENSIONSERVICEDEPLOYMENTSTATUS_RUNNING     DpuExtensionServiceDeploymentStatus = "Running"
	DPUEXTENSIONSERVICEDEPLOYMENTSTATUS_ERROR       DpuExtensionServiceDeploymentStatus = "Error"
	DPUEXTENSIONSERVICEDEPLOYMENTSTATUS_FAILED      DpuExtensionServiceDeploymentStatus = "Failed"
	DPUEXTENSIONSERVICEDEPLOYMENTSTATUS_TERMINATING DpuExtensionServiceDeploymentStatus = "Terminating"
)

// All allowed values of DpuExtensionServiceDeploymentStatus enum
var AllowedDpuExtensionServiceDeploymentStatusEnumValues = []DpuExtensionServiceDeploymentStatus{
	"Pending",
	"Running",
	"Error",
	"Failed",
	"Terminating",
}

func (v *DpuExtensionServiceDeploymentStatus) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := DpuExtensionServiceDeploymentStatus(value)
	for _, existing := range AllowedDpuExtensionServiceDeploymentStatusEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid DpuExtensionServiceDeploymentStatus", value)
}

// NewDpuExtensionServiceDeploymentStatusFromValue returns a pointer to a valid DpuExtensionServiceDeploymentStatus
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewDpuExtensionServiceDeploymentStatusFromValue(v string) (*DpuExtensionServiceDeploymentStatus, error) {
	ev := DpuExtensionServiceDeploymentStatus(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for DpuExtensionServiceDeploymentStatus: valid values are %v", v, AllowedDpuExtensionServiceDeploymentStatusEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v DpuExtensionServiceDeploymentStatus) IsValid() bool {
	for _, existing := range AllowedDpuExtensionServiceDeploymentStatusEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to DpuExtensionServiceDeploymentStatus value
func (v DpuExtensionServiceDeploymentStatus) Ptr() *DpuExtensionServiceDeploymentStatus {
	return &v
}

type NullableDpuExtensionServiceDeploymentStatus struct {
	value *DpuExtensionServiceDeploymentStatus
	isSet bool
}

func (v NullableDpuExtensionServiceDeploymentStatus) Get() *DpuExtensionServiceDeploymentStatus {
	return v.value
}

func (v *NullableDpuExtensionServiceDeploymentStatus) Set(val *DpuExtensionServiceDeploymentStatus) {
	v.value = val
	v.isSet = true
}

func (v NullableDpuExtensionServiceDeploymentStatus) IsSet() bool {
	return v.isSet
}

func (v *NullableDpuExtensionServiceDeploymentStatus) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDpuExtensionServiceDeploymentStatus(val *DpuExtensionServiceDeploymentStatus) *NullableDpuExtensionServiceDeploymentStatus {
	return &NullableDpuExtensionServiceDeploymentStatus{value: val, isSet: true}
}

func (v NullableDpuExtensionServiceDeploymentStatus) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDpuExtensionServiceDeploymentStatus) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
