// SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

/*
NVIDIA Infra Controller REST API

NVIDIA Infra Controller REST API allows users to create and manage resources, e.g., VPCs, Subnets, and Instances, across all connected NVIDIA Infra Controller datacenters, also referred to as Sites.

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package standard

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the NVLinkDomainFirmwareUpdateRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &NVLinkDomainFirmwareUpdateRequest{}

// NVLinkDomainFirmwareUpdateRequest Request body for an NVLink Domain firmware update
type NVLinkDomainFirmwareUpdateRequest struct {
	// ID of the Site
	SiteId string `json:"siteId"`
	// Target firmware version. When empty, null, or omitted, use the default firmware version for each targeted component.
	Version NullableString `json:"version,omitempty"`
	// Optional Operation Rule UUID. When set, pins every task spawned by this operation to the named rule and overrides Flow's default rule resolution.
	RuleId *string `json:"ruleId,omitempty"`
	// When true, proceed even if one or more target components (or hosts on the owning rack for rack-scoped components) are reported as not ready by their persisted status. Intended for operator-supervised maintenance.
	OverrideReadinessCheck *bool `json:"overrideReadinessCheck,omitempty"`
}

type _NVLinkDomainFirmwareUpdateRequest NVLinkDomainFirmwareUpdateRequest

// NewNVLinkDomainFirmwareUpdateRequest instantiates a new NVLinkDomainFirmwareUpdateRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewNVLinkDomainFirmwareUpdateRequest(siteId string) *NVLinkDomainFirmwareUpdateRequest {
	this := NVLinkDomainFirmwareUpdateRequest{}
	this.SiteId = siteId
	var overrideReadinessCheck bool = false
	this.OverrideReadinessCheck = &overrideReadinessCheck
	return &this
}

// NewNVLinkDomainFirmwareUpdateRequestWithDefaults instantiates a new NVLinkDomainFirmwareUpdateRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewNVLinkDomainFirmwareUpdateRequestWithDefaults() *NVLinkDomainFirmwareUpdateRequest {
	this := NVLinkDomainFirmwareUpdateRequest{}
	var overrideReadinessCheck bool = false
	this.OverrideReadinessCheck = &overrideReadinessCheck
	return &this
}

// GetSiteId returns the SiteId field value
func (o *NVLinkDomainFirmwareUpdateRequest) GetSiteId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SiteId
}

// GetSiteIdOk returns a tuple with the SiteId field value
// and a boolean to check if the value has been set.
func (o *NVLinkDomainFirmwareUpdateRequest) GetSiteIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SiteId, true
}

// SetSiteId sets field value
func (o *NVLinkDomainFirmwareUpdateRequest) SetSiteId(v string) {
	o.SiteId = v
}

// GetVersion returns the Version field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *NVLinkDomainFirmwareUpdateRequest) GetVersion() string {
	if o == nil || IsNil(o.Version.Get()) {
		var ret string
		return ret
	}
	return *o.Version.Get()
}

// GetVersionOk returns a tuple with the Version field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *NVLinkDomainFirmwareUpdateRequest) GetVersionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Version.Get(), o.Version.IsSet()
}

// HasVersion returns a boolean if a field has been set.
func (o *NVLinkDomainFirmwareUpdateRequest) HasVersion() bool {
	if o != nil && o.Version.IsSet() {
		return true
	}

	return false
}

// SetVersion gets a reference to the given NullableString and assigns it to the Version field.
func (o *NVLinkDomainFirmwareUpdateRequest) SetVersion(v string) {
	o.Version.Set(&v)
}

// SetVersionNil sets the value for Version to be an explicit nil
func (o *NVLinkDomainFirmwareUpdateRequest) SetVersionNil() {
	o.Version.Set(nil)
}

// UnsetVersion ensures that no value is present for Version, not even an explicit nil
func (o *NVLinkDomainFirmwareUpdateRequest) UnsetVersion() {
	o.Version.Unset()
}

// GetRuleId returns the RuleId field value if set, zero value otherwise.
func (o *NVLinkDomainFirmwareUpdateRequest) GetRuleId() string {
	if o == nil || IsNil(o.RuleId) {
		var ret string
		return ret
	}
	return *o.RuleId
}

// GetRuleIdOk returns a tuple with the RuleId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NVLinkDomainFirmwareUpdateRequest) GetRuleIdOk() (*string, bool) {
	if o == nil || IsNil(o.RuleId) {
		return nil, false
	}
	return o.RuleId, true
}

// HasRuleId returns a boolean if a field has been set.
func (o *NVLinkDomainFirmwareUpdateRequest) HasRuleId() bool {
	if o != nil && !IsNil(o.RuleId) {
		return true
	}

	return false
}

// SetRuleId gets a reference to the given string and assigns it to the RuleId field.
func (o *NVLinkDomainFirmwareUpdateRequest) SetRuleId(v string) {
	o.RuleId = &v
}

// GetOverrideReadinessCheck returns the OverrideReadinessCheck field value if set, zero value otherwise.
func (o *NVLinkDomainFirmwareUpdateRequest) GetOverrideReadinessCheck() bool {
	if o == nil || IsNil(o.OverrideReadinessCheck) {
		var ret bool
		return ret
	}
	return *o.OverrideReadinessCheck
}

// GetOverrideReadinessCheckOk returns a tuple with the OverrideReadinessCheck field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NVLinkDomainFirmwareUpdateRequest) GetOverrideReadinessCheckOk() (*bool, bool) {
	if o == nil || IsNil(o.OverrideReadinessCheck) {
		return nil, false
	}
	return o.OverrideReadinessCheck, true
}

// HasOverrideReadinessCheck returns a boolean if a field has been set.
func (o *NVLinkDomainFirmwareUpdateRequest) HasOverrideReadinessCheck() bool {
	if o != nil && !IsNil(o.OverrideReadinessCheck) {
		return true
	}

	return false
}

// SetOverrideReadinessCheck gets a reference to the given bool and assigns it to the OverrideReadinessCheck field.
func (o *NVLinkDomainFirmwareUpdateRequest) SetOverrideReadinessCheck(v bool) {
	o.OverrideReadinessCheck = &v
}

func (o NVLinkDomainFirmwareUpdateRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o NVLinkDomainFirmwareUpdateRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["siteId"] = o.SiteId
	if o.Version.IsSet() {
		toSerialize["version"] = o.Version.Get()
	}
	if !IsNil(o.RuleId) {
		toSerialize["ruleId"] = o.RuleId
	}
	if !IsNil(o.OverrideReadinessCheck) {
		toSerialize["overrideReadinessCheck"] = o.OverrideReadinessCheck
	}
	return toSerialize, nil
}

func (o *NVLinkDomainFirmwareUpdateRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"siteId",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if value, exists := allProperties[requiredProperty]; !exists || value == nil {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varNVLinkDomainFirmwareUpdateRequest := _NVLinkDomainFirmwareUpdateRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	err = decoder.Decode(&varNVLinkDomainFirmwareUpdateRequest)

	if err != nil {
		return err
	}

	*o = NVLinkDomainFirmwareUpdateRequest(varNVLinkDomainFirmwareUpdateRequest)

	return err
}

type NullableNVLinkDomainFirmwareUpdateRequest struct {
	value *NVLinkDomainFirmwareUpdateRequest
	isSet bool
}

func (v NullableNVLinkDomainFirmwareUpdateRequest) Get() *NVLinkDomainFirmwareUpdateRequest {
	return v.value
}

func (v *NullableNVLinkDomainFirmwareUpdateRequest) Set(val *NVLinkDomainFirmwareUpdateRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableNVLinkDomainFirmwareUpdateRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableNVLinkDomainFirmwareUpdateRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableNVLinkDomainFirmwareUpdateRequest(val *NVLinkDomainFirmwareUpdateRequest) *NullableNVLinkDomainFirmwareUpdateRequest {
	return &NullableNVLinkDomainFirmwareUpdateRequest{value: val, isSet: true}
}

func (v NullableNVLinkDomainFirmwareUpdateRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableNVLinkDomainFirmwareUpdateRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
