// SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

/*
NVIDIA Infra Controller REST API

NVIDIA Infra Controller REST API allows users to create and manage resources e.g. VPC, Subnets, Instances across all connected NVIDIA Infra Controller datacenters, also referred to as Sites.

API version: 1.6.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package standard

import (
	"encoding/json"
	"time"
)

// checks if the MachineInterface type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MachineInterface{}

// MachineInterface Describes an interface attached to a machine
type MachineInterface struct {
	Id                    *string        `json:"id,omitempty"`
	MachineId             *string        `json:"machineId,omitempty"`
	ControllerInterfaceId NullableString `json:"controllerInterfaceId,omitempty"`
	ControllerSegmentId   NullableString `json:"controllerSegmentId,omitempty"`
	AttachedDpuMachineID  NullableString `json:"attachedDpuMachineID,omitempty"`
	SubnetId              NullableString `json:"subnetId,omitempty"`
	Hostname              NullableString `json:"hostname,omitempty"`
	IsPrimary             *bool          `json:"isPrimary,omitempty"`
	MacAddress            NullableString `json:"macAddress,omitempty"`
	// Array of IP addresses
	IpAddresses []string   `json:"ipAddresses,omitempty"`
	Created     *time.Time `json:"created,omitempty"`
	Updated     *time.Time `json:"updated,omitempty"`
}

// NewMachineInterface instantiates a new MachineInterface object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMachineInterface() *MachineInterface {
	this := MachineInterface{}
	return &this
}

// NewMachineInterfaceWithDefaults instantiates a new MachineInterface object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMachineInterfaceWithDefaults() *MachineInterface {
	this := MachineInterface{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *MachineInterface) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MachineInterface) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *MachineInterface) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *MachineInterface) SetId(v string) {
	o.Id = &v
}

// GetMachineId returns the MachineId field value if set, zero value otherwise.
func (o *MachineInterface) GetMachineId() string {
	if o == nil || IsNil(o.MachineId) {
		var ret string
		return ret
	}
	return *o.MachineId
}

// GetMachineIdOk returns a tuple with the MachineId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MachineInterface) GetMachineIdOk() (*string, bool) {
	if o == nil || IsNil(o.MachineId) {
		return nil, false
	}
	return o.MachineId, true
}

// HasMachineId returns a boolean if a field has been set.
func (o *MachineInterface) HasMachineId() bool {
	if o != nil && !IsNil(o.MachineId) {
		return true
	}

	return false
}

// SetMachineId gets a reference to the given string and assigns it to the MachineId field.
func (o *MachineInterface) SetMachineId(v string) {
	o.MachineId = &v
}

// GetControllerInterfaceId returns the ControllerInterfaceId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *MachineInterface) GetControllerInterfaceId() string {
	if o == nil || IsNil(o.ControllerInterfaceId.Get()) {
		var ret string
		return ret
	}
	return *o.ControllerInterfaceId.Get()
}

// GetControllerInterfaceIdOk returns a tuple with the ControllerInterfaceId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *MachineInterface) GetControllerInterfaceIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ControllerInterfaceId.Get(), o.ControllerInterfaceId.IsSet()
}

// HasControllerInterfaceId returns a boolean if a field has been set.
func (o *MachineInterface) HasControllerInterfaceId() bool {
	if o != nil && o.ControllerInterfaceId.IsSet() {
		return true
	}

	return false
}

// SetControllerInterfaceId gets a reference to the given NullableString and assigns it to the ControllerInterfaceId field.
func (o *MachineInterface) SetControllerInterfaceId(v string) {
	o.ControllerInterfaceId.Set(&v)
}

// SetControllerInterfaceIdNil sets the value for ControllerInterfaceId to be an explicit nil
func (o *MachineInterface) SetControllerInterfaceIdNil() {
	o.ControllerInterfaceId.Set(nil)
}

// UnsetControllerInterfaceId ensures that no value is present for ControllerInterfaceId, not even an explicit nil
func (o *MachineInterface) UnsetControllerInterfaceId() {
	o.ControllerInterfaceId.Unset()
}

// GetControllerSegmentId returns the ControllerSegmentId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *MachineInterface) GetControllerSegmentId() string {
	if o == nil || IsNil(o.ControllerSegmentId.Get()) {
		var ret string
		return ret
	}
	return *o.ControllerSegmentId.Get()
}

// GetControllerSegmentIdOk returns a tuple with the ControllerSegmentId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *MachineInterface) GetControllerSegmentIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ControllerSegmentId.Get(), o.ControllerSegmentId.IsSet()
}

// HasControllerSegmentId returns a boolean if a field has been set.
func (o *MachineInterface) HasControllerSegmentId() bool {
	if o != nil && o.ControllerSegmentId.IsSet() {
		return true
	}

	return false
}

// SetControllerSegmentId gets a reference to the given NullableString and assigns it to the ControllerSegmentId field.
func (o *MachineInterface) SetControllerSegmentId(v string) {
	o.ControllerSegmentId.Set(&v)
}

// SetControllerSegmentIdNil sets the value for ControllerSegmentId to be an explicit nil
func (o *MachineInterface) SetControllerSegmentIdNil() {
	o.ControllerSegmentId.Set(nil)
}

// UnsetControllerSegmentId ensures that no value is present for ControllerSegmentId, not even an explicit nil
func (o *MachineInterface) UnsetControllerSegmentId() {
	o.ControllerSegmentId.Unset()
}

// GetAttachedDpuMachineID returns the AttachedDpuMachineID field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *MachineInterface) GetAttachedDpuMachineID() string {
	if o == nil || IsNil(o.AttachedDpuMachineID.Get()) {
		var ret string
		return ret
	}
	return *o.AttachedDpuMachineID.Get()
}

// GetAttachedDpuMachineIDOk returns a tuple with the AttachedDpuMachineID field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *MachineInterface) GetAttachedDpuMachineIDOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.AttachedDpuMachineID.Get(), o.AttachedDpuMachineID.IsSet()
}

// HasAttachedDpuMachineID returns a boolean if a field has been set.
func (o *MachineInterface) HasAttachedDpuMachineID() bool {
	if o != nil && o.AttachedDpuMachineID.IsSet() {
		return true
	}

	return false
}

// SetAttachedDpuMachineID gets a reference to the given NullableString and assigns it to the AttachedDpuMachineID field.
func (o *MachineInterface) SetAttachedDpuMachineID(v string) {
	o.AttachedDpuMachineID.Set(&v)
}

// SetAttachedDpuMachineIDNil sets the value for AttachedDpuMachineID to be an explicit nil
func (o *MachineInterface) SetAttachedDpuMachineIDNil() {
	o.AttachedDpuMachineID.Set(nil)
}

// UnsetAttachedDpuMachineID ensures that no value is present for AttachedDpuMachineID, not even an explicit nil
func (o *MachineInterface) UnsetAttachedDpuMachineID() {
	o.AttachedDpuMachineID.Unset()
}

// GetSubnetId returns the SubnetId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *MachineInterface) GetSubnetId() string {
	if o == nil || IsNil(o.SubnetId.Get()) {
		var ret string
		return ret
	}
	return *o.SubnetId.Get()
}

// GetSubnetIdOk returns a tuple with the SubnetId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *MachineInterface) GetSubnetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.SubnetId.Get(), o.SubnetId.IsSet()
}

// HasSubnetId returns a boolean if a field has been set.
func (o *MachineInterface) HasSubnetId() bool {
	if o != nil && o.SubnetId.IsSet() {
		return true
	}

	return false
}

// SetSubnetId gets a reference to the given NullableString and assigns it to the SubnetId field.
func (o *MachineInterface) SetSubnetId(v string) {
	o.SubnetId.Set(&v)
}

// SetSubnetIdNil sets the value for SubnetId to be an explicit nil
func (o *MachineInterface) SetSubnetIdNil() {
	o.SubnetId.Set(nil)
}

// UnsetSubnetId ensures that no value is present for SubnetId, not even an explicit nil
func (o *MachineInterface) UnsetSubnetId() {
	o.SubnetId.Unset()
}

// GetHostname returns the Hostname field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *MachineInterface) GetHostname() string {
	if o == nil || IsNil(o.Hostname.Get()) {
		var ret string
		return ret
	}
	return *o.Hostname.Get()
}

// GetHostnameOk returns a tuple with the Hostname field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *MachineInterface) GetHostnameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Hostname.Get(), o.Hostname.IsSet()
}

// HasHostname returns a boolean if a field has been set.
func (o *MachineInterface) HasHostname() bool {
	if o != nil && o.Hostname.IsSet() {
		return true
	}

	return false
}

// SetHostname gets a reference to the given NullableString and assigns it to the Hostname field.
func (o *MachineInterface) SetHostname(v string) {
	o.Hostname.Set(&v)
}

// SetHostnameNil sets the value for Hostname to be an explicit nil
func (o *MachineInterface) SetHostnameNil() {
	o.Hostname.Set(nil)
}

// UnsetHostname ensures that no value is present for Hostname, not even an explicit nil
func (o *MachineInterface) UnsetHostname() {
	o.Hostname.Unset()
}

// GetIsPrimary returns the IsPrimary field value if set, zero value otherwise.
func (o *MachineInterface) GetIsPrimary() bool {
	if o == nil || IsNil(o.IsPrimary) {
		var ret bool
		return ret
	}
	return *o.IsPrimary
}

// GetIsPrimaryOk returns a tuple with the IsPrimary field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MachineInterface) GetIsPrimaryOk() (*bool, bool) {
	if o == nil || IsNil(o.IsPrimary) {
		return nil, false
	}
	return o.IsPrimary, true
}

// HasIsPrimary returns a boolean if a field has been set.
func (o *MachineInterface) HasIsPrimary() bool {
	if o != nil && !IsNil(o.IsPrimary) {
		return true
	}

	return false
}

// SetIsPrimary gets a reference to the given bool and assigns it to the IsPrimary field.
func (o *MachineInterface) SetIsPrimary(v bool) {
	o.IsPrimary = &v
}

// GetMacAddress returns the MacAddress field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *MachineInterface) GetMacAddress() string {
	if o == nil || IsNil(o.MacAddress.Get()) {
		var ret string
		return ret
	}
	return *o.MacAddress.Get()
}

// GetMacAddressOk returns a tuple with the MacAddress field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *MachineInterface) GetMacAddressOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.MacAddress.Get(), o.MacAddress.IsSet()
}

// HasMacAddress returns a boolean if a field has been set.
func (o *MachineInterface) HasMacAddress() bool {
	if o != nil && o.MacAddress.IsSet() {
		return true
	}

	return false
}

// SetMacAddress gets a reference to the given NullableString and assigns it to the MacAddress field.
func (o *MachineInterface) SetMacAddress(v string) {
	o.MacAddress.Set(&v)
}

// SetMacAddressNil sets the value for MacAddress to be an explicit nil
func (o *MachineInterface) SetMacAddressNil() {
	o.MacAddress.Set(nil)
}

// UnsetMacAddress ensures that no value is present for MacAddress, not even an explicit nil
func (o *MachineInterface) UnsetMacAddress() {
	o.MacAddress.Unset()
}

// GetIpAddresses returns the IpAddresses field value if set, zero value otherwise.
func (o *MachineInterface) GetIpAddresses() []string {
	if o == nil || IsNil(o.IpAddresses) {
		var ret []string
		return ret
	}
	return o.IpAddresses
}

// GetIpAddressesOk returns a tuple with the IpAddresses field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MachineInterface) GetIpAddressesOk() ([]string, bool) {
	if o == nil || IsNil(o.IpAddresses) {
		return nil, false
	}
	return o.IpAddresses, true
}

// HasIpAddresses returns a boolean if a field has been set.
func (o *MachineInterface) HasIpAddresses() bool {
	if o != nil && !IsNil(o.IpAddresses) {
		return true
	}

	return false
}

// SetIpAddresses gets a reference to the given []string and assigns it to the IpAddresses field.
func (o *MachineInterface) SetIpAddresses(v []string) {
	o.IpAddresses = v
}

// GetCreated returns the Created field value if set, zero value otherwise.
func (o *MachineInterface) GetCreated() time.Time {
	if o == nil || IsNil(o.Created) {
		var ret time.Time
		return ret
	}
	return *o.Created
}

// GetCreatedOk returns a tuple with the Created field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MachineInterface) GetCreatedOk() (*time.Time, bool) {
	if o == nil || IsNil(o.Created) {
		return nil, false
	}
	return o.Created, true
}

// HasCreated returns a boolean if a field has been set.
func (o *MachineInterface) HasCreated() bool {
	if o != nil && !IsNil(o.Created) {
		return true
	}

	return false
}

// SetCreated gets a reference to the given time.Time and assigns it to the Created field.
func (o *MachineInterface) SetCreated(v time.Time) {
	o.Created = &v
}

// GetUpdated returns the Updated field value if set, zero value otherwise.
func (o *MachineInterface) GetUpdated() time.Time {
	if o == nil || IsNil(o.Updated) {
		var ret time.Time
		return ret
	}
	return *o.Updated
}

// GetUpdatedOk returns a tuple with the Updated field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MachineInterface) GetUpdatedOk() (*time.Time, bool) {
	if o == nil || IsNil(o.Updated) {
		return nil, false
	}
	return o.Updated, true
}

// HasUpdated returns a boolean if a field has been set.
func (o *MachineInterface) HasUpdated() bool {
	if o != nil && !IsNil(o.Updated) {
		return true
	}

	return false
}

// SetUpdated gets a reference to the given time.Time and assigns it to the Updated field.
func (o *MachineInterface) SetUpdated(v time.Time) {
	o.Updated = &v
}

func (o MachineInterface) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MachineInterface) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.MachineId) {
		toSerialize["machineId"] = o.MachineId
	}
	if o.ControllerInterfaceId.IsSet() {
		toSerialize["controllerInterfaceId"] = o.ControllerInterfaceId.Get()
	}
	if o.ControllerSegmentId.IsSet() {
		toSerialize["controllerSegmentId"] = o.ControllerSegmentId.Get()
	}
	if o.AttachedDpuMachineID.IsSet() {
		toSerialize["attachedDpuMachineID"] = o.AttachedDpuMachineID.Get()
	}
	if o.SubnetId.IsSet() {
		toSerialize["subnetId"] = o.SubnetId.Get()
	}
	if o.Hostname.IsSet() {
		toSerialize["hostname"] = o.Hostname.Get()
	}
	if !IsNil(o.IsPrimary) {
		toSerialize["isPrimary"] = o.IsPrimary
	}
	if o.MacAddress.IsSet() {
		toSerialize["macAddress"] = o.MacAddress.Get()
	}
	if !IsNil(o.IpAddresses) {
		toSerialize["ipAddresses"] = o.IpAddresses
	}
	if !IsNil(o.Created) {
		toSerialize["created"] = o.Created
	}
	if !IsNil(o.Updated) {
		toSerialize["updated"] = o.Updated
	}
	return toSerialize, nil
}

type NullableMachineInterface struct {
	value *MachineInterface
	isSet bool
}

func (v NullableMachineInterface) Get() *MachineInterface {
	return v.value
}

func (v *NullableMachineInterface) Set(val *MachineInterface) {
	v.value = val
	v.isSet = true
}

func (v NullableMachineInterface) IsSet() bool {
	return v.isSet
}

func (v *NullableMachineInterface) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMachineInterface(val *MachineInterface) *NullableMachineInterface {
	return &NullableMachineInterface{value: val, isSet: true}
}

func (v NullableMachineInterface) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMachineInterface) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
