// SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

/*
NVIDIA Infra Controller REST API

NVIDIA Infra Controller REST API allows users to create and manage resources, e.g., VPCs, Subnets, and Instances, across all connected NVIDIA Infra Controller datacenters, also referred to as Sites.

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package standard

import (
	"encoding/json"
)

// checks if the VpcRoutingProfileOverrides type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &VpcRoutingProfileOverrides{}

// VpcRoutingProfileOverrides Presence-aware routing-profile properties set directly on a VPC. Each present property replaces the corresponding named-profile value; omitted properties inherit from that profile.
type VpcRoutingProfileOverrides struct {
	// Route targets imported into the VPC. An empty array overrides the named profile with no imports.
	RouteTargetImports []VpcRouteTarget `json:"routeTargetImports,omitempty"`
	// Route targets attached to VPC exports. An empty array overrides the named profile with no export targets.
	RouteTargetsOnExports []VpcRouteTarget `json:"routeTargetsOnExports,omitempty"`
	// Whether the underlay default route is leaked into the VPC.
	LeakDefaultRouteFromUnderlay NullableBool `json:"leakDefaultRouteFromUnderlay,omitempty"`
	// Whether tenant host routes are leaked into the underlay.
	LeakTenantHostRoutesToUnderlay NullableBool `json:"leakTenantHostRoutesToUnderlay,omitempty"`
	// Whether tenant-supplied route-leak communities are honored.
	TenantLeakCommunitiesAccepted NullableBool `json:"tenantLeakCommunitiesAccepted,omitempty"`
	// IPv4 or IPv6 CIDR prefixes allowed to leak from the underlay. An empty array disables explicitly accepted leaks.
	AcceptedLeaksFromUnderlay []string `json:"acceptedLeaksFromUnderlay,omitempty"`
	// IPv4 or IPv6 CIDR prefixes tenant hosts may announce as anycast routes. An empty array disables anycast announcements.
	AllowedAnycastPrefixes []string `json:"allowedAnycastPrefixes,omitempty"`
}

// NewVpcRoutingProfileOverrides instantiates a new VpcRoutingProfileOverrides object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewVpcRoutingProfileOverrides() *VpcRoutingProfileOverrides {
	this := VpcRoutingProfileOverrides{}
	return &this
}

// NewVpcRoutingProfileOverridesWithDefaults instantiates a new VpcRoutingProfileOverrides object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewVpcRoutingProfileOverridesWithDefaults() *VpcRoutingProfileOverrides {
	this := VpcRoutingProfileOverrides{}
	return &this
}

// GetRouteTargetImports returns the RouteTargetImports field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *VpcRoutingProfileOverrides) GetRouteTargetImports() []VpcRouteTarget {
	if o == nil {
		var ret []VpcRouteTarget
		return ret
	}
	return o.RouteTargetImports
}

// GetRouteTargetImportsOk returns a tuple with the RouteTargetImports field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *VpcRoutingProfileOverrides) GetRouteTargetImportsOk() ([]VpcRouteTarget, bool) {
	if o == nil || IsNil(o.RouteTargetImports) {
		return nil, false
	}
	return o.RouteTargetImports, true
}

// HasRouteTargetImports returns a boolean if a field has been set.
func (o *VpcRoutingProfileOverrides) HasRouteTargetImports() bool {
	if o != nil && !IsNil(o.RouteTargetImports) {
		return true
	}

	return false
}

// SetRouteTargetImports gets a reference to the given []VpcRouteTarget and assigns it to the RouteTargetImports field.
func (o *VpcRoutingProfileOverrides) SetRouteTargetImports(v []VpcRouteTarget) {
	o.RouteTargetImports = v
}

// GetRouteTargetsOnExports returns the RouteTargetsOnExports field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *VpcRoutingProfileOverrides) GetRouteTargetsOnExports() []VpcRouteTarget {
	if o == nil {
		var ret []VpcRouteTarget
		return ret
	}
	return o.RouteTargetsOnExports
}

// GetRouteTargetsOnExportsOk returns a tuple with the RouteTargetsOnExports field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *VpcRoutingProfileOverrides) GetRouteTargetsOnExportsOk() ([]VpcRouteTarget, bool) {
	if o == nil || IsNil(o.RouteTargetsOnExports) {
		return nil, false
	}
	return o.RouteTargetsOnExports, true
}

// HasRouteTargetsOnExports returns a boolean if a field has been set.
func (o *VpcRoutingProfileOverrides) HasRouteTargetsOnExports() bool {
	if o != nil && !IsNil(o.RouteTargetsOnExports) {
		return true
	}

	return false
}

// SetRouteTargetsOnExports gets a reference to the given []VpcRouteTarget and assigns it to the RouteTargetsOnExports field.
func (o *VpcRoutingProfileOverrides) SetRouteTargetsOnExports(v []VpcRouteTarget) {
	o.RouteTargetsOnExports = v
}

// GetLeakDefaultRouteFromUnderlay returns the LeakDefaultRouteFromUnderlay field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *VpcRoutingProfileOverrides) GetLeakDefaultRouteFromUnderlay() bool {
	if o == nil || IsNil(o.LeakDefaultRouteFromUnderlay.Get()) {
		var ret bool
		return ret
	}
	return *o.LeakDefaultRouteFromUnderlay.Get()
}

// GetLeakDefaultRouteFromUnderlayOk returns a tuple with the LeakDefaultRouteFromUnderlay field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *VpcRoutingProfileOverrides) GetLeakDefaultRouteFromUnderlayOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return o.LeakDefaultRouteFromUnderlay.Get(), o.LeakDefaultRouteFromUnderlay.IsSet()
}

// HasLeakDefaultRouteFromUnderlay returns a boolean if a field has been set.
func (o *VpcRoutingProfileOverrides) HasLeakDefaultRouteFromUnderlay() bool {
	if o != nil && o.LeakDefaultRouteFromUnderlay.IsSet() {
		return true
	}

	return false
}

// SetLeakDefaultRouteFromUnderlay gets a reference to the given NullableBool and assigns it to the LeakDefaultRouteFromUnderlay field.
func (o *VpcRoutingProfileOverrides) SetLeakDefaultRouteFromUnderlay(v bool) {
	o.LeakDefaultRouteFromUnderlay.Set(&v)
}

// SetLeakDefaultRouteFromUnderlayNil sets the value for LeakDefaultRouteFromUnderlay to be an explicit nil
func (o *VpcRoutingProfileOverrides) SetLeakDefaultRouteFromUnderlayNil() {
	o.LeakDefaultRouteFromUnderlay.Set(nil)
}

// UnsetLeakDefaultRouteFromUnderlay ensures that no value is present for LeakDefaultRouteFromUnderlay, not even an explicit nil
func (o *VpcRoutingProfileOverrides) UnsetLeakDefaultRouteFromUnderlay() {
	o.LeakDefaultRouteFromUnderlay.Unset()
}

// GetLeakTenantHostRoutesToUnderlay returns the LeakTenantHostRoutesToUnderlay field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *VpcRoutingProfileOverrides) GetLeakTenantHostRoutesToUnderlay() bool {
	if o == nil || IsNil(o.LeakTenantHostRoutesToUnderlay.Get()) {
		var ret bool
		return ret
	}
	return *o.LeakTenantHostRoutesToUnderlay.Get()
}

// GetLeakTenantHostRoutesToUnderlayOk returns a tuple with the LeakTenantHostRoutesToUnderlay field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *VpcRoutingProfileOverrides) GetLeakTenantHostRoutesToUnderlayOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return o.LeakTenantHostRoutesToUnderlay.Get(), o.LeakTenantHostRoutesToUnderlay.IsSet()
}

// HasLeakTenantHostRoutesToUnderlay returns a boolean if a field has been set.
func (o *VpcRoutingProfileOverrides) HasLeakTenantHostRoutesToUnderlay() bool {
	if o != nil && o.LeakTenantHostRoutesToUnderlay.IsSet() {
		return true
	}

	return false
}

// SetLeakTenantHostRoutesToUnderlay gets a reference to the given NullableBool and assigns it to the LeakTenantHostRoutesToUnderlay field.
func (o *VpcRoutingProfileOverrides) SetLeakTenantHostRoutesToUnderlay(v bool) {
	o.LeakTenantHostRoutesToUnderlay.Set(&v)
}

// SetLeakTenantHostRoutesToUnderlayNil sets the value for LeakTenantHostRoutesToUnderlay to be an explicit nil
func (o *VpcRoutingProfileOverrides) SetLeakTenantHostRoutesToUnderlayNil() {
	o.LeakTenantHostRoutesToUnderlay.Set(nil)
}

// UnsetLeakTenantHostRoutesToUnderlay ensures that no value is present for LeakTenantHostRoutesToUnderlay, not even an explicit nil
func (o *VpcRoutingProfileOverrides) UnsetLeakTenantHostRoutesToUnderlay() {
	o.LeakTenantHostRoutesToUnderlay.Unset()
}

// GetTenantLeakCommunitiesAccepted returns the TenantLeakCommunitiesAccepted field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *VpcRoutingProfileOverrides) GetTenantLeakCommunitiesAccepted() bool {
	if o == nil || IsNil(o.TenantLeakCommunitiesAccepted.Get()) {
		var ret bool
		return ret
	}
	return *o.TenantLeakCommunitiesAccepted.Get()
}

// GetTenantLeakCommunitiesAcceptedOk returns a tuple with the TenantLeakCommunitiesAccepted field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *VpcRoutingProfileOverrides) GetTenantLeakCommunitiesAcceptedOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return o.TenantLeakCommunitiesAccepted.Get(), o.TenantLeakCommunitiesAccepted.IsSet()
}

// HasTenantLeakCommunitiesAccepted returns a boolean if a field has been set.
func (o *VpcRoutingProfileOverrides) HasTenantLeakCommunitiesAccepted() bool {
	if o != nil && o.TenantLeakCommunitiesAccepted.IsSet() {
		return true
	}

	return false
}

// SetTenantLeakCommunitiesAccepted gets a reference to the given NullableBool and assigns it to the TenantLeakCommunitiesAccepted field.
func (o *VpcRoutingProfileOverrides) SetTenantLeakCommunitiesAccepted(v bool) {
	o.TenantLeakCommunitiesAccepted.Set(&v)
}

// SetTenantLeakCommunitiesAcceptedNil sets the value for TenantLeakCommunitiesAccepted to be an explicit nil
func (o *VpcRoutingProfileOverrides) SetTenantLeakCommunitiesAcceptedNil() {
	o.TenantLeakCommunitiesAccepted.Set(nil)
}

// UnsetTenantLeakCommunitiesAccepted ensures that no value is present for TenantLeakCommunitiesAccepted, not even an explicit nil
func (o *VpcRoutingProfileOverrides) UnsetTenantLeakCommunitiesAccepted() {
	o.TenantLeakCommunitiesAccepted.Unset()
}

// GetAcceptedLeaksFromUnderlay returns the AcceptedLeaksFromUnderlay field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *VpcRoutingProfileOverrides) GetAcceptedLeaksFromUnderlay() []string {
	if o == nil {
		var ret []string
		return ret
	}
	return o.AcceptedLeaksFromUnderlay
}

// GetAcceptedLeaksFromUnderlayOk returns a tuple with the AcceptedLeaksFromUnderlay field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *VpcRoutingProfileOverrides) GetAcceptedLeaksFromUnderlayOk() ([]string, bool) {
	if o == nil || IsNil(o.AcceptedLeaksFromUnderlay) {
		return nil, false
	}
	return o.AcceptedLeaksFromUnderlay, true
}

// HasAcceptedLeaksFromUnderlay returns a boolean if a field has been set.
func (o *VpcRoutingProfileOverrides) HasAcceptedLeaksFromUnderlay() bool {
	if o != nil && !IsNil(o.AcceptedLeaksFromUnderlay) {
		return true
	}

	return false
}

// SetAcceptedLeaksFromUnderlay gets a reference to the given []string and assigns it to the AcceptedLeaksFromUnderlay field.
func (o *VpcRoutingProfileOverrides) SetAcceptedLeaksFromUnderlay(v []string) {
	o.AcceptedLeaksFromUnderlay = v
}

// GetAllowedAnycastPrefixes returns the AllowedAnycastPrefixes field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *VpcRoutingProfileOverrides) GetAllowedAnycastPrefixes() []string {
	if o == nil {
		var ret []string
		return ret
	}
	return o.AllowedAnycastPrefixes
}

// GetAllowedAnycastPrefixesOk returns a tuple with the AllowedAnycastPrefixes field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *VpcRoutingProfileOverrides) GetAllowedAnycastPrefixesOk() ([]string, bool) {
	if o == nil || IsNil(o.AllowedAnycastPrefixes) {
		return nil, false
	}
	return o.AllowedAnycastPrefixes, true
}

// HasAllowedAnycastPrefixes returns a boolean if a field has been set.
func (o *VpcRoutingProfileOverrides) HasAllowedAnycastPrefixes() bool {
	if o != nil && !IsNil(o.AllowedAnycastPrefixes) {
		return true
	}

	return false
}

// SetAllowedAnycastPrefixes gets a reference to the given []string and assigns it to the AllowedAnycastPrefixes field.
func (o *VpcRoutingProfileOverrides) SetAllowedAnycastPrefixes(v []string) {
	o.AllowedAnycastPrefixes = v
}

func (o VpcRoutingProfileOverrides) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o VpcRoutingProfileOverrides) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.RouteTargetImports != nil {
		toSerialize["routeTargetImports"] = o.RouteTargetImports
	}
	if o.RouteTargetsOnExports != nil {
		toSerialize["routeTargetsOnExports"] = o.RouteTargetsOnExports
	}
	if o.LeakDefaultRouteFromUnderlay.IsSet() {
		toSerialize["leakDefaultRouteFromUnderlay"] = o.LeakDefaultRouteFromUnderlay.Get()
	}
	if o.LeakTenantHostRoutesToUnderlay.IsSet() {
		toSerialize["leakTenantHostRoutesToUnderlay"] = o.LeakTenantHostRoutesToUnderlay.Get()
	}
	if o.TenantLeakCommunitiesAccepted.IsSet() {
		toSerialize["tenantLeakCommunitiesAccepted"] = o.TenantLeakCommunitiesAccepted.Get()
	}
	if o.AcceptedLeaksFromUnderlay != nil {
		toSerialize["acceptedLeaksFromUnderlay"] = o.AcceptedLeaksFromUnderlay
	}
	if o.AllowedAnycastPrefixes != nil {
		toSerialize["allowedAnycastPrefixes"] = o.AllowedAnycastPrefixes
	}
	return toSerialize, nil
}

type NullableVpcRoutingProfileOverrides struct {
	value *VpcRoutingProfileOverrides
	isSet bool
}

func (v NullableVpcRoutingProfileOverrides) Get() *VpcRoutingProfileOverrides {
	return v.value
}

func (v *NullableVpcRoutingProfileOverrides) Set(val *VpcRoutingProfileOverrides) {
	v.value = val
	v.isSet = true
}

func (v NullableVpcRoutingProfileOverrides) IsSet() bool {
	return v.isSet
}

func (v *NullableVpcRoutingProfileOverrides) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableVpcRoutingProfileOverrides(val *VpcRoutingProfileOverrides) *NullableVpcRoutingProfileOverrides {
	return &NullableVpcRoutingProfileOverrides{value: val, isSet: true}
}

func (v NullableVpcRoutingProfileOverrides) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableVpcRoutingProfileOverrides) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
