// SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

/*
NVIDIA Infra Controller REST API

NVIDIA Infra Controller REST API allows users to create and manage resources, e.g., VPCs, Subnets, and Instances, across all connected NVIDIA Infra Controller datacenters, also referred to as Sites.

API version: 1.6.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package standard

import (
	"bytes"
	"encoding/json"
	"fmt"
	"time"
)

// checks if the MachineHealthReportProbeAlert type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MachineHealthReportProbeAlert{}

// MachineHealthReportProbeAlert Failed Machine health probe submitted to NICo Core.
type MachineHealthReportProbeAlert struct {
	// Health probe identifier.
	Id string `json:"id"`
	// Specific component targeted by health probe.
	Target *string `json:"target,omitempty"`
	// Date/time since the alert has been in effect.
	InAlertSince *time.Time `json:"inAlertSince,omitempty"`
	// Details of the failed health probe result.
	Message string `json:"message"`
	// Information provided by Tenant, if any.
	TenantMessage *string `json:"tenantMessage,omitempty"`
	// Classifications for this alert.
	Classifications []string `json:"classifications,omitempty"`
}

type _MachineHealthReportProbeAlert MachineHealthReportProbeAlert

// NewMachineHealthReportProbeAlert instantiates a new MachineHealthReportProbeAlert object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMachineHealthReportProbeAlert(id string, message string) *MachineHealthReportProbeAlert {
	this := MachineHealthReportProbeAlert{}
	this.Id = id
	this.Message = message
	return &this
}

// NewMachineHealthReportProbeAlertWithDefaults instantiates a new MachineHealthReportProbeAlert object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMachineHealthReportProbeAlertWithDefaults() *MachineHealthReportProbeAlert {
	this := MachineHealthReportProbeAlert{}
	return &this
}

// GetId returns the Id field value
func (o *MachineHealthReportProbeAlert) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *MachineHealthReportProbeAlert) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *MachineHealthReportProbeAlert) SetId(v string) {
	o.Id = v
}

// GetTarget returns the Target field value if set, zero value otherwise.
func (o *MachineHealthReportProbeAlert) GetTarget() string {
	if o == nil || IsNil(o.Target) {
		var ret string
		return ret
	}
	return *o.Target
}

// GetTargetOk returns a tuple with the Target field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MachineHealthReportProbeAlert) GetTargetOk() (*string, bool) {
	if o == nil || IsNil(o.Target) {
		return nil, false
	}
	return o.Target, true
}

// HasTarget returns a boolean if a field has been set.
func (o *MachineHealthReportProbeAlert) HasTarget() bool {
	if o != nil && !IsNil(o.Target) {
		return true
	}

	return false
}

// SetTarget gets a reference to the given string and assigns it to the Target field.
func (o *MachineHealthReportProbeAlert) SetTarget(v string) {
	o.Target = &v
}

// GetInAlertSince returns the InAlertSince field value if set, zero value otherwise.
func (o *MachineHealthReportProbeAlert) GetInAlertSince() time.Time {
	if o == nil || IsNil(o.InAlertSince) {
		var ret time.Time
		return ret
	}
	return *o.InAlertSince
}

// GetInAlertSinceOk returns a tuple with the InAlertSince field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MachineHealthReportProbeAlert) GetInAlertSinceOk() (*time.Time, bool) {
	if o == nil || IsNil(o.InAlertSince) {
		return nil, false
	}
	return o.InAlertSince, true
}

// HasInAlertSince returns a boolean if a field has been set.
func (o *MachineHealthReportProbeAlert) HasInAlertSince() bool {
	if o != nil && !IsNil(o.InAlertSince) {
		return true
	}

	return false
}

// SetInAlertSince gets a reference to the given time.Time and assigns it to the InAlertSince field.
func (o *MachineHealthReportProbeAlert) SetInAlertSince(v time.Time) {
	o.InAlertSince = &v
}

// GetMessage returns the Message field value
func (o *MachineHealthReportProbeAlert) GetMessage() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Message
}

// GetMessageOk returns a tuple with the Message field value
// and a boolean to check if the value has been set.
func (o *MachineHealthReportProbeAlert) GetMessageOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Message, true
}

// SetMessage sets field value
func (o *MachineHealthReportProbeAlert) SetMessage(v string) {
	o.Message = v
}

// GetTenantMessage returns the TenantMessage field value if set, zero value otherwise.
func (o *MachineHealthReportProbeAlert) GetTenantMessage() string {
	if o == nil || IsNil(o.TenantMessage) {
		var ret string
		return ret
	}
	return *o.TenantMessage
}

// GetTenantMessageOk returns a tuple with the TenantMessage field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MachineHealthReportProbeAlert) GetTenantMessageOk() (*string, bool) {
	if o == nil || IsNil(o.TenantMessage) {
		return nil, false
	}
	return o.TenantMessage, true
}

// HasTenantMessage returns a boolean if a field has been set.
func (o *MachineHealthReportProbeAlert) HasTenantMessage() bool {
	if o != nil && !IsNil(o.TenantMessage) {
		return true
	}

	return false
}

// SetTenantMessage gets a reference to the given string and assigns it to the TenantMessage field.
func (o *MachineHealthReportProbeAlert) SetTenantMessage(v string) {
	o.TenantMessage = &v
}

// GetClassifications returns the Classifications field value if set, zero value otherwise.
func (o *MachineHealthReportProbeAlert) GetClassifications() []string {
	if o == nil || IsNil(o.Classifications) {
		var ret []string
		return ret
	}
	return o.Classifications
}

// GetClassificationsOk returns a tuple with the Classifications field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MachineHealthReportProbeAlert) GetClassificationsOk() ([]string, bool) {
	if o == nil || IsNil(o.Classifications) {
		return nil, false
	}
	return o.Classifications, true
}

// HasClassifications returns a boolean if a field has been set.
func (o *MachineHealthReportProbeAlert) HasClassifications() bool {
	if o != nil && !IsNil(o.Classifications) {
		return true
	}

	return false
}

// SetClassifications gets a reference to the given []string and assigns it to the Classifications field.
func (o *MachineHealthReportProbeAlert) SetClassifications(v []string) {
	o.Classifications = v
}

func (o MachineHealthReportProbeAlert) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MachineHealthReportProbeAlert) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	if !IsNil(o.Target) {
		toSerialize["target"] = o.Target
	}
	if !IsNil(o.InAlertSince) {
		toSerialize["inAlertSince"] = o.InAlertSince
	}
	toSerialize["message"] = o.Message
	if !IsNil(o.TenantMessage) {
		toSerialize["tenantMessage"] = o.TenantMessage
	}
	if !IsNil(o.Classifications) {
		toSerialize["classifications"] = o.Classifications
	}
	return toSerialize, nil
}

func (o *MachineHealthReportProbeAlert) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"message",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if value, exists := allProperties[requiredProperty]; !exists || value == nil {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varMachineHealthReportProbeAlert := _MachineHealthReportProbeAlert{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varMachineHealthReportProbeAlert)

	if err != nil {
		return err
	}

	*o = MachineHealthReportProbeAlert(varMachineHealthReportProbeAlert)

	return err
}

type NullableMachineHealthReportProbeAlert struct {
	value *MachineHealthReportProbeAlert
	isSet bool
}

func (v NullableMachineHealthReportProbeAlert) Get() *MachineHealthReportProbeAlert {
	return v.value
}

func (v *NullableMachineHealthReportProbeAlert) Set(val *MachineHealthReportProbeAlert) {
	v.value = val
	v.isSet = true
}

func (v NullableMachineHealthReportProbeAlert) IsSet() bool {
	return v.isSet
}

func (v *NullableMachineHealthReportProbeAlert) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMachineHealthReportProbeAlert(val *MachineHealthReportProbeAlert) *NullableMachineHealthReportProbeAlert {
	return &NullableMachineHealthReportProbeAlert{value: val, isSet: true}
}

func (v NullableMachineHealthReportProbeAlert) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMachineHealthReportProbeAlert) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
