// SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

/*
NVIDIA Infra Controller REST API

NVIDIA Infra Controller REST API allows users to create and manage resources e.g. VPC, Subnets, Instances across all connected NVIDIA Infra Controller datacenters, also referred to as Sites.

API version: 1.6.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package standard

import (
	"encoding/json"
)

// checks if the OpenIDConfiguration type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &OpenIDConfiguration{}

// OpenIDConfiguration OIDC discovery document. Note: `id_token_signing_alg_values_supported` is always empty because NICo issues JWT bearer access tokens, not OIDC `id_token`s.
type OpenIDConfiguration struct {
	Issuer                           *string  `json:"issuer,omitempty"`
	JwksUri                          *string  `json:"jwks_uri,omitempty"`
	ResponseTypesSupported           []string `json:"response_types_supported,omitempty"`
	SubjectTypesSupported            []string `json:"subject_types_supported,omitempty"`
	IdTokenSigningAlgValuesSupported []string `json:"id_token_signing_alg_values_supported,omitempty"`
	SpiffeJwksUri                    *string  `json:"spiffe_jwks_uri,omitempty"`
}

// NewOpenIDConfiguration instantiates a new OpenIDConfiguration object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOpenIDConfiguration() *OpenIDConfiguration {
	this := OpenIDConfiguration{}
	return &this
}

// NewOpenIDConfigurationWithDefaults instantiates a new OpenIDConfiguration object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOpenIDConfigurationWithDefaults() *OpenIDConfiguration {
	this := OpenIDConfiguration{}
	return &this
}

// GetIssuer returns the Issuer field value if set, zero value otherwise.
func (o *OpenIDConfiguration) GetIssuer() string {
	if o == nil || IsNil(o.Issuer) {
		var ret string
		return ret
	}
	return *o.Issuer
}

// GetIssuerOk returns a tuple with the Issuer field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OpenIDConfiguration) GetIssuerOk() (*string, bool) {
	if o == nil || IsNil(o.Issuer) {
		return nil, false
	}
	return o.Issuer, true
}

// HasIssuer returns a boolean if a field has been set.
func (o *OpenIDConfiguration) HasIssuer() bool {
	if o != nil && !IsNil(o.Issuer) {
		return true
	}

	return false
}

// SetIssuer gets a reference to the given string and assigns it to the Issuer field.
func (o *OpenIDConfiguration) SetIssuer(v string) {
	o.Issuer = &v
}

// GetJwksUri returns the JwksUri field value if set, zero value otherwise.
func (o *OpenIDConfiguration) GetJwksUri() string {
	if o == nil || IsNil(o.JwksUri) {
		var ret string
		return ret
	}
	return *o.JwksUri
}

// GetJwksUriOk returns a tuple with the JwksUri field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OpenIDConfiguration) GetJwksUriOk() (*string, bool) {
	if o == nil || IsNil(o.JwksUri) {
		return nil, false
	}
	return o.JwksUri, true
}

// HasJwksUri returns a boolean if a field has been set.
func (o *OpenIDConfiguration) HasJwksUri() bool {
	if o != nil && !IsNil(o.JwksUri) {
		return true
	}

	return false
}

// SetJwksUri gets a reference to the given string and assigns it to the JwksUri field.
func (o *OpenIDConfiguration) SetJwksUri(v string) {
	o.JwksUri = &v
}

// GetResponseTypesSupported returns the ResponseTypesSupported field value if set, zero value otherwise.
func (o *OpenIDConfiguration) GetResponseTypesSupported() []string {
	if o == nil || IsNil(o.ResponseTypesSupported) {
		var ret []string
		return ret
	}
	return o.ResponseTypesSupported
}

// GetResponseTypesSupportedOk returns a tuple with the ResponseTypesSupported field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OpenIDConfiguration) GetResponseTypesSupportedOk() ([]string, bool) {
	if o == nil || IsNil(o.ResponseTypesSupported) {
		return nil, false
	}
	return o.ResponseTypesSupported, true
}

// HasResponseTypesSupported returns a boolean if a field has been set.
func (o *OpenIDConfiguration) HasResponseTypesSupported() bool {
	if o != nil && !IsNil(o.ResponseTypesSupported) {
		return true
	}

	return false
}

// SetResponseTypesSupported gets a reference to the given []string and assigns it to the ResponseTypesSupported field.
func (o *OpenIDConfiguration) SetResponseTypesSupported(v []string) {
	o.ResponseTypesSupported = v
}

// GetSubjectTypesSupported returns the SubjectTypesSupported field value if set, zero value otherwise.
func (o *OpenIDConfiguration) GetSubjectTypesSupported() []string {
	if o == nil || IsNil(o.SubjectTypesSupported) {
		var ret []string
		return ret
	}
	return o.SubjectTypesSupported
}

// GetSubjectTypesSupportedOk returns a tuple with the SubjectTypesSupported field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OpenIDConfiguration) GetSubjectTypesSupportedOk() ([]string, bool) {
	if o == nil || IsNil(o.SubjectTypesSupported) {
		return nil, false
	}
	return o.SubjectTypesSupported, true
}

// HasSubjectTypesSupported returns a boolean if a field has been set.
func (o *OpenIDConfiguration) HasSubjectTypesSupported() bool {
	if o != nil && !IsNil(o.SubjectTypesSupported) {
		return true
	}

	return false
}

// SetSubjectTypesSupported gets a reference to the given []string and assigns it to the SubjectTypesSupported field.
func (o *OpenIDConfiguration) SetSubjectTypesSupported(v []string) {
	o.SubjectTypesSupported = v
}

// GetIdTokenSigningAlgValuesSupported returns the IdTokenSigningAlgValuesSupported field value if set, zero value otherwise.
func (o *OpenIDConfiguration) GetIdTokenSigningAlgValuesSupported() []string {
	if o == nil || IsNil(o.IdTokenSigningAlgValuesSupported) {
		var ret []string
		return ret
	}
	return o.IdTokenSigningAlgValuesSupported
}

// GetIdTokenSigningAlgValuesSupportedOk returns a tuple with the IdTokenSigningAlgValuesSupported field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OpenIDConfiguration) GetIdTokenSigningAlgValuesSupportedOk() ([]string, bool) {
	if o == nil || IsNil(o.IdTokenSigningAlgValuesSupported) {
		return nil, false
	}
	return o.IdTokenSigningAlgValuesSupported, true
}

// HasIdTokenSigningAlgValuesSupported returns a boolean if a field has been set.
func (o *OpenIDConfiguration) HasIdTokenSigningAlgValuesSupported() bool {
	if o != nil && !IsNil(o.IdTokenSigningAlgValuesSupported) {
		return true
	}

	return false
}

// SetIdTokenSigningAlgValuesSupported gets a reference to the given []string and assigns it to the IdTokenSigningAlgValuesSupported field.
func (o *OpenIDConfiguration) SetIdTokenSigningAlgValuesSupported(v []string) {
	o.IdTokenSigningAlgValuesSupported = v
}

// GetSpiffeJwksUri returns the SpiffeJwksUri field value if set, zero value otherwise.
func (o *OpenIDConfiguration) GetSpiffeJwksUri() string {
	if o == nil || IsNil(o.SpiffeJwksUri) {
		var ret string
		return ret
	}
	return *o.SpiffeJwksUri
}

// GetSpiffeJwksUriOk returns a tuple with the SpiffeJwksUri field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OpenIDConfiguration) GetSpiffeJwksUriOk() (*string, bool) {
	if o == nil || IsNil(o.SpiffeJwksUri) {
		return nil, false
	}
	return o.SpiffeJwksUri, true
}

// HasSpiffeJwksUri returns a boolean if a field has been set.
func (o *OpenIDConfiguration) HasSpiffeJwksUri() bool {
	if o != nil && !IsNil(o.SpiffeJwksUri) {
		return true
	}

	return false
}

// SetSpiffeJwksUri gets a reference to the given string and assigns it to the SpiffeJwksUri field.
func (o *OpenIDConfiguration) SetSpiffeJwksUri(v string) {
	o.SpiffeJwksUri = &v
}

func (o OpenIDConfiguration) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o OpenIDConfiguration) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Issuer) {
		toSerialize["issuer"] = o.Issuer
	}
	if !IsNil(o.JwksUri) {
		toSerialize["jwks_uri"] = o.JwksUri
	}
	if !IsNil(o.ResponseTypesSupported) {
		toSerialize["response_types_supported"] = o.ResponseTypesSupported
	}
	if !IsNil(o.SubjectTypesSupported) {
		toSerialize["subject_types_supported"] = o.SubjectTypesSupported
	}
	if !IsNil(o.IdTokenSigningAlgValuesSupported) {
		toSerialize["id_token_signing_alg_values_supported"] = o.IdTokenSigningAlgValuesSupported
	}
	if !IsNil(o.SpiffeJwksUri) {
		toSerialize["spiffe_jwks_uri"] = o.SpiffeJwksUri
	}
	return toSerialize, nil
}

type NullableOpenIDConfiguration struct {
	value *OpenIDConfiguration
	isSet bool
}

func (v NullableOpenIDConfiguration) Get() *OpenIDConfiguration {
	return v.value
}

func (v *NullableOpenIDConfiguration) Set(val *OpenIDConfiguration) {
	v.value = val
	v.isSet = true
}

func (v NullableOpenIDConfiguration) IsSet() bool {
	return v.isSet
}

func (v *NullableOpenIDConfiguration) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOpenIDConfiguration(val *OpenIDConfiguration) *NullableOpenIDConfiguration {
	return &NullableOpenIDConfiguration{value: val, isSet: true}
}

func (v NullableOpenIDConfiguration) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOpenIDConfiguration) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
