// SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

/*
NVIDIA Infra Controller REST API

NVIDIA Infra Controller REST API allows users to create and manage resources, e.g., VPCs, Subnets, and Instances, across all connected NVIDIA Infra Controller datacenters, also referred to as Sites.

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package standard

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the TaskRunOperation type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TaskRunOperation{}

// TaskRunOperation The operation the Task Run executes. Firmware is the only supported operation.
type TaskRunOperation struct {
	Firmware TaskRunFirmwareOperation `json:"firmware"`
	// Excludes Racks materialized by prior Task Runs from this Task Run's candidate scope.
	ExcludeRunIds []string `json:"excludeRunIds,omitempty"`
}

type _TaskRunOperation TaskRunOperation

// NewTaskRunOperation instantiates a new TaskRunOperation object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTaskRunOperation(firmware TaskRunFirmwareOperation) *TaskRunOperation {
	this := TaskRunOperation{}
	this.Firmware = firmware
	return &this
}

// NewTaskRunOperationWithDefaults instantiates a new TaskRunOperation object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTaskRunOperationWithDefaults() *TaskRunOperation {
	this := TaskRunOperation{}
	return &this
}

// GetFirmware returns the Firmware field value
func (o *TaskRunOperation) GetFirmware() TaskRunFirmwareOperation {
	if o == nil {
		var ret TaskRunFirmwareOperation
		return ret
	}

	return o.Firmware
}

// GetFirmwareOk returns a tuple with the Firmware field value
// and a boolean to check if the value has been set.
func (o *TaskRunOperation) GetFirmwareOk() (*TaskRunFirmwareOperation, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Firmware, true
}

// SetFirmware sets field value
func (o *TaskRunOperation) SetFirmware(v TaskRunFirmwareOperation) {
	o.Firmware = v
}

// GetExcludeRunIds returns the ExcludeRunIds field value if set, zero value otherwise.
func (o *TaskRunOperation) GetExcludeRunIds() []string {
	if o == nil || IsNil(o.ExcludeRunIds) {
		var ret []string
		return ret
	}
	return o.ExcludeRunIds
}

// GetExcludeRunIdsOk returns a tuple with the ExcludeRunIds field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TaskRunOperation) GetExcludeRunIdsOk() ([]string, bool) {
	if o == nil || IsNil(o.ExcludeRunIds) {
		return nil, false
	}
	return o.ExcludeRunIds, true
}

// HasExcludeRunIds returns a boolean if a field has been set.
func (o *TaskRunOperation) HasExcludeRunIds() bool {
	if o != nil && !IsNil(o.ExcludeRunIds) {
		return true
	}

	return false
}

// SetExcludeRunIds gets a reference to the given []string and assigns it to the ExcludeRunIds field.
func (o *TaskRunOperation) SetExcludeRunIds(v []string) {
	o.ExcludeRunIds = v
}

func (o TaskRunOperation) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TaskRunOperation) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["firmware"] = o.Firmware
	if !IsNil(o.ExcludeRunIds) {
		toSerialize["excludeRunIds"] = o.ExcludeRunIds
	}
	return toSerialize, nil
}

func (o *TaskRunOperation) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"firmware",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if value, exists := allProperties[requiredProperty]; !exists || value == nil {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varTaskRunOperation := _TaskRunOperation{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	err = decoder.Decode(&varTaskRunOperation)

	if err != nil {
		return err
	}

	*o = TaskRunOperation(varTaskRunOperation)

	return err
}

type NullableTaskRunOperation struct {
	value *TaskRunOperation
	isSet bool
}

func (v NullableTaskRunOperation) Get() *TaskRunOperation {
	return v.value
}

func (v *NullableTaskRunOperation) Set(val *TaskRunOperation) {
	v.value = val
	v.isSet = true
}

func (v NullableTaskRunOperation) IsSet() bool {
	return v.isSet
}

func (v *NullableTaskRunOperation) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTaskRunOperation(val *TaskRunOperation) *NullableTaskRunOperation {
	return &NullableTaskRunOperation{value: val, isSet: true}
}

func (v NullableTaskRunOperation) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTaskRunOperation) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
