// SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

/*
NVIDIA Infra Controller REST API

NVIDIA Infra Controller REST API allows users to create and manage resources, e.g., VPCs, Subnets, and Instances, across all connected NVIDIA Infra Controller datacenters, also referred to as Sites.

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package standard

import (
	"encoding/json"
)

// checks if the PerComponentFirmwareAuthenticationData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PerComponentFirmwareAuthenticationData{}

// PerComponentFirmwareAuthenticationData Authentication data scoped to supported firmware tray types. An omitted field means that tray type receives no authentication data.
type PerComponentFirmwareAuthenticationData struct {
	// Authentication data for compute tray firmware downloads.
	Compute *string `json:"compute,omitempty"`
	// Authentication data for NVSwitch tray firmware downloads.
	Nvswitch *string `json:"nvswitch,omitempty"`
	// Authentication data for power shelf firmware downloads.
	Powershelf *string `json:"powershelf,omitempty"`
}

// NewPerComponentFirmwareAuthenticationData instantiates a new PerComponentFirmwareAuthenticationData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPerComponentFirmwareAuthenticationData() *PerComponentFirmwareAuthenticationData {
	this := PerComponentFirmwareAuthenticationData{}
	return &this
}

// NewPerComponentFirmwareAuthenticationDataWithDefaults instantiates a new PerComponentFirmwareAuthenticationData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPerComponentFirmwareAuthenticationDataWithDefaults() *PerComponentFirmwareAuthenticationData {
	this := PerComponentFirmwareAuthenticationData{}
	return &this
}

// GetCompute returns the Compute field value if set, zero value otherwise.
func (o *PerComponentFirmwareAuthenticationData) GetCompute() string {
	if o == nil || IsNil(o.Compute) {
		var ret string
		return ret
	}
	return *o.Compute
}

// GetComputeOk returns a tuple with the Compute field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PerComponentFirmwareAuthenticationData) GetComputeOk() (*string, bool) {
	if o == nil || IsNil(o.Compute) {
		return nil, false
	}
	return o.Compute, true
}

// HasCompute returns a boolean if a field has been set.
func (o *PerComponentFirmwareAuthenticationData) HasCompute() bool {
	if o != nil && !IsNil(o.Compute) {
		return true
	}

	return false
}

// SetCompute gets a reference to the given string and assigns it to the Compute field.
func (o *PerComponentFirmwareAuthenticationData) SetCompute(v string) {
	o.Compute = &v
}

// GetNvswitch returns the Nvswitch field value if set, zero value otherwise.
func (o *PerComponentFirmwareAuthenticationData) GetNvswitch() string {
	if o == nil || IsNil(o.Nvswitch) {
		var ret string
		return ret
	}
	return *o.Nvswitch
}

// GetNvswitchOk returns a tuple with the Nvswitch field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PerComponentFirmwareAuthenticationData) GetNvswitchOk() (*string, bool) {
	if o == nil || IsNil(o.Nvswitch) {
		return nil, false
	}
	return o.Nvswitch, true
}

// HasNvswitch returns a boolean if a field has been set.
func (o *PerComponentFirmwareAuthenticationData) HasNvswitch() bool {
	if o != nil && !IsNil(o.Nvswitch) {
		return true
	}

	return false
}

// SetNvswitch gets a reference to the given string and assigns it to the Nvswitch field.
func (o *PerComponentFirmwareAuthenticationData) SetNvswitch(v string) {
	o.Nvswitch = &v
}

// GetPowershelf returns the Powershelf field value if set, zero value otherwise.
func (o *PerComponentFirmwareAuthenticationData) GetPowershelf() string {
	if o == nil || IsNil(o.Powershelf) {
		var ret string
		return ret
	}
	return *o.Powershelf
}

// GetPowershelfOk returns a tuple with the Powershelf field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PerComponentFirmwareAuthenticationData) GetPowershelfOk() (*string, bool) {
	if o == nil || IsNil(o.Powershelf) {
		return nil, false
	}
	return o.Powershelf, true
}

// HasPowershelf returns a boolean if a field has been set.
func (o *PerComponentFirmwareAuthenticationData) HasPowershelf() bool {
	if o != nil && !IsNil(o.Powershelf) {
		return true
	}

	return false
}

// SetPowershelf gets a reference to the given string and assigns it to the Powershelf field.
func (o *PerComponentFirmwareAuthenticationData) SetPowershelf(v string) {
	o.Powershelf = &v
}

func (o PerComponentFirmwareAuthenticationData) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PerComponentFirmwareAuthenticationData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Compute) {
		toSerialize["compute"] = o.Compute
	}
	if !IsNil(o.Nvswitch) {
		toSerialize["nvswitch"] = o.Nvswitch
	}
	if !IsNil(o.Powershelf) {
		toSerialize["powershelf"] = o.Powershelf
	}
	return toSerialize, nil
}

type NullablePerComponentFirmwareAuthenticationData struct {
	value *PerComponentFirmwareAuthenticationData
	isSet bool
}

func (v NullablePerComponentFirmwareAuthenticationData) Get() *PerComponentFirmwareAuthenticationData {
	return v.value
}

func (v *NullablePerComponentFirmwareAuthenticationData) Set(val *PerComponentFirmwareAuthenticationData) {
	v.value = val
	v.isSet = true
}

func (v NullablePerComponentFirmwareAuthenticationData) IsSet() bool {
	return v.isSet
}

func (v *NullablePerComponentFirmwareAuthenticationData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePerComponentFirmwareAuthenticationData(val *PerComponentFirmwareAuthenticationData) *NullablePerComponentFirmwareAuthenticationData {
	return &NullablePerComponentFirmwareAuthenticationData{value: val, isSet: true}
}

func (v NullablePerComponentFirmwareAuthenticationData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePerComponentFirmwareAuthenticationData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
