// SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

/*
NVIDIA Infra Controller REST API

NVIDIA Infra Controller REST API allows users to create and manage resources e.g. VPC, Subnets, Instances across all connected NVIDIA Infra Controller datacenters, also referred to as Sites.

API version: 1.6.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package standard

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the VpcPrefixCreateRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &VpcPrefixCreateRequest{}

// VpcPrefixCreateRequest Request data for creating VPC Prefix
type VpcPrefixCreateRequest struct {
	// Human readable name for the VPC Prefix
	Name string `json:"name"`
	// ID of the VPC
	VpcId string `json:"vpcId"`
	// ID of the IP Block to allocate the VPC Prefix from
	IpBlockId string `json:"ipBlockId"`
	// Prefix length for the VPC Prefix. Valid range is 8 to 31, and max usable value depends on prefix length of parent IP Block.
	PrefixLength int32 `json:"prefixLength"`
}

type _VpcPrefixCreateRequest VpcPrefixCreateRequest

// NewVpcPrefixCreateRequest instantiates a new VpcPrefixCreateRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewVpcPrefixCreateRequest(name string, vpcId string, ipBlockId string, prefixLength int32) *VpcPrefixCreateRequest {
	this := VpcPrefixCreateRequest{}
	this.Name = name
	this.VpcId = vpcId
	this.IpBlockId = ipBlockId
	this.PrefixLength = prefixLength
	return &this
}

// NewVpcPrefixCreateRequestWithDefaults instantiates a new VpcPrefixCreateRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewVpcPrefixCreateRequestWithDefaults() *VpcPrefixCreateRequest {
	this := VpcPrefixCreateRequest{}
	return &this
}

// GetName returns the Name field value
func (o *VpcPrefixCreateRequest) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *VpcPrefixCreateRequest) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *VpcPrefixCreateRequest) SetName(v string) {
	o.Name = v
}

// GetVpcId returns the VpcId field value
func (o *VpcPrefixCreateRequest) GetVpcId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.VpcId
}

// GetVpcIdOk returns a tuple with the VpcId field value
// and a boolean to check if the value has been set.
func (o *VpcPrefixCreateRequest) GetVpcIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.VpcId, true
}

// SetVpcId sets field value
func (o *VpcPrefixCreateRequest) SetVpcId(v string) {
	o.VpcId = v
}

// GetIpBlockId returns the IpBlockId field value
func (o *VpcPrefixCreateRequest) GetIpBlockId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.IpBlockId
}

// GetIpBlockIdOk returns a tuple with the IpBlockId field value
// and a boolean to check if the value has been set.
func (o *VpcPrefixCreateRequest) GetIpBlockIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IpBlockId, true
}

// SetIpBlockId sets field value
func (o *VpcPrefixCreateRequest) SetIpBlockId(v string) {
	o.IpBlockId = v
}

// GetPrefixLength returns the PrefixLength field value
func (o *VpcPrefixCreateRequest) GetPrefixLength() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.PrefixLength
}

// GetPrefixLengthOk returns a tuple with the PrefixLength field value
// and a boolean to check if the value has been set.
func (o *VpcPrefixCreateRequest) GetPrefixLengthOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PrefixLength, true
}

// SetPrefixLength sets field value
func (o *VpcPrefixCreateRequest) SetPrefixLength(v int32) {
	o.PrefixLength = v
}

func (o VpcPrefixCreateRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o VpcPrefixCreateRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	toSerialize["vpcId"] = o.VpcId
	toSerialize["ipBlockId"] = o.IpBlockId
	toSerialize["prefixLength"] = o.PrefixLength
	return toSerialize, nil
}

func (o *VpcPrefixCreateRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
		"vpcId",
		"ipBlockId",
		"prefixLength",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varVpcPrefixCreateRequest := _VpcPrefixCreateRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varVpcPrefixCreateRequest)

	if err != nil {
		return err
	}

	*o = VpcPrefixCreateRequest(varVpcPrefixCreateRequest)

	return err
}

type NullableVpcPrefixCreateRequest struct {
	value *VpcPrefixCreateRequest
	isSet bool
}

func (v NullableVpcPrefixCreateRequest) Get() *VpcPrefixCreateRequest {
	return v.value
}

func (v *NullableVpcPrefixCreateRequest) Set(val *VpcPrefixCreateRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableVpcPrefixCreateRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableVpcPrefixCreateRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableVpcPrefixCreateRequest(val *VpcPrefixCreateRequest) *NullableVpcPrefixCreateRequest {
	return &NullableVpcPrefixCreateRequest{value: val, isSet: true}
}

func (v NullableVpcPrefixCreateRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableVpcPrefixCreateRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
