// SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

/*
NVIDIA Infra Controller REST API

NVIDIA Infra Controller REST API allows users to create and manage resources, e.g., VPCs, Subnets, and Instances, across all connected NVIDIA Infra Controller datacenters, also referred to as Sites.

API version: 1.6.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package standard

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the MachineHealthReportListResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MachineHealthReportListResponse{}

// MachineHealthReportListResponse Machine health report entries returned by NICo Core.
type MachineHealthReportListResponse struct {
	// ID of the Machine.
	MachineId           string                     `json:"machineId"`
	HealthReportEntries []MachineHealthReportEntry `json:"healthReportEntries"`
}

type _MachineHealthReportListResponse MachineHealthReportListResponse

// NewMachineHealthReportListResponse instantiates a new MachineHealthReportListResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMachineHealthReportListResponse(machineId string, healthReportEntries []MachineHealthReportEntry) *MachineHealthReportListResponse {
	this := MachineHealthReportListResponse{}
	this.MachineId = machineId
	this.HealthReportEntries = healthReportEntries
	return &this
}

// NewMachineHealthReportListResponseWithDefaults instantiates a new MachineHealthReportListResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMachineHealthReportListResponseWithDefaults() *MachineHealthReportListResponse {
	this := MachineHealthReportListResponse{}
	return &this
}

// GetMachineId returns the MachineId field value
func (o *MachineHealthReportListResponse) GetMachineId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.MachineId
}

// GetMachineIdOk returns a tuple with the MachineId field value
// and a boolean to check if the value has been set.
func (o *MachineHealthReportListResponse) GetMachineIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MachineId, true
}

// SetMachineId sets field value
func (o *MachineHealthReportListResponse) SetMachineId(v string) {
	o.MachineId = v
}

// GetHealthReportEntries returns the HealthReportEntries field value
func (o *MachineHealthReportListResponse) GetHealthReportEntries() []MachineHealthReportEntry {
	if o == nil {
		var ret []MachineHealthReportEntry
		return ret
	}

	return o.HealthReportEntries
}

// GetHealthReportEntriesOk returns a tuple with the HealthReportEntries field value
// and a boolean to check if the value has been set.
func (o *MachineHealthReportListResponse) GetHealthReportEntriesOk() ([]MachineHealthReportEntry, bool) {
	if o == nil {
		return nil, false
	}
	return o.HealthReportEntries, true
}

// SetHealthReportEntries sets field value
func (o *MachineHealthReportListResponse) SetHealthReportEntries(v []MachineHealthReportEntry) {
	o.HealthReportEntries = v
}

func (o MachineHealthReportListResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MachineHealthReportListResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["machineId"] = o.MachineId
	toSerialize["healthReportEntries"] = o.HealthReportEntries
	return toSerialize, nil
}

func (o *MachineHealthReportListResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"machineId",
		"healthReportEntries",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varMachineHealthReportListResponse := _MachineHealthReportListResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varMachineHealthReportListResponse)

	if err != nil {
		return err
	}

	*o = MachineHealthReportListResponse(varMachineHealthReportListResponse)

	return err
}

type NullableMachineHealthReportListResponse struct {
	value *MachineHealthReportListResponse
	isSet bool
}

func (v NullableMachineHealthReportListResponse) Get() *MachineHealthReportListResponse {
	return v.value
}

func (v *NullableMachineHealthReportListResponse) Set(val *MachineHealthReportListResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableMachineHealthReportListResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableMachineHealthReportListResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMachineHealthReportListResponse(val *MachineHealthReportListResponse) *NullableMachineHealthReportListResponse {
	return &NullableMachineHealthReportListResponse{value: val, isSet: true}
}

func (v NullableMachineHealthReportListResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMachineHealthReportListResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
