// SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

/*
NVIDIA Infra Controller REST API

NVIDIA Infra Controller REST API allows users to create and manage resources e.g. VPC, Subnets, Instances across all connected NVIDIA Infra Controller datacenters, also referred to as Sites.

API version: 1.6.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package standard

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the TenantIdentityJWKS type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TenantIdentityJWKS{}

// TenantIdentityJWKS RFC 7517 JSON Web Key Set. NICo-rest returns this schema only on `200 OK`; in that case the `keys` member is present. The Core gRPC API normally returns one key, or two during a rotation overlap window. When no identity configuration exists for the org/site, the JWKS endpoints return `404 Not Found`.
type TenantIdentityJWKS struct {
	// RFC 7517 JWK members. NICo currently emits only EC keys (`kty: EC`, `crv: P-256`, `alg: ES256`); the schema is intentionally open-ended so that future algorithms can be added without a spec change.
	Keys []TenantIdentityJWKSKeysInner `json:"keys"`
}

type _TenantIdentityJWKS TenantIdentityJWKS

// NewTenantIdentityJWKS instantiates a new TenantIdentityJWKS object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTenantIdentityJWKS(keys []TenantIdentityJWKSKeysInner) *TenantIdentityJWKS {
	this := TenantIdentityJWKS{}
	this.Keys = keys
	return &this
}

// NewTenantIdentityJWKSWithDefaults instantiates a new TenantIdentityJWKS object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTenantIdentityJWKSWithDefaults() *TenantIdentityJWKS {
	this := TenantIdentityJWKS{}
	return &this
}

// GetKeys returns the Keys field value
func (o *TenantIdentityJWKS) GetKeys() []TenantIdentityJWKSKeysInner {
	if o == nil {
		var ret []TenantIdentityJWKSKeysInner
		return ret
	}

	return o.Keys
}

// GetKeysOk returns a tuple with the Keys field value
// and a boolean to check if the value has been set.
func (o *TenantIdentityJWKS) GetKeysOk() ([]TenantIdentityJWKSKeysInner, bool) {
	if o == nil {
		return nil, false
	}
	return o.Keys, true
}

// SetKeys sets field value
func (o *TenantIdentityJWKS) SetKeys(v []TenantIdentityJWKSKeysInner) {
	o.Keys = v
}

func (o TenantIdentityJWKS) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TenantIdentityJWKS) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["keys"] = o.Keys
	return toSerialize, nil
}

func (o *TenantIdentityJWKS) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"keys",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varTenantIdentityJWKS := _TenantIdentityJWKS{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varTenantIdentityJWKS)

	if err != nil {
		return err
	}

	*o = TenantIdentityJWKS(varTenantIdentityJWKS)

	return err
}

type NullableTenantIdentityJWKS struct {
	value *TenantIdentityJWKS
	isSet bool
}

func (v NullableTenantIdentityJWKS) Get() *TenantIdentityJWKS {
	return v.value
}

func (v *NullableTenantIdentityJWKS) Set(val *TenantIdentityJWKS) {
	v.value = val
	v.isSet = true
}

func (v NullableTenantIdentityJWKS) IsSet() bool {
	return v.isSet
}

func (v *NullableTenantIdentityJWKS) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTenantIdentityJWKS(val *TenantIdentityJWKS) *NullableTenantIdentityJWKS {
	return &NullableTenantIdentityJWKS{value: val, isSet: true}
}

func (v NullableTenantIdentityJWKS) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTenantIdentityJWKS) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
