// SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

/*
NVIDIA Infra Controller REST API

NVIDIA Infra Controller REST API allows users to create and manage resources, e.g., VPCs, Subnets, and Instances, across all connected NVIDIA Infra Controller datacenters, also referred to as Sites.

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package standard

import (
	"encoding/json"
)

// checks if the SkuTpm type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SkuTpm{}

// SkuTpm TPM component in a SKU
type SkuTpm struct {
	// Vendor of the TPM
	Vendor *string `json:"vendor,omitempty"`
	// Version of the TPM
	Version *string `json:"version,omitempty"`
}

// NewSkuTpm instantiates a new SkuTpm object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSkuTpm() *SkuTpm {
	this := SkuTpm{}
	return &this
}

// NewSkuTpmWithDefaults instantiates a new SkuTpm object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSkuTpmWithDefaults() *SkuTpm {
	this := SkuTpm{}
	return &this
}

// GetVendor returns the Vendor field value if set, zero value otherwise.
func (o *SkuTpm) GetVendor() string {
	if o == nil || IsNil(o.Vendor) {
		var ret string
		return ret
	}
	return *o.Vendor
}

// GetVendorOk returns a tuple with the Vendor field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SkuTpm) GetVendorOk() (*string, bool) {
	if o == nil || IsNil(o.Vendor) {
		return nil, false
	}
	return o.Vendor, true
}

// HasVendor returns a boolean if a field has been set.
func (o *SkuTpm) HasVendor() bool {
	if o != nil && !IsNil(o.Vendor) {
		return true
	}

	return false
}

// SetVendor gets a reference to the given string and assigns it to the Vendor field.
func (o *SkuTpm) SetVendor(v string) {
	o.Vendor = &v
}

// GetVersion returns the Version field value if set, zero value otherwise.
func (o *SkuTpm) GetVersion() string {
	if o == nil || IsNil(o.Version) {
		var ret string
		return ret
	}
	return *o.Version
}

// GetVersionOk returns a tuple with the Version field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SkuTpm) GetVersionOk() (*string, bool) {
	if o == nil || IsNil(o.Version) {
		return nil, false
	}
	return o.Version, true
}

// HasVersion returns a boolean if a field has been set.
func (o *SkuTpm) HasVersion() bool {
	if o != nil && !IsNil(o.Version) {
		return true
	}

	return false
}

// SetVersion gets a reference to the given string and assigns it to the Version field.
func (o *SkuTpm) SetVersion(v string) {
	o.Version = &v
}

func (o SkuTpm) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SkuTpm) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Vendor) {
		toSerialize["vendor"] = o.Vendor
	}
	if !IsNil(o.Version) {
		toSerialize["version"] = o.Version
	}
	return toSerialize, nil
}

type NullableSkuTpm struct {
	value *SkuTpm
	isSet bool
}

func (v NullableSkuTpm) Get() *SkuTpm {
	return v.value
}

func (v *NullableSkuTpm) Set(val *SkuTpm) {
	v.value = val
	v.isSet = true
}

func (v NullableSkuTpm) IsSet() bool {
	return v.isSet
}

func (v *NullableSkuTpm) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSkuTpm(val *SkuTpm) *NullableSkuTpm {
	return &NullableSkuTpm{value: val, isSet: true}
}

func (v NullableSkuTpm) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSkuTpm) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
