// SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

/*
NVIDIA Infra Controller REST API

NVIDIA Infra Controller REST API allows users to create and manage resources e.g. VPC, Subnets, Instances across all connected NVIDIA Infra Controller datacenters, also referred to as Sites.

API version: 1.6.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package standard

import (
	"encoding/json"
	"fmt"
)

// NVLinkInterfaceStatus Status values for NVLink Interface objects
type NVLinkInterfaceStatus string

// List of NVLinkInterfaceStatus
const (
	NVLINKINTERFACESTATUS_PENDING      NVLinkInterfaceStatus = "Pending"
	NVLINKINTERFACESTATUS_PROVISIONING NVLinkInterfaceStatus = "Provisioning"
	NVLINKINTERFACESTATUS_READY        NVLinkInterfaceStatus = "Ready"
	NVLINKINTERFACESTATUS_DELETING     NVLinkInterfaceStatus = "Deleting"
	NVLINKINTERFACESTATUS_ERROR        NVLinkInterfaceStatus = "Error"
)

// All allowed values of NVLinkInterfaceStatus enum
var AllowedNVLinkInterfaceStatusEnumValues = []NVLinkInterfaceStatus{
	"Pending",
	"Provisioning",
	"Ready",
	"Deleting",
	"Error",
}

func (v *NVLinkInterfaceStatus) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := NVLinkInterfaceStatus(value)
	for _, existing := range AllowedNVLinkInterfaceStatusEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid NVLinkInterfaceStatus", value)
}

// NewNVLinkInterfaceStatusFromValue returns a pointer to a valid NVLinkInterfaceStatus
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewNVLinkInterfaceStatusFromValue(v string) (*NVLinkInterfaceStatus, error) {
	ev := NVLinkInterfaceStatus(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for NVLinkInterfaceStatus: valid values are %v", v, AllowedNVLinkInterfaceStatusEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v NVLinkInterfaceStatus) IsValid() bool {
	for _, existing := range AllowedNVLinkInterfaceStatusEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to NVLinkInterfaceStatus value
func (v NVLinkInterfaceStatus) Ptr() *NVLinkInterfaceStatus {
	return &v
}

type NullableNVLinkInterfaceStatus struct {
	value *NVLinkInterfaceStatus
	isSet bool
}

func (v NullableNVLinkInterfaceStatus) Get() *NVLinkInterfaceStatus {
	return v.value
}

func (v *NullableNVLinkInterfaceStatus) Set(val *NVLinkInterfaceStatus) {
	v.value = val
	v.isSet = true
}

func (v NullableNVLinkInterfaceStatus) IsSet() bool {
	return v.isSet
}

func (v *NullableNVLinkInterfaceStatus) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableNVLinkInterfaceStatus(val *NVLinkInterfaceStatus) *NullableNVLinkInterfaceStatus {
	return &NullableNVLinkInterfaceStatus{value: val, isSet: true}
}

func (v NullableNVLinkInterfaceStatus) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableNVLinkInterfaceStatus) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
