// SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

/*
NVIDIA Infra Controller REST API

NVIDIA Infra Controller REST API allows users to create and manage resources e.g. VPC, Subnets, Instances across all connected NVIDIA Infra Controller datacenters, also referred to as Sites.

API version: 1.6.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package standard

import (
	"encoding/json"
)

// checks if the InfrastructureProviderStats type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &InfrastructureProviderStats{}

// InfrastructureProviderStats Provide operational stats for Infrastructure Provider
type InfrastructureProviderStats struct {
	Machine       *MachineCountByStatus       `json:"machine,omitempty"`
	IpBlock       *IpBlockCountByStatus       `json:"ipBlock,omitempty"`
	TenantAccount *TenantAccountCountByStatus `json:"tenantAccount,omitempty"`
}

// NewInfrastructureProviderStats instantiates a new InfrastructureProviderStats object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInfrastructureProviderStats() *InfrastructureProviderStats {
	this := InfrastructureProviderStats{}
	return &this
}

// NewInfrastructureProviderStatsWithDefaults instantiates a new InfrastructureProviderStats object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInfrastructureProviderStatsWithDefaults() *InfrastructureProviderStats {
	this := InfrastructureProviderStats{}
	return &this
}

// GetMachine returns the Machine field value if set, zero value otherwise.
func (o *InfrastructureProviderStats) GetMachine() MachineCountByStatus {
	if o == nil || IsNil(o.Machine) {
		var ret MachineCountByStatus
		return ret
	}
	return *o.Machine
}

// GetMachineOk returns a tuple with the Machine field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InfrastructureProviderStats) GetMachineOk() (*MachineCountByStatus, bool) {
	if o == nil || IsNil(o.Machine) {
		return nil, false
	}
	return o.Machine, true
}

// HasMachine returns a boolean if a field has been set.
func (o *InfrastructureProviderStats) HasMachine() bool {
	if o != nil && !IsNil(o.Machine) {
		return true
	}

	return false
}

// SetMachine gets a reference to the given MachineCountByStatus and assigns it to the Machine field.
func (o *InfrastructureProviderStats) SetMachine(v MachineCountByStatus) {
	o.Machine = &v
}

// GetIpBlock returns the IpBlock field value if set, zero value otherwise.
func (o *InfrastructureProviderStats) GetIpBlock() IpBlockCountByStatus {
	if o == nil || IsNil(o.IpBlock) {
		var ret IpBlockCountByStatus
		return ret
	}
	return *o.IpBlock
}

// GetIpBlockOk returns a tuple with the IpBlock field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InfrastructureProviderStats) GetIpBlockOk() (*IpBlockCountByStatus, bool) {
	if o == nil || IsNil(o.IpBlock) {
		return nil, false
	}
	return o.IpBlock, true
}

// HasIpBlock returns a boolean if a field has been set.
func (o *InfrastructureProviderStats) HasIpBlock() bool {
	if o != nil && !IsNil(o.IpBlock) {
		return true
	}

	return false
}

// SetIpBlock gets a reference to the given IpBlockCountByStatus and assigns it to the IpBlock field.
func (o *InfrastructureProviderStats) SetIpBlock(v IpBlockCountByStatus) {
	o.IpBlock = &v
}

// GetTenantAccount returns the TenantAccount field value if set, zero value otherwise.
func (o *InfrastructureProviderStats) GetTenantAccount() TenantAccountCountByStatus {
	if o == nil || IsNil(o.TenantAccount) {
		var ret TenantAccountCountByStatus
		return ret
	}
	return *o.TenantAccount
}

// GetTenantAccountOk returns a tuple with the TenantAccount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InfrastructureProviderStats) GetTenantAccountOk() (*TenantAccountCountByStatus, bool) {
	if o == nil || IsNil(o.TenantAccount) {
		return nil, false
	}
	return o.TenantAccount, true
}

// HasTenantAccount returns a boolean if a field has been set.
func (o *InfrastructureProviderStats) HasTenantAccount() bool {
	if o != nil && !IsNil(o.TenantAccount) {
		return true
	}

	return false
}

// SetTenantAccount gets a reference to the given TenantAccountCountByStatus and assigns it to the TenantAccount field.
func (o *InfrastructureProviderStats) SetTenantAccount(v TenantAccountCountByStatus) {
	o.TenantAccount = &v
}

func (o InfrastructureProviderStats) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o InfrastructureProviderStats) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Machine) {
		toSerialize["machine"] = o.Machine
	}
	if !IsNil(o.IpBlock) {
		toSerialize["ipBlock"] = o.IpBlock
	}
	if !IsNil(o.TenantAccount) {
		toSerialize["tenantAccount"] = o.TenantAccount
	}
	return toSerialize, nil
}

type NullableInfrastructureProviderStats struct {
	value *InfrastructureProviderStats
	isSet bool
}

func (v NullableInfrastructureProviderStats) Get() *InfrastructureProviderStats {
	return v.value
}

func (v *NullableInfrastructureProviderStats) Set(val *InfrastructureProviderStats) {
	v.value = val
	v.isSet = true
}

func (v NullableInfrastructureProviderStats) IsSet() bool {
	return v.isSet
}

func (v *NullableInfrastructureProviderStats) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInfrastructureProviderStats(val *InfrastructureProviderStats) *NullableInfrastructureProviderStats {
	return &NullableInfrastructureProviderStats{value: val, isSet: true}
}

func (v NullableInfrastructureProviderStats) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInfrastructureProviderStats) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
