// SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

/*
NVIDIA Infra Controller REST API

NVIDIA Infra Controller REST API allows users to create and manage resources, e.g., VPCs, Subnets, and Instances, across all connected NVIDIA Infra Controller datacenters, also referred to as Sites.

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package standard

import (
	"bytes"
	"encoding/json"
	"fmt"
	"time"
)

// checks if the DpuMachineSummary type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DpuMachineSummary{}

// DpuMachineSummary A DPU Machine returned by a site-scoped DPU lookup. Network configuration is null unless the endpoint supports and receives an explicit request for it.
type DpuMachineSummary struct {
	// ID of the DPU Machine
	Id string `json:"id"`
	// ID of the Infrastructure Provider that owns the host Machine
	InfrastructureProviderId string `json:"infrastructureProviderId"`
	// ID of the Site that the host Machine belongs to
	SiteId string `json:"siteId"`
	// ID of the host Machine that this DPU is attached to
	HostMachineId string `json:"hostMachineId"`
	// Version of the DPU agent running on the DPU
	DpuAgentVersion string `json:"dpuAgentVersion"`
	// BMC (Baseboard Management Controller) information for the DPU
	BmcInfo NullableMachineBMCInfo `json:"bmcInfo"`
	// DMI (Desktop Management Interface) data reported for the DPU
	DmiData NullableMachineDMIData `json:"dmiData"`
	// Interfaces reported on the DPU
	Interfaces []DpuMachineInterface `json:"interfaces"`
	// Software components reported on the DPU
	SoftwareComponents []DpuMachineSoftwareComponent `json:"softwareComponents"`
	// Health information for the DPU
	Health NullableMachineHealth `json:"health"`
	// Labels associated with the DPU
	Labels map[string]string `json:"labels"`
	// Lifecycle state of the DPU
	State string `json:"state"`
	// Network configuration fields exposed by the REST API, or null when not requested or unavailable
	DpuNetworkConfig NullableDpuNetworkConfig `json:"dpuNetworkConfig"`
	// Last reboot timestamp
	LastRebooted NullableTime `json:"lastRebooted"`
	// Physical placement of the DPU Machine within its Rack, when known
	PlacementInRack NullablePlacementInRack `json:"placementInRack"`
}

type _DpuMachineSummary DpuMachineSummary

// NewDpuMachineSummary instantiates a new DpuMachineSummary object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDpuMachineSummary(id string, infrastructureProviderId string, siteId string, hostMachineId string, dpuAgentVersion string, bmcInfo NullableMachineBMCInfo, dmiData NullableMachineDMIData, interfaces []DpuMachineInterface, softwareComponents []DpuMachineSoftwareComponent, health NullableMachineHealth, labels map[string]string, state string, dpuNetworkConfig NullableDpuNetworkConfig, lastRebooted NullableTime, placementInRack NullablePlacementInRack) *DpuMachineSummary {
	this := DpuMachineSummary{}
	this.Id = id
	this.InfrastructureProviderId = infrastructureProviderId
	this.SiteId = siteId
	this.HostMachineId = hostMachineId
	this.DpuAgentVersion = dpuAgentVersion
	this.BmcInfo = bmcInfo
	this.DmiData = dmiData
	this.Interfaces = interfaces
	this.SoftwareComponents = softwareComponents
	this.Health = health
	this.Labels = labels
	this.State = state
	this.DpuNetworkConfig = dpuNetworkConfig
	this.LastRebooted = lastRebooted
	this.PlacementInRack = placementInRack
	return &this
}

// NewDpuMachineSummaryWithDefaults instantiates a new DpuMachineSummary object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDpuMachineSummaryWithDefaults() *DpuMachineSummary {
	this := DpuMachineSummary{}
	return &this
}

// GetId returns the Id field value
func (o *DpuMachineSummary) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *DpuMachineSummary) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *DpuMachineSummary) SetId(v string) {
	o.Id = v
}

// GetInfrastructureProviderId returns the InfrastructureProviderId field value
func (o *DpuMachineSummary) GetInfrastructureProviderId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.InfrastructureProviderId
}

// GetInfrastructureProviderIdOk returns a tuple with the InfrastructureProviderId field value
// and a boolean to check if the value has been set.
func (o *DpuMachineSummary) GetInfrastructureProviderIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.InfrastructureProviderId, true
}

// SetInfrastructureProviderId sets field value
func (o *DpuMachineSummary) SetInfrastructureProviderId(v string) {
	o.InfrastructureProviderId = v
}

// GetSiteId returns the SiteId field value
func (o *DpuMachineSummary) GetSiteId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SiteId
}

// GetSiteIdOk returns a tuple with the SiteId field value
// and a boolean to check if the value has been set.
func (o *DpuMachineSummary) GetSiteIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SiteId, true
}

// SetSiteId sets field value
func (o *DpuMachineSummary) SetSiteId(v string) {
	o.SiteId = v
}

// GetHostMachineId returns the HostMachineId field value
func (o *DpuMachineSummary) GetHostMachineId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.HostMachineId
}

// GetHostMachineIdOk returns a tuple with the HostMachineId field value
// and a boolean to check if the value has been set.
func (o *DpuMachineSummary) GetHostMachineIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.HostMachineId, true
}

// SetHostMachineId sets field value
func (o *DpuMachineSummary) SetHostMachineId(v string) {
	o.HostMachineId = v
}

// GetDpuAgentVersion returns the DpuAgentVersion field value
func (o *DpuMachineSummary) GetDpuAgentVersion() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.DpuAgentVersion
}

// GetDpuAgentVersionOk returns a tuple with the DpuAgentVersion field value
// and a boolean to check if the value has been set.
func (o *DpuMachineSummary) GetDpuAgentVersionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DpuAgentVersion, true
}

// SetDpuAgentVersion sets field value
func (o *DpuMachineSummary) SetDpuAgentVersion(v string) {
	o.DpuAgentVersion = v
}

// GetBmcInfo returns the BmcInfo field value
// If the value is explicit nil, the zero value for MachineBMCInfo will be returned
func (o *DpuMachineSummary) GetBmcInfo() MachineBMCInfo {
	if o == nil || o.BmcInfo.Get() == nil {
		var ret MachineBMCInfo
		return ret
	}

	return *o.BmcInfo.Get()
}

// GetBmcInfoOk returns a tuple with the BmcInfo field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *DpuMachineSummary) GetBmcInfoOk() (*MachineBMCInfo, bool) {
	if o == nil {
		return nil, false
	}
	return o.BmcInfo.Get(), o.BmcInfo.IsSet()
}

// SetBmcInfo sets field value
func (o *DpuMachineSummary) SetBmcInfo(v MachineBMCInfo) {
	o.BmcInfo.Set(&v)
}

// GetDmiData returns the DmiData field value
// If the value is explicit nil, the zero value for MachineDMIData will be returned
func (o *DpuMachineSummary) GetDmiData() MachineDMIData {
	if o == nil || o.DmiData.Get() == nil {
		var ret MachineDMIData
		return ret
	}

	return *o.DmiData.Get()
}

// GetDmiDataOk returns a tuple with the DmiData field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *DpuMachineSummary) GetDmiDataOk() (*MachineDMIData, bool) {
	if o == nil {
		return nil, false
	}
	return o.DmiData.Get(), o.DmiData.IsSet()
}

// SetDmiData sets field value
func (o *DpuMachineSummary) SetDmiData(v MachineDMIData) {
	o.DmiData.Set(&v)
}

// GetInterfaces returns the Interfaces field value
// If the value is explicit nil, the zero value for []DpuMachineInterface will be returned
func (o *DpuMachineSummary) GetInterfaces() []DpuMachineInterface {
	if o == nil {
		var ret []DpuMachineInterface
		return ret
	}

	return o.Interfaces
}

// GetInterfacesOk returns a tuple with the Interfaces field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *DpuMachineSummary) GetInterfacesOk() ([]DpuMachineInterface, bool) {
	if o == nil || IsNil(o.Interfaces) {
		return nil, false
	}
	return o.Interfaces, true
}

// SetInterfaces sets field value
func (o *DpuMachineSummary) SetInterfaces(v []DpuMachineInterface) {
	o.Interfaces = v
}

// GetSoftwareComponents returns the SoftwareComponents field value
// If the value is explicit nil, the zero value for []DpuMachineSoftwareComponent will be returned
func (o *DpuMachineSummary) GetSoftwareComponents() []DpuMachineSoftwareComponent {
	if o == nil {
		var ret []DpuMachineSoftwareComponent
		return ret
	}

	return o.SoftwareComponents
}

// GetSoftwareComponentsOk returns a tuple with the SoftwareComponents field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *DpuMachineSummary) GetSoftwareComponentsOk() ([]DpuMachineSoftwareComponent, bool) {
	if o == nil || IsNil(o.SoftwareComponents) {
		return nil, false
	}
	return o.SoftwareComponents, true
}

// SetSoftwareComponents sets field value
func (o *DpuMachineSummary) SetSoftwareComponents(v []DpuMachineSoftwareComponent) {
	o.SoftwareComponents = v
}

// GetHealth returns the Health field value
// If the value is explicit nil, the zero value for MachineHealth will be returned
func (o *DpuMachineSummary) GetHealth() MachineHealth {
	if o == nil || o.Health.Get() == nil {
		var ret MachineHealth
		return ret
	}

	return *o.Health.Get()
}

// GetHealthOk returns a tuple with the Health field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *DpuMachineSummary) GetHealthOk() (*MachineHealth, bool) {
	if o == nil {
		return nil, false
	}
	return o.Health.Get(), o.Health.IsSet()
}

// SetHealth sets field value
func (o *DpuMachineSummary) SetHealth(v MachineHealth) {
	o.Health.Set(&v)
}

// GetLabels returns the Labels field value
func (o *DpuMachineSummary) GetLabels() map[string]string {
	if o == nil {
		var ret map[string]string
		return ret
	}

	return o.Labels
}

// GetLabelsOk returns a tuple with the Labels field value
// and a boolean to check if the value has been set.
func (o *DpuMachineSummary) GetLabelsOk() (map[string]string, bool) {
	if o == nil {
		return map[string]string{}, false
	}
	return o.Labels, true
}

// SetLabels sets field value
func (o *DpuMachineSummary) SetLabels(v map[string]string) {
	o.Labels = v
}

// GetState returns the State field value
func (o *DpuMachineSummary) GetState() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.State
}

// GetStateOk returns a tuple with the State field value
// and a boolean to check if the value has been set.
func (o *DpuMachineSummary) GetStateOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.State, true
}

// SetState sets field value
func (o *DpuMachineSummary) SetState(v string) {
	o.State = v
}

// GetDpuNetworkConfig returns the DpuNetworkConfig field value
// If the value is explicit nil, the zero value for DpuNetworkConfig will be returned
func (o *DpuMachineSummary) GetDpuNetworkConfig() DpuNetworkConfig {
	if o == nil || o.DpuNetworkConfig.Get() == nil {
		var ret DpuNetworkConfig
		return ret
	}

	return *o.DpuNetworkConfig.Get()
}

// GetDpuNetworkConfigOk returns a tuple with the DpuNetworkConfig field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *DpuMachineSummary) GetDpuNetworkConfigOk() (*DpuNetworkConfig, bool) {
	if o == nil {
		return nil, false
	}
	return o.DpuNetworkConfig.Get(), o.DpuNetworkConfig.IsSet()
}

// SetDpuNetworkConfig sets field value
func (o *DpuMachineSummary) SetDpuNetworkConfig(v DpuNetworkConfig) {
	o.DpuNetworkConfig.Set(&v)
}

// GetLastRebooted returns the LastRebooted field value
// If the value is explicit nil, the zero value for time.Time will be returned
func (o *DpuMachineSummary) GetLastRebooted() time.Time {
	if o == nil || o.LastRebooted.Get() == nil {
		var ret time.Time
		return ret
	}

	return *o.LastRebooted.Get()
}

// GetLastRebootedOk returns a tuple with the LastRebooted field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *DpuMachineSummary) GetLastRebootedOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.LastRebooted.Get(), o.LastRebooted.IsSet()
}

// SetLastRebooted sets field value
func (o *DpuMachineSummary) SetLastRebooted(v time.Time) {
	o.LastRebooted.Set(&v)
}

// GetPlacementInRack returns the PlacementInRack field value
// If the value is explicit nil, the zero value for PlacementInRack will be returned
func (o *DpuMachineSummary) GetPlacementInRack() PlacementInRack {
	if o == nil || o.PlacementInRack.Get() == nil {
		var ret PlacementInRack
		return ret
	}

	return *o.PlacementInRack.Get()
}

// GetPlacementInRackOk returns a tuple with the PlacementInRack field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *DpuMachineSummary) GetPlacementInRackOk() (*PlacementInRack, bool) {
	if o == nil {
		return nil, false
	}
	return o.PlacementInRack.Get(), o.PlacementInRack.IsSet()
}

// SetPlacementInRack sets field value
func (o *DpuMachineSummary) SetPlacementInRack(v PlacementInRack) {
	o.PlacementInRack.Set(&v)
}

func (o DpuMachineSummary) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DpuMachineSummary) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["infrastructureProviderId"] = o.InfrastructureProviderId
	toSerialize["siteId"] = o.SiteId
	toSerialize["hostMachineId"] = o.HostMachineId
	toSerialize["dpuAgentVersion"] = o.DpuAgentVersion
	toSerialize["bmcInfo"] = o.BmcInfo.Get()
	toSerialize["dmiData"] = o.DmiData.Get()
	toSerialize["interfaces"] = o.Interfaces
	toSerialize["softwareComponents"] = o.SoftwareComponents
	toSerialize["health"] = o.Health.Get()
	toSerialize["labels"] = o.Labels
	toSerialize["state"] = o.State
	toSerialize["dpuNetworkConfig"] = o.DpuNetworkConfig.Get()
	toSerialize["lastRebooted"] = o.LastRebooted.Get()
	toSerialize["placementInRack"] = o.PlacementInRack.Get()
	return toSerialize, nil
}

func (o *DpuMachineSummary) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"infrastructureProviderId",
		"siteId",
		"hostMachineId",
		"dpuAgentVersion",
		"bmcInfo",
		"dmiData",
		"interfaces",
		"softwareComponents",
		"health",
		"labels",
		"state",
		"dpuNetworkConfig",
		"lastRebooted",
		"placementInRack",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	nullableRequiredProperties := map[string]struct{}{
		"bmcInfo":            {},
		"dmiData":            {},
		"interfaces":         {},
		"softwareComponents": {},
		"health":             {},
		"labels":             {},
		"dpuNetworkConfig":   {},
		"lastRebooted":       {},
		"placementInRack":    {},
	}
	for _, requiredProperty := range requiredProperties {
		_, nullable := nullableRequiredProperties[requiredProperty]
		if value, exists := allProperties[requiredProperty]; !exists || (value == nil && !nullable) {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDpuMachineSummary := _DpuMachineSummary{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	err = decoder.Decode(&varDpuMachineSummary)

	if err != nil {
		return err
	}

	*o = DpuMachineSummary(varDpuMachineSummary)

	return err
}

type NullableDpuMachineSummary struct {
	value *DpuMachineSummary
	isSet bool
}

func (v NullableDpuMachineSummary) Get() *DpuMachineSummary {
	return v.value
}

func (v *NullableDpuMachineSummary) Set(val *DpuMachineSummary) {
	v.value = val
	v.isSet = true
}

func (v NullableDpuMachineSummary) IsSet() bool {
	return v.isSet
}

func (v *NullableDpuMachineSummary) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDpuMachineSummary(val *DpuMachineSummary) *NullableDpuMachineSummary {
	return &NullableDpuMachineSummary{value: val, isSet: true}
}

func (v NullableDpuMachineSummary) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDpuMachineSummary) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
