// SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

/*
NVIDIA Infra Controller REST API

NVIDIA Infra Controller REST API allows users to create and manage resources e.g. VPC, Subnets, Instances across all connected NVIDIA Infra Controller datacenters, also referred to as Sites.

API version: 1.6.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package standard

import (
	"encoding/json"
	"time"
)

// checks if the DpuExtensionService type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DpuExtensionService{}

// DpuExtensionService DPU Extension Service allows user defined services to run on DPUs of their Instances
type DpuExtensionService struct {
	// Unique identifier for the DPU Extension Service
	Id *string `json:"id,omitempty"`
	// Name for the DPU Extension Service. Must be unique for a given Tenant
	Name *string `json:"name,omitempty"`
	// Optional description for the DPU Extension Service
	Description NullableString `json:"description,omitempty"`
	// Type of the DPU Extension Service
	ServiceType *string `json:"serviceType,omitempty"`
	// ID for the Site the DPU Extension Service belongs to
	SiteId *string `json:"siteId,omitempty"`
	// ID for the Tenant the DPU Extension Service belongs to
	TenantId *string `json:"tenantId,omitempty"`
	// Latest version of the DPU Extension Service
	Version NullableString `json:"version,omitempty"`
	// Details for the latest version of the DPU Extension Service
	VersionInfo *DpuExtensionServiceVersionInfo `json:"versionInfo,omitempty"`
	// Latest and past versions of this DPU Extension Service that have not been deleted and are available for deployment
	ActiveVersions []string `json:"activeVersions,omitempty"`
	// Status of the DPU Extension Service
	Status *DpuExtensionServiceStatus `json:"status,omitempty"`
	// History of the DPU Extension Service statuses
	StatusHistory []StatusDetail `json:"statusHistory,omitempty"`
	// Date/time when the DPU Extension Service was created
	Created *time.Time `json:"created,omitempty"`
	// Date/time when the DPU Extension Service was last updated
	Updated *time.Time `json:"updated,omitempty"`
}

// NewDpuExtensionService instantiates a new DpuExtensionService object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDpuExtensionService() *DpuExtensionService {
	this := DpuExtensionService{}
	return &this
}

// NewDpuExtensionServiceWithDefaults instantiates a new DpuExtensionService object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDpuExtensionServiceWithDefaults() *DpuExtensionService {
	this := DpuExtensionService{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *DpuExtensionService) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DpuExtensionService) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *DpuExtensionService) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *DpuExtensionService) SetId(v string) {
	o.Id = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *DpuExtensionService) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DpuExtensionService) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *DpuExtensionService) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *DpuExtensionService) SetName(v string) {
	o.Name = &v
}

// GetDescription returns the Description field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *DpuExtensionService) GetDescription() string {
	if o == nil || IsNil(o.Description.Get()) {
		var ret string
		return ret
	}
	return *o.Description.Get()
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *DpuExtensionService) GetDescriptionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Description.Get(), o.Description.IsSet()
}

// HasDescription returns a boolean if a field has been set.
func (o *DpuExtensionService) HasDescription() bool {
	if o != nil && o.Description.IsSet() {
		return true
	}

	return false
}

// SetDescription gets a reference to the given NullableString and assigns it to the Description field.
func (o *DpuExtensionService) SetDescription(v string) {
	o.Description.Set(&v)
}

// SetDescriptionNil sets the value for Description to be an explicit nil
func (o *DpuExtensionService) SetDescriptionNil() {
	o.Description.Set(nil)
}

// UnsetDescription ensures that no value is present for Description, not even an explicit nil
func (o *DpuExtensionService) UnsetDescription() {
	o.Description.Unset()
}

// GetServiceType returns the ServiceType field value if set, zero value otherwise.
func (o *DpuExtensionService) GetServiceType() string {
	if o == nil || IsNil(o.ServiceType) {
		var ret string
		return ret
	}
	return *o.ServiceType
}

// GetServiceTypeOk returns a tuple with the ServiceType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DpuExtensionService) GetServiceTypeOk() (*string, bool) {
	if o == nil || IsNil(o.ServiceType) {
		return nil, false
	}
	return o.ServiceType, true
}

// HasServiceType returns a boolean if a field has been set.
func (o *DpuExtensionService) HasServiceType() bool {
	if o != nil && !IsNil(o.ServiceType) {
		return true
	}

	return false
}

// SetServiceType gets a reference to the given string and assigns it to the ServiceType field.
func (o *DpuExtensionService) SetServiceType(v string) {
	o.ServiceType = &v
}

// GetSiteId returns the SiteId field value if set, zero value otherwise.
func (o *DpuExtensionService) GetSiteId() string {
	if o == nil || IsNil(o.SiteId) {
		var ret string
		return ret
	}
	return *o.SiteId
}

// GetSiteIdOk returns a tuple with the SiteId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DpuExtensionService) GetSiteIdOk() (*string, bool) {
	if o == nil || IsNil(o.SiteId) {
		return nil, false
	}
	return o.SiteId, true
}

// HasSiteId returns a boolean if a field has been set.
func (o *DpuExtensionService) HasSiteId() bool {
	if o != nil && !IsNil(o.SiteId) {
		return true
	}

	return false
}

// SetSiteId gets a reference to the given string and assigns it to the SiteId field.
func (o *DpuExtensionService) SetSiteId(v string) {
	o.SiteId = &v
}

// GetTenantId returns the TenantId field value if set, zero value otherwise.
func (o *DpuExtensionService) GetTenantId() string {
	if o == nil || IsNil(o.TenantId) {
		var ret string
		return ret
	}
	return *o.TenantId
}

// GetTenantIdOk returns a tuple with the TenantId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DpuExtensionService) GetTenantIdOk() (*string, bool) {
	if o == nil || IsNil(o.TenantId) {
		return nil, false
	}
	return o.TenantId, true
}

// HasTenantId returns a boolean if a field has been set.
func (o *DpuExtensionService) HasTenantId() bool {
	if o != nil && !IsNil(o.TenantId) {
		return true
	}

	return false
}

// SetTenantId gets a reference to the given string and assigns it to the TenantId field.
func (o *DpuExtensionService) SetTenantId(v string) {
	o.TenantId = &v
}

// GetVersion returns the Version field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *DpuExtensionService) GetVersion() string {
	if o == nil || IsNil(o.Version.Get()) {
		var ret string
		return ret
	}
	return *o.Version.Get()
}

// GetVersionOk returns a tuple with the Version field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *DpuExtensionService) GetVersionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Version.Get(), o.Version.IsSet()
}

// HasVersion returns a boolean if a field has been set.
func (o *DpuExtensionService) HasVersion() bool {
	if o != nil && o.Version.IsSet() {
		return true
	}

	return false
}

// SetVersion gets a reference to the given NullableString and assigns it to the Version field.
func (o *DpuExtensionService) SetVersion(v string) {
	o.Version.Set(&v)
}

// SetVersionNil sets the value for Version to be an explicit nil
func (o *DpuExtensionService) SetVersionNil() {
	o.Version.Set(nil)
}

// UnsetVersion ensures that no value is present for Version, not even an explicit nil
func (o *DpuExtensionService) UnsetVersion() {
	o.Version.Unset()
}

// GetVersionInfo returns the VersionInfo field value if set, zero value otherwise.
func (o *DpuExtensionService) GetVersionInfo() DpuExtensionServiceVersionInfo {
	if o == nil || IsNil(o.VersionInfo) {
		var ret DpuExtensionServiceVersionInfo
		return ret
	}
	return *o.VersionInfo
}

// GetVersionInfoOk returns a tuple with the VersionInfo field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DpuExtensionService) GetVersionInfoOk() (*DpuExtensionServiceVersionInfo, bool) {
	if o == nil || IsNil(o.VersionInfo) {
		return nil, false
	}
	return o.VersionInfo, true
}

// HasVersionInfo returns a boolean if a field has been set.
func (o *DpuExtensionService) HasVersionInfo() bool {
	if o != nil && !IsNil(o.VersionInfo) {
		return true
	}

	return false
}

// SetVersionInfo gets a reference to the given DpuExtensionServiceVersionInfo and assigns it to the VersionInfo field.
func (o *DpuExtensionService) SetVersionInfo(v DpuExtensionServiceVersionInfo) {
	o.VersionInfo = &v
}

// GetActiveVersions returns the ActiveVersions field value if set, zero value otherwise.
func (o *DpuExtensionService) GetActiveVersions() []string {
	if o == nil || IsNil(o.ActiveVersions) {
		var ret []string
		return ret
	}
	return o.ActiveVersions
}

// GetActiveVersionsOk returns a tuple with the ActiveVersions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DpuExtensionService) GetActiveVersionsOk() ([]string, bool) {
	if o == nil || IsNil(o.ActiveVersions) {
		return nil, false
	}
	return o.ActiveVersions, true
}

// HasActiveVersions returns a boolean if a field has been set.
func (o *DpuExtensionService) HasActiveVersions() bool {
	if o != nil && !IsNil(o.ActiveVersions) {
		return true
	}

	return false
}

// SetActiveVersions gets a reference to the given []string and assigns it to the ActiveVersions field.
func (o *DpuExtensionService) SetActiveVersions(v []string) {
	o.ActiveVersions = v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *DpuExtensionService) GetStatus() DpuExtensionServiceStatus {
	if o == nil || IsNil(o.Status) {
		var ret DpuExtensionServiceStatus
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DpuExtensionService) GetStatusOk() (*DpuExtensionServiceStatus, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *DpuExtensionService) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given DpuExtensionServiceStatus and assigns it to the Status field.
func (o *DpuExtensionService) SetStatus(v DpuExtensionServiceStatus) {
	o.Status = &v
}

// GetStatusHistory returns the StatusHistory field value if set, zero value otherwise.
func (o *DpuExtensionService) GetStatusHistory() []StatusDetail {
	if o == nil || IsNil(o.StatusHistory) {
		var ret []StatusDetail
		return ret
	}
	return o.StatusHistory
}

// GetStatusHistoryOk returns a tuple with the StatusHistory field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DpuExtensionService) GetStatusHistoryOk() ([]StatusDetail, bool) {
	if o == nil || IsNil(o.StatusHistory) {
		return nil, false
	}
	return o.StatusHistory, true
}

// HasStatusHistory returns a boolean if a field has been set.
func (o *DpuExtensionService) HasStatusHistory() bool {
	if o != nil && !IsNil(o.StatusHistory) {
		return true
	}

	return false
}

// SetStatusHistory gets a reference to the given []StatusDetail and assigns it to the StatusHistory field.
func (o *DpuExtensionService) SetStatusHistory(v []StatusDetail) {
	o.StatusHistory = v
}

// GetCreated returns the Created field value if set, zero value otherwise.
func (o *DpuExtensionService) GetCreated() time.Time {
	if o == nil || IsNil(o.Created) {
		var ret time.Time
		return ret
	}
	return *o.Created
}

// GetCreatedOk returns a tuple with the Created field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DpuExtensionService) GetCreatedOk() (*time.Time, bool) {
	if o == nil || IsNil(o.Created) {
		return nil, false
	}
	return o.Created, true
}

// HasCreated returns a boolean if a field has been set.
func (o *DpuExtensionService) HasCreated() bool {
	if o != nil && !IsNil(o.Created) {
		return true
	}

	return false
}

// SetCreated gets a reference to the given time.Time and assigns it to the Created field.
func (o *DpuExtensionService) SetCreated(v time.Time) {
	o.Created = &v
}

// GetUpdated returns the Updated field value if set, zero value otherwise.
func (o *DpuExtensionService) GetUpdated() time.Time {
	if o == nil || IsNil(o.Updated) {
		var ret time.Time
		return ret
	}
	return *o.Updated
}

// GetUpdatedOk returns a tuple with the Updated field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DpuExtensionService) GetUpdatedOk() (*time.Time, bool) {
	if o == nil || IsNil(o.Updated) {
		return nil, false
	}
	return o.Updated, true
}

// HasUpdated returns a boolean if a field has been set.
func (o *DpuExtensionService) HasUpdated() bool {
	if o != nil && !IsNil(o.Updated) {
		return true
	}

	return false
}

// SetUpdated gets a reference to the given time.Time and assigns it to the Updated field.
func (o *DpuExtensionService) SetUpdated(v time.Time) {
	o.Updated = &v
}

func (o DpuExtensionService) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DpuExtensionService) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if o.Description.IsSet() {
		toSerialize["description"] = o.Description.Get()
	}
	if !IsNil(o.ServiceType) {
		toSerialize["serviceType"] = o.ServiceType
	}
	if !IsNil(o.SiteId) {
		toSerialize["siteId"] = o.SiteId
	}
	if !IsNil(o.TenantId) {
		toSerialize["tenantId"] = o.TenantId
	}
	if o.Version.IsSet() {
		toSerialize["version"] = o.Version.Get()
	}
	if !IsNil(o.VersionInfo) {
		toSerialize["versionInfo"] = o.VersionInfo
	}
	if !IsNil(o.ActiveVersions) {
		toSerialize["activeVersions"] = o.ActiveVersions
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	if !IsNil(o.StatusHistory) {
		toSerialize["statusHistory"] = o.StatusHistory
	}
	if !IsNil(o.Created) {
		toSerialize["created"] = o.Created
	}
	if !IsNil(o.Updated) {
		toSerialize["updated"] = o.Updated
	}
	return toSerialize, nil
}

type NullableDpuExtensionService struct {
	value *DpuExtensionService
	isSet bool
}

func (v NullableDpuExtensionService) Get() *DpuExtensionService {
	return v.value
}

func (v *NullableDpuExtensionService) Set(val *DpuExtensionService) {
	v.value = val
	v.isSet = true
}

func (v NullableDpuExtensionService) IsSet() bool {
	return v.isSet
}

func (v *NullableDpuExtensionService) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDpuExtensionService(val *DpuExtensionService) *NullableDpuExtensionService {
	return &NullableDpuExtensionService{value: val, isSet: true}
}

func (v NullableDpuExtensionService) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDpuExtensionService) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
