// SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

/*
NVIDIA Infra Controller REST API

NVIDIA Infra Controller REST API allows users to create and manage resources e.g. VPC, Subnets, Instances across all connected NVIDIA Infra Controller datacenters, also referred to as Sites.

API version: 1.6.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package standard

import (
	"encoding/json"
)

// checks if the SkuEthernetDevice type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SkuEthernetDevice{}

// SkuEthernetDevice Ethernet device component in a SKU
type SkuEthernetDevice struct {
	// Vendor of the ethernet device
	Vendor *string `json:"vendor,omitempty"`
	// Model of the ethernet device
	Model *string `json:"model,omitempty"`
	// Number of ethernet devices present
	Count *int32 `json:"count,omitempty"`
}

// NewSkuEthernetDevice instantiates a new SkuEthernetDevice object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSkuEthernetDevice() *SkuEthernetDevice {
	this := SkuEthernetDevice{}
	return &this
}

// NewSkuEthernetDeviceWithDefaults instantiates a new SkuEthernetDevice object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSkuEthernetDeviceWithDefaults() *SkuEthernetDevice {
	this := SkuEthernetDevice{}
	return &this
}

// GetVendor returns the Vendor field value if set, zero value otherwise.
func (o *SkuEthernetDevice) GetVendor() string {
	if o == nil || IsNil(o.Vendor) {
		var ret string
		return ret
	}
	return *o.Vendor
}

// GetVendorOk returns a tuple with the Vendor field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SkuEthernetDevice) GetVendorOk() (*string, bool) {
	if o == nil || IsNil(o.Vendor) {
		return nil, false
	}
	return o.Vendor, true
}

// HasVendor returns a boolean if a field has been set.
func (o *SkuEthernetDevice) HasVendor() bool {
	if o != nil && !IsNil(o.Vendor) {
		return true
	}

	return false
}

// SetVendor gets a reference to the given string and assigns it to the Vendor field.
func (o *SkuEthernetDevice) SetVendor(v string) {
	o.Vendor = &v
}

// GetModel returns the Model field value if set, zero value otherwise.
func (o *SkuEthernetDevice) GetModel() string {
	if o == nil || IsNil(o.Model) {
		var ret string
		return ret
	}
	return *o.Model
}

// GetModelOk returns a tuple with the Model field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SkuEthernetDevice) GetModelOk() (*string, bool) {
	if o == nil || IsNil(o.Model) {
		return nil, false
	}
	return o.Model, true
}

// HasModel returns a boolean if a field has been set.
func (o *SkuEthernetDevice) HasModel() bool {
	if o != nil && !IsNil(o.Model) {
		return true
	}

	return false
}

// SetModel gets a reference to the given string and assigns it to the Model field.
func (o *SkuEthernetDevice) SetModel(v string) {
	o.Model = &v
}

// GetCount returns the Count field value if set, zero value otherwise.
func (o *SkuEthernetDevice) GetCount() int32 {
	if o == nil || IsNil(o.Count) {
		var ret int32
		return ret
	}
	return *o.Count
}

// GetCountOk returns a tuple with the Count field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SkuEthernetDevice) GetCountOk() (*int32, bool) {
	if o == nil || IsNil(o.Count) {
		return nil, false
	}
	return o.Count, true
}

// HasCount returns a boolean if a field has been set.
func (o *SkuEthernetDevice) HasCount() bool {
	if o != nil && !IsNil(o.Count) {
		return true
	}

	return false
}

// SetCount gets a reference to the given int32 and assigns it to the Count field.
func (o *SkuEthernetDevice) SetCount(v int32) {
	o.Count = &v
}

func (o SkuEthernetDevice) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SkuEthernetDevice) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Vendor) {
		toSerialize["vendor"] = o.Vendor
	}
	if !IsNil(o.Model) {
		toSerialize["model"] = o.Model
	}
	if !IsNil(o.Count) {
		toSerialize["count"] = o.Count
	}
	return toSerialize, nil
}

type NullableSkuEthernetDevice struct {
	value *SkuEthernetDevice
	isSet bool
}

func (v NullableSkuEthernetDevice) Get() *SkuEthernetDevice {
	return v.value
}

func (v *NullableSkuEthernetDevice) Set(val *SkuEthernetDevice) {
	v.value = val
	v.isSet = true
}

func (v NullableSkuEthernetDevice) IsSet() bool {
	return v.isSet
}

func (v *NullableSkuEthernetDevice) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSkuEthernetDevice(val *SkuEthernetDevice) *NullableSkuEthernetDevice {
	return &NullableSkuEthernetDevice{value: val, isSet: true}
}

func (v NullableSkuEthernetDevice) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSkuEthernetDevice) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
