// SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

/*
NVIDIA Infra Controller REST API

NVIDIA Infra Controller REST API allows users to create and manage resources, e.g., VPCs, Subnets, and Instances, across all connected NVIDIA Infra Controller datacenters, also referred to as Sites.

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package standard

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the CreateRuleRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateRuleRequest{}

// CreateRuleRequest Request body for creating an Operation Rule.
type CreateRuleRequest struct {
	// ID of the Site to create the rule on.
	SiteId string `json:"siteId"`
	// Human-readable name of the rule.
	Name string `json:"name"`
	// Optional free-form description.
	Description *string `json:"description,omitempty"`
	// Operation type the rule applies to.
	OperationType string `json:"operationType"`
	// Operation code within the operation type (e.g. `power_on`).
	OperationCode  string         `json:"operationCode"`
	RuleDefinition RuleDefinition `json:"ruleDefinition"`
}

type _CreateRuleRequest CreateRuleRequest

// NewCreateRuleRequest instantiates a new CreateRuleRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateRuleRequest(siteId string, name string, operationType string, operationCode string, ruleDefinition RuleDefinition) *CreateRuleRequest {
	this := CreateRuleRequest{}
	this.SiteId = siteId
	this.Name = name
	this.OperationType = operationType
	this.OperationCode = operationCode
	this.RuleDefinition = ruleDefinition
	return &this
}

// NewCreateRuleRequestWithDefaults instantiates a new CreateRuleRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateRuleRequestWithDefaults() *CreateRuleRequest {
	this := CreateRuleRequest{}
	return &this
}

// GetSiteId returns the SiteId field value
func (o *CreateRuleRequest) GetSiteId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SiteId
}

// GetSiteIdOk returns a tuple with the SiteId field value
// and a boolean to check if the value has been set.
func (o *CreateRuleRequest) GetSiteIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SiteId, true
}

// SetSiteId sets field value
func (o *CreateRuleRequest) SetSiteId(v string) {
	o.SiteId = v
}

// GetName returns the Name field value
func (o *CreateRuleRequest) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *CreateRuleRequest) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *CreateRuleRequest) SetName(v string) {
	o.Name = v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *CreateRuleRequest) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateRuleRequest) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *CreateRuleRequest) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *CreateRuleRequest) SetDescription(v string) {
	o.Description = &v
}

// GetOperationType returns the OperationType field value
func (o *CreateRuleRequest) GetOperationType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.OperationType
}

// GetOperationTypeOk returns a tuple with the OperationType field value
// and a boolean to check if the value has been set.
func (o *CreateRuleRequest) GetOperationTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OperationType, true
}

// SetOperationType sets field value
func (o *CreateRuleRequest) SetOperationType(v string) {
	o.OperationType = v
}

// GetOperationCode returns the OperationCode field value
func (o *CreateRuleRequest) GetOperationCode() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.OperationCode
}

// GetOperationCodeOk returns a tuple with the OperationCode field value
// and a boolean to check if the value has been set.
func (o *CreateRuleRequest) GetOperationCodeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OperationCode, true
}

// SetOperationCode sets field value
func (o *CreateRuleRequest) SetOperationCode(v string) {
	o.OperationCode = v
}

// GetRuleDefinition returns the RuleDefinition field value
func (o *CreateRuleRequest) GetRuleDefinition() RuleDefinition {
	if o == nil {
		var ret RuleDefinition
		return ret
	}

	return o.RuleDefinition
}

// GetRuleDefinitionOk returns a tuple with the RuleDefinition field value
// and a boolean to check if the value has been set.
func (o *CreateRuleRequest) GetRuleDefinitionOk() (*RuleDefinition, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RuleDefinition, true
}

// SetRuleDefinition sets field value
func (o *CreateRuleRequest) SetRuleDefinition(v RuleDefinition) {
	o.RuleDefinition = v
}

func (o CreateRuleRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateRuleRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["siteId"] = o.SiteId
	toSerialize["name"] = o.Name
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	toSerialize["operationType"] = o.OperationType
	toSerialize["operationCode"] = o.OperationCode
	toSerialize["ruleDefinition"] = o.RuleDefinition
	return toSerialize, nil
}

func (o *CreateRuleRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"siteId",
		"name",
		"operationType",
		"operationCode",
		"ruleDefinition",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if value, exists := allProperties[requiredProperty]; !exists || value == nil {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateRuleRequest := _CreateRuleRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCreateRuleRequest)

	if err != nil {
		return err
	}

	*o = CreateRuleRequest(varCreateRuleRequest)

	return err
}

type NullableCreateRuleRequest struct {
	value *CreateRuleRequest
	isSet bool
}

func (v NullableCreateRuleRequest) Get() *CreateRuleRequest {
	return v.value
}

func (v *NullableCreateRuleRequest) Set(val *CreateRuleRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateRuleRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateRuleRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateRuleRequest(val *CreateRuleRequest) *NullableCreateRuleRequest {
	return &NullableCreateRuleRequest{value: val, isSet: true}
}

func (v NullableCreateRuleRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateRuleRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
