// SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

/*
NVIDIA Infra Controller REST API

NVIDIA Infra Controller REST API allows users to create and manage resources, e.g., VPCs, Subnets, and Instances, across all connected NVIDIA Infra Controller datacenters, also referred to as Sites.

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package standard

import (
	"encoding/json"
)

// checks if the TaskRunSelector type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TaskRunSelector{}

// TaskRunSelector Selects a subset of candidate Racks. Percentage is the only supported selector today.
type TaskRunSelector struct {
	Percentage *TaskRunPercentageSelector `json:"percentage,omitempty"`
}

// NewTaskRunSelector instantiates a new TaskRunSelector object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTaskRunSelector() *TaskRunSelector {
	this := TaskRunSelector{}
	return &this
}

// NewTaskRunSelectorWithDefaults instantiates a new TaskRunSelector object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTaskRunSelectorWithDefaults() *TaskRunSelector {
	this := TaskRunSelector{}
	return &this
}

// GetPercentage returns the Percentage field value if set, zero value otherwise.
func (o *TaskRunSelector) GetPercentage() TaskRunPercentageSelector {
	if o == nil || IsNil(o.Percentage) {
		var ret TaskRunPercentageSelector
		return ret
	}
	return *o.Percentage
}

// GetPercentageOk returns a tuple with the Percentage field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TaskRunSelector) GetPercentageOk() (*TaskRunPercentageSelector, bool) {
	if o == nil || IsNil(o.Percentage) {
		return nil, false
	}
	return o.Percentage, true
}

// HasPercentage returns a boolean if a field has been set.
func (o *TaskRunSelector) HasPercentage() bool {
	if o != nil && !IsNil(o.Percentage) {
		return true
	}

	return false
}

// SetPercentage gets a reference to the given TaskRunPercentageSelector and assigns it to the Percentage field.
func (o *TaskRunSelector) SetPercentage(v TaskRunPercentageSelector) {
	o.Percentage = &v
}

func (o TaskRunSelector) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TaskRunSelector) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Percentage) {
		toSerialize["percentage"] = o.Percentage
	}
	return toSerialize, nil
}

type NullableTaskRunSelector struct {
	value *TaskRunSelector
	isSet bool
}

func (v NullableTaskRunSelector) Get() *TaskRunSelector {
	return v.value
}

func (v *NullableTaskRunSelector) Set(val *TaskRunSelector) {
	v.value = val
	v.isSet = true
}

func (v NullableTaskRunSelector) IsSet() bool {
	return v.isSet
}

func (v *NullableTaskRunSelector) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTaskRunSelector(val *TaskRunSelector) *NullableTaskRunSelector {
	return &NullableTaskRunSelector{value: val, isSet: true}
}

func (v NullableTaskRunSelector) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTaskRunSelector) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
