// SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

/*
NVIDIA Infra Controller REST API

NVIDIA Infra Controller REST API allows users to create and manage resources e.g. VPC, Subnets, Instances across all connected NVIDIA Infra Controller datacenters, also referred to as Sites.

API version: 1.6.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package standard

import (
	"encoding/json"
)

// checks if the TenantAccountCountByStatus type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TenantAccountCountByStatus{}

// TenantAccountCountByStatus Describes counts of Tenant Accounts in various statuses
type TenantAccountCountByStatus struct {
	Total   *int32 `json:"total,omitempty"`
	Pending *int32 `json:"pending,omitempty"`
	Invited *int32 `json:"invited,omitempty"`
	Ready   *int32 `json:"ready,omitempty"`
	Error   *int32 `json:"error,omitempty"`
}

// NewTenantAccountCountByStatus instantiates a new TenantAccountCountByStatus object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTenantAccountCountByStatus() *TenantAccountCountByStatus {
	this := TenantAccountCountByStatus{}
	return &this
}

// NewTenantAccountCountByStatusWithDefaults instantiates a new TenantAccountCountByStatus object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTenantAccountCountByStatusWithDefaults() *TenantAccountCountByStatus {
	this := TenantAccountCountByStatus{}
	return &this
}

// GetTotal returns the Total field value if set, zero value otherwise.
func (o *TenantAccountCountByStatus) GetTotal() int32 {
	if o == nil || IsNil(o.Total) {
		var ret int32
		return ret
	}
	return *o.Total
}

// GetTotalOk returns a tuple with the Total field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TenantAccountCountByStatus) GetTotalOk() (*int32, bool) {
	if o == nil || IsNil(o.Total) {
		return nil, false
	}
	return o.Total, true
}

// HasTotal returns a boolean if a field has been set.
func (o *TenantAccountCountByStatus) HasTotal() bool {
	if o != nil && !IsNil(o.Total) {
		return true
	}

	return false
}

// SetTotal gets a reference to the given int32 and assigns it to the Total field.
func (o *TenantAccountCountByStatus) SetTotal(v int32) {
	o.Total = &v
}

// GetPending returns the Pending field value if set, zero value otherwise.
func (o *TenantAccountCountByStatus) GetPending() int32 {
	if o == nil || IsNil(o.Pending) {
		var ret int32
		return ret
	}
	return *o.Pending
}

// GetPendingOk returns a tuple with the Pending field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TenantAccountCountByStatus) GetPendingOk() (*int32, bool) {
	if o == nil || IsNil(o.Pending) {
		return nil, false
	}
	return o.Pending, true
}

// HasPending returns a boolean if a field has been set.
func (o *TenantAccountCountByStatus) HasPending() bool {
	if o != nil && !IsNil(o.Pending) {
		return true
	}

	return false
}

// SetPending gets a reference to the given int32 and assigns it to the Pending field.
func (o *TenantAccountCountByStatus) SetPending(v int32) {
	o.Pending = &v
}

// GetInvited returns the Invited field value if set, zero value otherwise.
func (o *TenantAccountCountByStatus) GetInvited() int32 {
	if o == nil || IsNil(o.Invited) {
		var ret int32
		return ret
	}
	return *o.Invited
}

// GetInvitedOk returns a tuple with the Invited field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TenantAccountCountByStatus) GetInvitedOk() (*int32, bool) {
	if o == nil || IsNil(o.Invited) {
		return nil, false
	}
	return o.Invited, true
}

// HasInvited returns a boolean if a field has been set.
func (o *TenantAccountCountByStatus) HasInvited() bool {
	if o != nil && !IsNil(o.Invited) {
		return true
	}

	return false
}

// SetInvited gets a reference to the given int32 and assigns it to the Invited field.
func (o *TenantAccountCountByStatus) SetInvited(v int32) {
	o.Invited = &v
}

// GetReady returns the Ready field value if set, zero value otherwise.
func (o *TenantAccountCountByStatus) GetReady() int32 {
	if o == nil || IsNil(o.Ready) {
		var ret int32
		return ret
	}
	return *o.Ready
}

// GetReadyOk returns a tuple with the Ready field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TenantAccountCountByStatus) GetReadyOk() (*int32, bool) {
	if o == nil || IsNil(o.Ready) {
		return nil, false
	}
	return o.Ready, true
}

// HasReady returns a boolean if a field has been set.
func (o *TenantAccountCountByStatus) HasReady() bool {
	if o != nil && !IsNil(o.Ready) {
		return true
	}

	return false
}

// SetReady gets a reference to the given int32 and assigns it to the Ready field.
func (o *TenantAccountCountByStatus) SetReady(v int32) {
	o.Ready = &v
}

// GetError returns the Error field value if set, zero value otherwise.
func (o *TenantAccountCountByStatus) GetError() int32 {
	if o == nil || IsNil(o.Error) {
		var ret int32
		return ret
	}
	return *o.Error
}

// GetErrorOk returns a tuple with the Error field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TenantAccountCountByStatus) GetErrorOk() (*int32, bool) {
	if o == nil || IsNil(o.Error) {
		return nil, false
	}
	return o.Error, true
}

// HasError returns a boolean if a field has been set.
func (o *TenantAccountCountByStatus) HasError() bool {
	if o != nil && !IsNil(o.Error) {
		return true
	}

	return false
}

// SetError gets a reference to the given int32 and assigns it to the Error field.
func (o *TenantAccountCountByStatus) SetError(v int32) {
	o.Error = &v
}

func (o TenantAccountCountByStatus) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TenantAccountCountByStatus) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Total) {
		toSerialize["total"] = o.Total
	}
	if !IsNil(o.Pending) {
		toSerialize["pending"] = o.Pending
	}
	if !IsNil(o.Invited) {
		toSerialize["invited"] = o.Invited
	}
	if !IsNil(o.Ready) {
		toSerialize["ready"] = o.Ready
	}
	if !IsNil(o.Error) {
		toSerialize["error"] = o.Error
	}
	return toSerialize, nil
}

type NullableTenantAccountCountByStatus struct {
	value *TenantAccountCountByStatus
	isSet bool
}

func (v NullableTenantAccountCountByStatus) Get() *TenantAccountCountByStatus {
	return v.value
}

func (v *NullableTenantAccountCountByStatus) Set(val *TenantAccountCountByStatus) {
	v.value = val
	v.isSet = true
}

func (v NullableTenantAccountCountByStatus) IsSet() bool {
	return v.isSet
}

func (v *NullableTenantAccountCountByStatus) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTenantAccountCountByStatus(val *TenantAccountCountByStatus) *NullableTenantAccountCountByStatus {
	return &NullableTenantAccountCountByStatus{value: val, isSet: true}
}

func (v NullableTenantAccountCountByStatus) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTenantAccountCountByStatus) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
