// SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

/*
NVIDIA Infra Controller REST API

NVIDIA Infra Controller REST API allows users to create and manage resources, e.g., VPCs, Subnets, and Instances, across all connected NVIDIA Infra Controller datacenters, also referred to as Sites.

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package standard

import (
	"encoding/json"
)

// checks if the TaskRunConflictPolicy type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TaskRunConflictPolicy{}

// TaskRunConflictPolicy Configures how blocked targets are retried. Retry is the only supported strategy today.
type TaskRunConflictPolicy struct {
	Retry *TaskRunConflictRetry `json:"retry,omitempty"`
}

// NewTaskRunConflictPolicy instantiates a new TaskRunConflictPolicy object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTaskRunConflictPolicy() *TaskRunConflictPolicy {
	this := TaskRunConflictPolicy{}
	return &this
}

// NewTaskRunConflictPolicyWithDefaults instantiates a new TaskRunConflictPolicy object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTaskRunConflictPolicyWithDefaults() *TaskRunConflictPolicy {
	this := TaskRunConflictPolicy{}
	return &this
}

// GetRetry returns the Retry field value if set, zero value otherwise.
func (o *TaskRunConflictPolicy) GetRetry() TaskRunConflictRetry {
	if o == nil || IsNil(o.Retry) {
		var ret TaskRunConflictRetry
		return ret
	}
	return *o.Retry
}

// GetRetryOk returns a tuple with the Retry field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TaskRunConflictPolicy) GetRetryOk() (*TaskRunConflictRetry, bool) {
	if o == nil || IsNil(o.Retry) {
		return nil, false
	}
	return o.Retry, true
}

// HasRetry returns a boolean if a field has been set.
func (o *TaskRunConflictPolicy) HasRetry() bool {
	if o != nil && !IsNil(o.Retry) {
		return true
	}

	return false
}

// SetRetry gets a reference to the given TaskRunConflictRetry and assigns it to the Retry field.
func (o *TaskRunConflictPolicy) SetRetry(v TaskRunConflictRetry) {
	o.Retry = &v
}

func (o TaskRunConflictPolicy) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TaskRunConflictPolicy) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Retry) {
		toSerialize["retry"] = o.Retry
	}
	return toSerialize, nil
}

type NullableTaskRunConflictPolicy struct {
	value *TaskRunConflictPolicy
	isSet bool
}

func (v NullableTaskRunConflictPolicy) Get() *TaskRunConflictPolicy {
	return v.value
}

func (v *NullableTaskRunConflictPolicy) Set(val *TaskRunConflictPolicy) {
	v.value = val
	v.isSet = true
}

func (v NullableTaskRunConflictPolicy) IsSet() bool {
	return v.isSet
}

func (v *NullableTaskRunConflictPolicy) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTaskRunConflictPolicy(val *TaskRunConflictPolicy) *NullableTaskRunConflictPolicy {
	return &NullableTaskRunConflictPolicy{value: val, isSet: true}
}

func (v NullableTaskRunConflictPolicy) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTaskRunConflictPolicy) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
