// SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

/*
NVIDIA Infra Controller REST API

NVIDIA Infra Controller REST API allows users to create and manage resources, e.g., VPCs, Subnets, and Instances, across all connected NVIDIA Infra Controller datacenters, also referred to as Sites.

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package standard

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the TaskRunOptions type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TaskRunOptions{}

// TaskRunOptions Execution policy for the Task Run.
type TaskRunOptions struct {
	// Caps how many targets may have active child Tasks at once. Must be greater than zero.
	MaxConcurrentTargets int32                  `json:"maxConcurrentTargets"`
	SafetyPolicy         *TaskRunSafetyPolicy   `json:"safetyPolicy,omitempty"`
	ConflictPolicy       *TaskRunConflictPolicy `json:"conflictPolicy,omitempty"`
	OrderingPolicy       *TaskRunOrderingPolicy `json:"orderingPolicy,omitempty"`
	PhasePolicy          *TaskRunPhasePolicy    `json:"phasePolicy,omitempty"`
}

type _TaskRunOptions TaskRunOptions

// NewTaskRunOptions instantiates a new TaskRunOptions object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTaskRunOptions(maxConcurrentTargets int32) *TaskRunOptions {
	this := TaskRunOptions{}
	this.MaxConcurrentTargets = maxConcurrentTargets
	return &this
}

// NewTaskRunOptionsWithDefaults instantiates a new TaskRunOptions object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTaskRunOptionsWithDefaults() *TaskRunOptions {
	this := TaskRunOptions{}
	return &this
}

// GetMaxConcurrentTargets returns the MaxConcurrentTargets field value
func (o *TaskRunOptions) GetMaxConcurrentTargets() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.MaxConcurrentTargets
}

// GetMaxConcurrentTargetsOk returns a tuple with the MaxConcurrentTargets field value
// and a boolean to check if the value has been set.
func (o *TaskRunOptions) GetMaxConcurrentTargetsOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MaxConcurrentTargets, true
}

// SetMaxConcurrentTargets sets field value
func (o *TaskRunOptions) SetMaxConcurrentTargets(v int32) {
	o.MaxConcurrentTargets = v
}

// GetSafetyPolicy returns the SafetyPolicy field value if set, zero value otherwise.
func (o *TaskRunOptions) GetSafetyPolicy() TaskRunSafetyPolicy {
	if o == nil || IsNil(o.SafetyPolicy) {
		var ret TaskRunSafetyPolicy
		return ret
	}
	return *o.SafetyPolicy
}

// GetSafetyPolicyOk returns a tuple with the SafetyPolicy field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TaskRunOptions) GetSafetyPolicyOk() (*TaskRunSafetyPolicy, bool) {
	if o == nil || IsNil(o.SafetyPolicy) {
		return nil, false
	}
	return o.SafetyPolicy, true
}

// HasSafetyPolicy returns a boolean if a field has been set.
func (o *TaskRunOptions) HasSafetyPolicy() bool {
	if o != nil && !IsNil(o.SafetyPolicy) {
		return true
	}

	return false
}

// SetSafetyPolicy gets a reference to the given TaskRunSafetyPolicy and assigns it to the SafetyPolicy field.
func (o *TaskRunOptions) SetSafetyPolicy(v TaskRunSafetyPolicy) {
	o.SafetyPolicy = &v
}

// GetConflictPolicy returns the ConflictPolicy field value if set, zero value otherwise.
func (o *TaskRunOptions) GetConflictPolicy() TaskRunConflictPolicy {
	if o == nil || IsNil(o.ConflictPolicy) {
		var ret TaskRunConflictPolicy
		return ret
	}
	return *o.ConflictPolicy
}

// GetConflictPolicyOk returns a tuple with the ConflictPolicy field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TaskRunOptions) GetConflictPolicyOk() (*TaskRunConflictPolicy, bool) {
	if o == nil || IsNil(o.ConflictPolicy) {
		return nil, false
	}
	return o.ConflictPolicy, true
}

// HasConflictPolicy returns a boolean if a field has been set.
func (o *TaskRunOptions) HasConflictPolicy() bool {
	if o != nil && !IsNil(o.ConflictPolicy) {
		return true
	}

	return false
}

// SetConflictPolicy gets a reference to the given TaskRunConflictPolicy and assigns it to the ConflictPolicy field.
func (o *TaskRunOptions) SetConflictPolicy(v TaskRunConflictPolicy) {
	o.ConflictPolicy = &v
}

// GetOrderingPolicy returns the OrderingPolicy field value if set, zero value otherwise.
func (o *TaskRunOptions) GetOrderingPolicy() TaskRunOrderingPolicy {
	if o == nil || IsNil(o.OrderingPolicy) {
		var ret TaskRunOrderingPolicy
		return ret
	}
	return *o.OrderingPolicy
}

// GetOrderingPolicyOk returns a tuple with the OrderingPolicy field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TaskRunOptions) GetOrderingPolicyOk() (*TaskRunOrderingPolicy, bool) {
	if o == nil || IsNil(o.OrderingPolicy) {
		return nil, false
	}
	return o.OrderingPolicy, true
}

// HasOrderingPolicy returns a boolean if a field has been set.
func (o *TaskRunOptions) HasOrderingPolicy() bool {
	if o != nil && !IsNil(o.OrderingPolicy) {
		return true
	}

	return false
}

// SetOrderingPolicy gets a reference to the given TaskRunOrderingPolicy and assigns it to the OrderingPolicy field.
func (o *TaskRunOptions) SetOrderingPolicy(v TaskRunOrderingPolicy) {
	o.OrderingPolicy = &v
}

// GetPhasePolicy returns the PhasePolicy field value if set, zero value otherwise.
func (o *TaskRunOptions) GetPhasePolicy() TaskRunPhasePolicy {
	if o == nil || IsNil(o.PhasePolicy) {
		var ret TaskRunPhasePolicy
		return ret
	}
	return *o.PhasePolicy
}

// GetPhasePolicyOk returns a tuple with the PhasePolicy field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TaskRunOptions) GetPhasePolicyOk() (*TaskRunPhasePolicy, bool) {
	if o == nil || IsNil(o.PhasePolicy) {
		return nil, false
	}
	return o.PhasePolicy, true
}

// HasPhasePolicy returns a boolean if a field has been set.
func (o *TaskRunOptions) HasPhasePolicy() bool {
	if o != nil && !IsNil(o.PhasePolicy) {
		return true
	}

	return false
}

// SetPhasePolicy gets a reference to the given TaskRunPhasePolicy and assigns it to the PhasePolicy field.
func (o *TaskRunOptions) SetPhasePolicy(v TaskRunPhasePolicy) {
	o.PhasePolicy = &v
}

func (o TaskRunOptions) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TaskRunOptions) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["maxConcurrentTargets"] = o.MaxConcurrentTargets
	if !IsNil(o.SafetyPolicy) {
		toSerialize["safetyPolicy"] = o.SafetyPolicy
	}
	if !IsNil(o.ConflictPolicy) {
		toSerialize["conflictPolicy"] = o.ConflictPolicy
	}
	if !IsNil(o.OrderingPolicy) {
		toSerialize["orderingPolicy"] = o.OrderingPolicy
	}
	if !IsNil(o.PhasePolicy) {
		toSerialize["phasePolicy"] = o.PhasePolicy
	}
	return toSerialize, nil
}

func (o *TaskRunOptions) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"maxConcurrentTargets",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if value, exists := allProperties[requiredProperty]; !exists || value == nil {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varTaskRunOptions := _TaskRunOptions{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	err = decoder.Decode(&varTaskRunOptions)

	if err != nil {
		return err
	}

	*o = TaskRunOptions(varTaskRunOptions)

	return err
}

type NullableTaskRunOptions struct {
	value *TaskRunOptions
	isSet bool
}

func (v NullableTaskRunOptions) Get() *TaskRunOptions {
	return v.value
}

func (v *NullableTaskRunOptions) Set(val *TaskRunOptions) {
	v.value = val
	v.isSet = true
}

func (v NullableTaskRunOptions) IsSet() bool {
	return v.isSet
}

func (v *NullableTaskRunOptions) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTaskRunOptions(val *TaskRunOptions) *NullableTaskRunOptions {
	return &NullableTaskRunOptions{value: val, isSet: true}
}

func (v NullableTaskRunOptions) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTaskRunOptions) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
