// SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

/*
NVIDIA Infra Controller REST API

NVIDIA Infra Controller REST API allows users to create and manage resources e.g. VPC, Subnets, Instances across all connected NVIDIA Infra Controller datacenters, also referred to as Sites.

API version: 1.6.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package standard

import (
	"encoding/json"
	"fmt"
)

// IpBlockStatus Status values for IP Block objects
type IpBlockStatus string

// List of IpBlockStatus
const (
	IPBLOCKSTATUS_PENDING      IpBlockStatus = "Pending"
	IPBLOCKSTATUS_PROVISIONING IpBlockStatus = "Provisioning"
	IPBLOCKSTATUS_READY        IpBlockStatus = "Ready"
	IPBLOCKSTATUS_DELETING     IpBlockStatus = "Deleting"
	IPBLOCKSTATUS_ERROR        IpBlockStatus = "Error"
)

// All allowed values of IpBlockStatus enum
var AllowedIpBlockStatusEnumValues = []IpBlockStatus{
	"Pending",
	"Provisioning",
	"Ready",
	"Deleting",
	"Error",
}

func (v *IpBlockStatus) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := IpBlockStatus(value)
	for _, existing := range AllowedIpBlockStatusEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid IpBlockStatus", value)
}

// NewIpBlockStatusFromValue returns a pointer to a valid IpBlockStatus
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewIpBlockStatusFromValue(v string) (*IpBlockStatus, error) {
	ev := IpBlockStatus(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for IpBlockStatus: valid values are %v", v, AllowedIpBlockStatusEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v IpBlockStatus) IsValid() bool {
	for _, existing := range AllowedIpBlockStatusEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to IpBlockStatus value
func (v IpBlockStatus) Ptr() *IpBlockStatus {
	return &v
}

type NullableIpBlockStatus struct {
	value *IpBlockStatus
	isSet bool
}

func (v NullableIpBlockStatus) Get() *IpBlockStatus {
	return v.value
}

func (v *NullableIpBlockStatus) Set(val *IpBlockStatus) {
	v.value = val
	v.isSet = true
}

func (v NullableIpBlockStatus) IsSet() bool {
	return v.isSet
}

func (v *NullableIpBlockStatus) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableIpBlockStatus(val *IpBlockStatus) *NullableIpBlockStatus {
	return &NullableIpBlockStatus{value: val, isSet: true}
}

func (v NullableIpBlockStatus) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableIpBlockStatus) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
