{{- if .Values.flowConfig }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: flow-config-files
  namespace: {{ include "nico-flow.namespace" . }}
  labels:
    {{- include "nico-flow.labels" . | nindent 4 }}
data:
  flowconfig.yaml: |
{{ .Values.flowConfig | indent 4 }}
{{- end }}
