apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "nico-bmc-proxy.name" . }}
  namespace: {{ include "nico-bmc-proxy.namespace" . }}
  labels:
    {{- include "nico-bmc-proxy.labels" . | nindent 4 }}
