#
# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
ARG CONTAINER_RUNTIME_AARCH64

FROM $CONTAINER_RUNTIME_AARCH64

WORKDIR /
COPY crates/machine-validation/config /machine-validation/config
RUN cd /machine-validation/config && tar -cvf /tmp/config.tar . && cp /tmp/config.tar /machine-validation/config/
COPY crates/machine-validation/images /machine-validation/images

CMD exec /bin/sh -c "trap : TERM INT; sleep 9999999999d & wait"
